
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `General` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model General
 * 
 */
export type GeneralModel = runtime.Types.Result.DefaultSelection<Prisma.$GeneralPayload>

export type AggregateGeneral = {
  _count: GeneralCountAggregateOutputType | null
  _avg: GeneralAvgAggregateOutputType | null
  _sum: GeneralSumAggregateOutputType | null
  _min: GeneralMinAggregateOutputType | null
  _max: GeneralMaxAggregateOutputType | null
}

export type GeneralAvgAggregateOutputType = {
  log_freq: number | null
}

export type GeneralSumAggregateOutputType = {
  log_freq: number | null
}

export type GeneralMinAggregateOutputType = {
  key: string | null
  c_name: string | null
  c_logo: string | null
  license_key: string | null
  log_freq: number | null
}

export type GeneralMaxAggregateOutputType = {
  key: string | null
  c_name: string | null
  c_logo: string | null
  license_key: string | null
  log_freq: number | null
}

export type GeneralCountAggregateOutputType = {
  key: number
  c_name: number
  c_logo: number
  license_key: number
  log_freq: number
  _all: number
}


export type GeneralAvgAggregateInputType = {
  log_freq?: true
}

export type GeneralSumAggregateInputType = {
  log_freq?: true
}

export type GeneralMinAggregateInputType = {
  key?: true
  c_name?: true
  c_logo?: true
  license_key?: true
  log_freq?: true
}

export type GeneralMaxAggregateInputType = {
  key?: true
  c_name?: true
  c_logo?: true
  license_key?: true
  log_freq?: true
}

export type GeneralCountAggregateInputType = {
  key?: true
  c_name?: true
  c_logo?: true
  license_key?: true
  log_freq?: true
  _all?: true
}

export type GeneralAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which General to aggregate.
   */
  where?: Prisma.GeneralWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Generals to fetch.
   */
  orderBy?: Prisma.GeneralOrderByWithRelationInput | Prisma.GeneralOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.GeneralWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Generals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Generals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Generals
  **/
  _count?: true | GeneralCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: GeneralAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: GeneralSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: GeneralMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: GeneralMaxAggregateInputType
}

export type GetGeneralAggregateType<T extends GeneralAggregateArgs> = {
      [P in keyof T & keyof AggregateGeneral]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateGeneral[P]>
    : Prisma.GetScalarType<T[P], AggregateGeneral[P]>
}




export type GeneralGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GeneralWhereInput
  orderBy?: Prisma.GeneralOrderByWithAggregationInput | Prisma.GeneralOrderByWithAggregationInput[]
  by: Prisma.GeneralScalarFieldEnum[] | Prisma.GeneralScalarFieldEnum
  having?: Prisma.GeneralScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: GeneralCountAggregateInputType | true
  _avg?: GeneralAvgAggregateInputType
  _sum?: GeneralSumAggregateInputType
  _min?: GeneralMinAggregateInputType
  _max?: GeneralMaxAggregateInputType
}

export type GeneralGroupByOutputType = {
  key: string
  c_name: string
  c_logo: string
  license_key: string
  log_freq: number
  _count: GeneralCountAggregateOutputType | null
  _avg: GeneralAvgAggregateOutputType | null
  _sum: GeneralSumAggregateOutputType | null
  _min: GeneralMinAggregateOutputType | null
  _max: GeneralMaxAggregateOutputType | null
}

type GetGeneralGroupByPayload<T extends GeneralGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<GeneralGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof GeneralGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], GeneralGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], GeneralGroupByOutputType[P]>
      }
    >
  >



export type GeneralWhereInput = {
  AND?: Prisma.GeneralWhereInput | Prisma.GeneralWhereInput[]
  OR?: Prisma.GeneralWhereInput[]
  NOT?: Prisma.GeneralWhereInput | Prisma.GeneralWhereInput[]
  key?: Prisma.StringFilter<"General"> | string
  c_name?: Prisma.StringFilter<"General"> | string
  c_logo?: Prisma.StringFilter<"General"> | string
  license_key?: Prisma.StringFilter<"General"> | string
  log_freq?: Prisma.IntFilter<"General"> | number
}

export type GeneralOrderByWithRelationInput = {
  key?: Prisma.SortOrder
  c_name?: Prisma.SortOrder
  c_logo?: Prisma.SortOrder
  license_key?: Prisma.SortOrder
  log_freq?: Prisma.SortOrder
}

export type GeneralWhereUniqueInput = Prisma.AtLeast<{
  key?: string
  AND?: Prisma.GeneralWhereInput | Prisma.GeneralWhereInput[]
  OR?: Prisma.GeneralWhereInput[]
  NOT?: Prisma.GeneralWhereInput | Prisma.GeneralWhereInput[]
  c_name?: Prisma.StringFilter<"General"> | string
  c_logo?: Prisma.StringFilter<"General"> | string
  license_key?: Prisma.StringFilter<"General"> | string
  log_freq?: Prisma.IntFilter<"General"> | number
}, "key">

export type GeneralOrderByWithAggregationInput = {
  key?: Prisma.SortOrder
  c_name?: Prisma.SortOrder
  c_logo?: Prisma.SortOrder
  license_key?: Prisma.SortOrder
  log_freq?: Prisma.SortOrder
  _count?: Prisma.GeneralCountOrderByAggregateInput
  _avg?: Prisma.GeneralAvgOrderByAggregateInput
  _max?: Prisma.GeneralMaxOrderByAggregateInput
  _min?: Prisma.GeneralMinOrderByAggregateInput
  _sum?: Prisma.GeneralSumOrderByAggregateInput
}

export type GeneralScalarWhereWithAggregatesInput = {
  AND?: Prisma.GeneralScalarWhereWithAggregatesInput | Prisma.GeneralScalarWhereWithAggregatesInput[]
  OR?: Prisma.GeneralScalarWhereWithAggregatesInput[]
  NOT?: Prisma.GeneralScalarWhereWithAggregatesInput | Prisma.GeneralScalarWhereWithAggregatesInput[]
  key?: Prisma.StringWithAggregatesFilter<"General"> | string
  c_name?: Prisma.StringWithAggregatesFilter<"General"> | string
  c_logo?: Prisma.StringWithAggregatesFilter<"General"> | string
  license_key?: Prisma.StringWithAggregatesFilter<"General"> | string
  log_freq?: Prisma.IntWithAggregatesFilter<"General"> | number
}

export type GeneralCreateInput = {
  key: string
  c_name: string
  c_logo: string
  license_key: string
  log_freq: number
}

export type GeneralUncheckedCreateInput = {
  key: string
  c_name: string
  c_logo: string
  license_key: string
  log_freq: number
}

export type GeneralUpdateInput = {
  key?: Prisma.StringFieldUpdateOperationsInput | string
  c_name?: Prisma.StringFieldUpdateOperationsInput | string
  c_logo?: Prisma.StringFieldUpdateOperationsInput | string
  license_key?: Prisma.StringFieldUpdateOperationsInput | string
  log_freq?: Prisma.IntFieldUpdateOperationsInput | number
}

export type GeneralUncheckedUpdateInput = {
  key?: Prisma.StringFieldUpdateOperationsInput | string
  c_name?: Prisma.StringFieldUpdateOperationsInput | string
  c_logo?: Prisma.StringFieldUpdateOperationsInput | string
  license_key?: Prisma.StringFieldUpdateOperationsInput | string
  log_freq?: Prisma.IntFieldUpdateOperationsInput | number
}

export type GeneralCreateManyInput = {
  key: string
  c_name: string
  c_logo: string
  license_key: string
  log_freq: number
}

export type GeneralUpdateManyMutationInput = {
  key?: Prisma.StringFieldUpdateOperationsInput | string
  c_name?: Prisma.StringFieldUpdateOperationsInput | string
  c_logo?: Prisma.StringFieldUpdateOperationsInput | string
  license_key?: Prisma.StringFieldUpdateOperationsInput | string
  log_freq?: Prisma.IntFieldUpdateOperationsInput | number
}

export type GeneralUncheckedUpdateManyInput = {
  key?: Prisma.StringFieldUpdateOperationsInput | string
  c_name?: Prisma.StringFieldUpdateOperationsInput | string
  c_logo?: Prisma.StringFieldUpdateOperationsInput | string
  license_key?: Prisma.StringFieldUpdateOperationsInput | string
  log_freq?: Prisma.IntFieldUpdateOperationsInput | number
}

export type GeneralCountOrderByAggregateInput = {
  key?: Prisma.SortOrder
  c_name?: Prisma.SortOrder
  c_logo?: Prisma.SortOrder
  license_key?: Prisma.SortOrder
  log_freq?: Prisma.SortOrder
}

export type GeneralAvgOrderByAggregateInput = {
  log_freq?: Prisma.SortOrder
}

export type GeneralMaxOrderByAggregateInput = {
  key?: Prisma.SortOrder
  c_name?: Prisma.SortOrder
  c_logo?: Prisma.SortOrder
  license_key?: Prisma.SortOrder
  log_freq?: Prisma.SortOrder
}

export type GeneralMinOrderByAggregateInput = {
  key?: Prisma.SortOrder
  c_name?: Prisma.SortOrder
  c_logo?: Prisma.SortOrder
  license_key?: Prisma.SortOrder
  log_freq?: Prisma.SortOrder
}

export type GeneralSumOrderByAggregateInput = {
  log_freq?: Prisma.SortOrder
}



export type GeneralSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  key?: boolean
  c_name?: boolean
  c_logo?: boolean
  license_key?: boolean
  log_freq?: boolean
}, ExtArgs["result"]["general"]>

export type GeneralSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  key?: boolean
  c_name?: boolean
  c_logo?: boolean
  license_key?: boolean
  log_freq?: boolean
}, ExtArgs["result"]["general"]>

export type GeneralSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  key?: boolean
  c_name?: boolean
  c_logo?: boolean
  license_key?: boolean
  log_freq?: boolean
}, ExtArgs["result"]["general"]>

export type GeneralSelectScalar = {
  key?: boolean
  c_name?: boolean
  c_logo?: boolean
  license_key?: boolean
  log_freq?: boolean
}

export type GeneralOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"key" | "c_name" | "c_logo" | "license_key" | "log_freq", ExtArgs["result"]["general"]>

export type $GeneralPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "General"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    key: string
    c_name: string
    c_logo: string
    license_key: string
    log_freq: number
  }, ExtArgs["result"]["general"]>
  composites: {}
}

export type GeneralGetPayload<S extends boolean | null | undefined | GeneralDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$GeneralPayload, S>

export type GeneralCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<GeneralFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: GeneralCountAggregateInputType | true
  }

export interface GeneralDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['General'], meta: { name: 'General' } }
  /**
   * Find zero or one General that matches the filter.
   * @param {GeneralFindUniqueArgs} args - Arguments to find a General
   * @example
   * // Get one General
   * const general = await prisma.general.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends GeneralFindUniqueArgs>(args: Prisma.SelectSubset<T, GeneralFindUniqueArgs<ExtArgs>>): Prisma.Prisma__GeneralClient<runtime.Types.Result.GetResult<Prisma.$GeneralPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one General that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {GeneralFindUniqueOrThrowArgs} args - Arguments to find a General
   * @example
   * // Get one General
   * const general = await prisma.general.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends GeneralFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, GeneralFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__GeneralClient<runtime.Types.Result.GetResult<Prisma.$GeneralPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first General that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GeneralFindFirstArgs} args - Arguments to find a General
   * @example
   * // Get one General
   * const general = await prisma.general.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends GeneralFindFirstArgs>(args?: Prisma.SelectSubset<T, GeneralFindFirstArgs<ExtArgs>>): Prisma.Prisma__GeneralClient<runtime.Types.Result.GetResult<Prisma.$GeneralPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first General that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GeneralFindFirstOrThrowArgs} args - Arguments to find a General
   * @example
   * // Get one General
   * const general = await prisma.general.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends GeneralFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, GeneralFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__GeneralClient<runtime.Types.Result.GetResult<Prisma.$GeneralPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Generals that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GeneralFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Generals
   * const generals = await prisma.general.findMany()
   * 
   * // Get first 10 Generals
   * const generals = await prisma.general.findMany({ take: 10 })
   * 
   * // Only select the `key`
   * const generalWithKeyOnly = await prisma.general.findMany({ select: { key: true } })
   * 
   */
  findMany<T extends GeneralFindManyArgs>(args?: Prisma.SelectSubset<T, GeneralFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GeneralPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a General.
   * @param {GeneralCreateArgs} args - Arguments to create a General.
   * @example
   * // Create one General
   * const General = await prisma.general.create({
   *   data: {
   *     // ... data to create a General
   *   }
   * })
   * 
   */
  create<T extends GeneralCreateArgs>(args: Prisma.SelectSubset<T, GeneralCreateArgs<ExtArgs>>): Prisma.Prisma__GeneralClient<runtime.Types.Result.GetResult<Prisma.$GeneralPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Generals.
   * @param {GeneralCreateManyArgs} args - Arguments to create many Generals.
   * @example
   * // Create many Generals
   * const general = await prisma.general.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends GeneralCreateManyArgs>(args?: Prisma.SelectSubset<T, GeneralCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Generals and returns the data saved in the database.
   * @param {GeneralCreateManyAndReturnArgs} args - Arguments to create many Generals.
   * @example
   * // Create many Generals
   * const general = await prisma.general.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Generals and only return the `key`
   * const generalWithKeyOnly = await prisma.general.createManyAndReturn({
   *   select: { key: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends GeneralCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, GeneralCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GeneralPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a General.
   * @param {GeneralDeleteArgs} args - Arguments to delete one General.
   * @example
   * // Delete one General
   * const General = await prisma.general.delete({
   *   where: {
   *     // ... filter to delete one General
   *   }
   * })
   * 
   */
  delete<T extends GeneralDeleteArgs>(args: Prisma.SelectSubset<T, GeneralDeleteArgs<ExtArgs>>): Prisma.Prisma__GeneralClient<runtime.Types.Result.GetResult<Prisma.$GeneralPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one General.
   * @param {GeneralUpdateArgs} args - Arguments to update one General.
   * @example
   * // Update one General
   * const general = await prisma.general.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends GeneralUpdateArgs>(args: Prisma.SelectSubset<T, GeneralUpdateArgs<ExtArgs>>): Prisma.Prisma__GeneralClient<runtime.Types.Result.GetResult<Prisma.$GeneralPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Generals.
   * @param {GeneralDeleteManyArgs} args - Arguments to filter Generals to delete.
   * @example
   * // Delete a few Generals
   * const { count } = await prisma.general.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends GeneralDeleteManyArgs>(args?: Prisma.SelectSubset<T, GeneralDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Generals.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GeneralUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Generals
   * const general = await prisma.general.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends GeneralUpdateManyArgs>(args: Prisma.SelectSubset<T, GeneralUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Generals and returns the data updated in the database.
   * @param {GeneralUpdateManyAndReturnArgs} args - Arguments to update many Generals.
   * @example
   * // Update many Generals
   * const general = await prisma.general.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Generals and only return the `key`
   * const generalWithKeyOnly = await prisma.general.updateManyAndReturn({
   *   select: { key: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends GeneralUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, GeneralUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GeneralPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one General.
   * @param {GeneralUpsertArgs} args - Arguments to update or create a General.
   * @example
   * // Update or create a General
   * const general = await prisma.general.upsert({
   *   create: {
   *     // ... data to create a General
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the General we want to update
   *   }
   * })
   */
  upsert<T extends GeneralUpsertArgs>(args: Prisma.SelectSubset<T, GeneralUpsertArgs<ExtArgs>>): Prisma.Prisma__GeneralClient<runtime.Types.Result.GetResult<Prisma.$GeneralPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Generals.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GeneralCountArgs} args - Arguments to filter Generals to count.
   * @example
   * // Count the number of Generals
   * const count = await prisma.general.count({
   *   where: {
   *     // ... the filter for the Generals we want to count
   *   }
   * })
  **/
  count<T extends GeneralCountArgs>(
    args?: Prisma.Subset<T, GeneralCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], GeneralCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a General.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GeneralAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends GeneralAggregateArgs>(args: Prisma.Subset<T, GeneralAggregateArgs>): Prisma.PrismaPromise<GetGeneralAggregateType<T>>

  /**
   * Group by General.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GeneralGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends GeneralGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: GeneralGroupByArgs['orderBy'] }
      : { orderBy?: GeneralGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, GeneralGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetGeneralGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the General model
 */
readonly fields: GeneralFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for General.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__GeneralClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the General model
 */
export interface GeneralFieldRefs {
  readonly key: Prisma.FieldRef<"General", 'String'>
  readonly c_name: Prisma.FieldRef<"General", 'String'>
  readonly c_logo: Prisma.FieldRef<"General", 'String'>
  readonly license_key: Prisma.FieldRef<"General", 'String'>
  readonly log_freq: Prisma.FieldRef<"General", 'Int'>
}
    

// Custom InputTypes
/**
 * General findUnique
 */
export type GeneralFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the General
   */
  select?: Prisma.GeneralSelect<ExtArgs> | null
  /**
   * Omit specific fields from the General
   */
  omit?: Prisma.GeneralOmit<ExtArgs> | null
  /**
   * Filter, which General to fetch.
   */
  where: Prisma.GeneralWhereUniqueInput
}

/**
 * General findUniqueOrThrow
 */
export type GeneralFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the General
   */
  select?: Prisma.GeneralSelect<ExtArgs> | null
  /**
   * Omit specific fields from the General
   */
  omit?: Prisma.GeneralOmit<ExtArgs> | null
  /**
   * Filter, which General to fetch.
   */
  where: Prisma.GeneralWhereUniqueInput
}

/**
 * General findFirst
 */
export type GeneralFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the General
   */
  select?: Prisma.GeneralSelect<ExtArgs> | null
  /**
   * Omit specific fields from the General
   */
  omit?: Prisma.GeneralOmit<ExtArgs> | null
  /**
   * Filter, which General to fetch.
   */
  where?: Prisma.GeneralWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Generals to fetch.
   */
  orderBy?: Prisma.GeneralOrderByWithRelationInput | Prisma.GeneralOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Generals.
   */
  cursor?: Prisma.GeneralWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Generals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Generals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Generals.
   */
  distinct?: Prisma.GeneralScalarFieldEnum | Prisma.GeneralScalarFieldEnum[]
}

/**
 * General findFirstOrThrow
 */
export type GeneralFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the General
   */
  select?: Prisma.GeneralSelect<ExtArgs> | null
  /**
   * Omit specific fields from the General
   */
  omit?: Prisma.GeneralOmit<ExtArgs> | null
  /**
   * Filter, which General to fetch.
   */
  where?: Prisma.GeneralWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Generals to fetch.
   */
  orderBy?: Prisma.GeneralOrderByWithRelationInput | Prisma.GeneralOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Generals.
   */
  cursor?: Prisma.GeneralWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Generals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Generals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Generals.
   */
  distinct?: Prisma.GeneralScalarFieldEnum | Prisma.GeneralScalarFieldEnum[]
}

/**
 * General findMany
 */
export type GeneralFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the General
   */
  select?: Prisma.GeneralSelect<ExtArgs> | null
  /**
   * Omit specific fields from the General
   */
  omit?: Prisma.GeneralOmit<ExtArgs> | null
  /**
   * Filter, which Generals to fetch.
   */
  where?: Prisma.GeneralWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Generals to fetch.
   */
  orderBy?: Prisma.GeneralOrderByWithRelationInput | Prisma.GeneralOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Generals.
   */
  cursor?: Prisma.GeneralWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Generals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Generals.
   */
  skip?: number
  distinct?: Prisma.GeneralScalarFieldEnum | Prisma.GeneralScalarFieldEnum[]
}

/**
 * General create
 */
export type GeneralCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the General
   */
  select?: Prisma.GeneralSelect<ExtArgs> | null
  /**
   * Omit specific fields from the General
   */
  omit?: Prisma.GeneralOmit<ExtArgs> | null
  /**
   * The data needed to create a General.
   */
  data: Prisma.XOR<Prisma.GeneralCreateInput, Prisma.GeneralUncheckedCreateInput>
}

/**
 * General createMany
 */
export type GeneralCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Generals.
   */
  data: Prisma.GeneralCreateManyInput | Prisma.GeneralCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * General createManyAndReturn
 */
export type GeneralCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the General
   */
  select?: Prisma.GeneralSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the General
   */
  omit?: Prisma.GeneralOmit<ExtArgs> | null
  /**
   * The data used to create many Generals.
   */
  data: Prisma.GeneralCreateManyInput | Prisma.GeneralCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * General update
 */
export type GeneralUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the General
   */
  select?: Prisma.GeneralSelect<ExtArgs> | null
  /**
   * Omit specific fields from the General
   */
  omit?: Prisma.GeneralOmit<ExtArgs> | null
  /**
   * The data needed to update a General.
   */
  data: Prisma.XOR<Prisma.GeneralUpdateInput, Prisma.GeneralUncheckedUpdateInput>
  /**
   * Choose, which General to update.
   */
  where: Prisma.GeneralWhereUniqueInput
}

/**
 * General updateMany
 */
export type GeneralUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Generals.
   */
  data: Prisma.XOR<Prisma.GeneralUpdateManyMutationInput, Prisma.GeneralUncheckedUpdateManyInput>
  /**
   * Filter which Generals to update
   */
  where?: Prisma.GeneralWhereInput
  /**
   * Limit how many Generals to update.
   */
  limit?: number
}

/**
 * General updateManyAndReturn
 */
export type GeneralUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the General
   */
  select?: Prisma.GeneralSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the General
   */
  omit?: Prisma.GeneralOmit<ExtArgs> | null
  /**
   * The data used to update Generals.
   */
  data: Prisma.XOR<Prisma.GeneralUpdateManyMutationInput, Prisma.GeneralUncheckedUpdateManyInput>
  /**
   * Filter which Generals to update
   */
  where?: Prisma.GeneralWhereInput
  /**
   * Limit how many Generals to update.
   */
  limit?: number
}

/**
 * General upsert
 */
export type GeneralUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the General
   */
  select?: Prisma.GeneralSelect<ExtArgs> | null
  /**
   * Omit specific fields from the General
   */
  omit?: Prisma.GeneralOmit<ExtArgs> | null
  /**
   * The filter to search for the General to update in case it exists.
   */
  where: Prisma.GeneralWhereUniqueInput
  /**
   * In case the General found by the `where` argument doesn't exist, create a new General with this data.
   */
  create: Prisma.XOR<Prisma.GeneralCreateInput, Prisma.GeneralUncheckedCreateInput>
  /**
   * In case the General was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.GeneralUpdateInput, Prisma.GeneralUncheckedUpdateInput>
}

/**
 * General delete
 */
export type GeneralDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the General
   */
  select?: Prisma.GeneralSelect<ExtArgs> | null
  /**
   * Omit specific fields from the General
   */
  omit?: Prisma.GeneralOmit<ExtArgs> | null
  /**
   * Filter which General to delete.
   */
  where: Prisma.GeneralWhereUniqueInput
}

/**
 * General deleteMany
 */
export type GeneralDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Generals to delete
   */
  where?: Prisma.GeneralWhereInput
  /**
   * Limit how many Generals to delete.
   */
  limit?: number
}

/**
 * General without action
 */
export type GeneralDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the General
   */
  select?: Prisma.GeneralSelect<ExtArgs> | null
  /**
   * Omit specific fields from the General
   */
  omit?: Prisma.GeneralOmit<ExtArgs> | null
}
