
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `LogHistory` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model LogHistory
 * 
 */
export type LogHistoryModel = runtime.Types.Result.DefaultSelection<Prisma.$LogHistoryPayload>

export type AggregateLogHistory = {
  _count: LogHistoryCountAggregateOutputType | null
  _avg: LogHistoryAvgAggregateOutputType | null
  _sum: LogHistorySumAggregateOutputType | null
  _min: LogHistoryMinAggregateOutputType | null
  _max: LogHistoryMaxAggregateOutputType | null
}

export type LogHistoryAvgAggregateOutputType = {
  on_contact: number | null
  alarm_contact: number | null
  machine_id: number | null
}

export type LogHistorySumAggregateOutputType = {
  on_contact: number | null
  alarm_contact: number | null
  machine_id: number | null
}

export type LogHistoryMinAggregateOutputType = {
  id: string | null
  on_contact: number | null
  alarm_contact: number | null
  temperature: string | null
  kwh: string | null
  timestamp: Date | null
  machine_id: number | null
}

export type LogHistoryMaxAggregateOutputType = {
  id: string | null
  on_contact: number | null
  alarm_contact: number | null
  temperature: string | null
  kwh: string | null
  timestamp: Date | null
  machine_id: number | null
}

export type LogHistoryCountAggregateOutputType = {
  id: number
  on_contact: number
  alarm_contact: number
  temperature: number
  kwh: number
  timestamp: number
  machine_id: number
  _all: number
}


export type LogHistoryAvgAggregateInputType = {
  on_contact?: true
  alarm_contact?: true
  machine_id?: true
}

export type LogHistorySumAggregateInputType = {
  on_contact?: true
  alarm_contact?: true
  machine_id?: true
}

export type LogHistoryMinAggregateInputType = {
  id?: true
  on_contact?: true
  alarm_contact?: true
  temperature?: true
  kwh?: true
  timestamp?: true
  machine_id?: true
}

export type LogHistoryMaxAggregateInputType = {
  id?: true
  on_contact?: true
  alarm_contact?: true
  temperature?: true
  kwh?: true
  timestamp?: true
  machine_id?: true
}

export type LogHistoryCountAggregateInputType = {
  id?: true
  on_contact?: true
  alarm_contact?: true
  temperature?: true
  kwh?: true
  timestamp?: true
  machine_id?: true
  _all?: true
}

export type LogHistoryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LogHistory to aggregate.
   */
  where?: Prisma.LogHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LogHistories to fetch.
   */
  orderBy?: Prisma.LogHistoryOrderByWithRelationInput | Prisma.LogHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LogHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LogHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LogHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned LogHistories
  **/
  _count?: true | LogHistoryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: LogHistoryAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: LogHistorySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LogHistoryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LogHistoryMaxAggregateInputType
}

export type GetLogHistoryAggregateType<T extends LogHistoryAggregateArgs> = {
      [P in keyof T & keyof AggregateLogHistory]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLogHistory[P]>
    : Prisma.GetScalarType<T[P], AggregateLogHistory[P]>
}




export type LogHistoryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LogHistoryWhereInput
  orderBy?: Prisma.LogHistoryOrderByWithAggregationInput | Prisma.LogHistoryOrderByWithAggregationInput[]
  by: Prisma.LogHistoryScalarFieldEnum[] | Prisma.LogHistoryScalarFieldEnum
  having?: Prisma.LogHistoryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LogHistoryCountAggregateInputType | true
  _avg?: LogHistoryAvgAggregateInputType
  _sum?: LogHistorySumAggregateInputType
  _min?: LogHistoryMinAggregateInputType
  _max?: LogHistoryMaxAggregateInputType
}

export type LogHistoryGroupByOutputType = {
  id: string
  on_contact: number | null
  alarm_contact: number | null
  temperature: string | null
  kwh: string | null
  timestamp: Date
  machine_id: number
  _count: LogHistoryCountAggregateOutputType | null
  _avg: LogHistoryAvgAggregateOutputType | null
  _sum: LogHistorySumAggregateOutputType | null
  _min: LogHistoryMinAggregateOutputType | null
  _max: LogHistoryMaxAggregateOutputType | null
}

type GetLogHistoryGroupByPayload<T extends LogHistoryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LogHistoryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LogHistoryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LogHistoryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LogHistoryGroupByOutputType[P]>
      }
    >
  >



export type LogHistoryWhereInput = {
  AND?: Prisma.LogHistoryWhereInput | Prisma.LogHistoryWhereInput[]
  OR?: Prisma.LogHistoryWhereInput[]
  NOT?: Prisma.LogHistoryWhereInput | Prisma.LogHistoryWhereInput[]
  id?: Prisma.StringFilter<"LogHistory"> | string
  on_contact?: Prisma.IntNullableFilter<"LogHistory"> | number | null
  alarm_contact?: Prisma.IntNullableFilter<"LogHistory"> | number | null
  temperature?: Prisma.StringNullableFilter<"LogHistory"> | string | null
  kwh?: Prisma.StringNullableFilter<"LogHistory"> | string | null
  timestamp?: Prisma.DateTimeFilter<"LogHistory"> | Date | string
  machine_id?: Prisma.IntFilter<"LogHistory"> | number
  machine?: Prisma.XOR<Prisma.MachineScalarRelationFilter, Prisma.MachineWhereInput>
}

export type LogHistoryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  on_contact?: Prisma.SortOrderInput | Prisma.SortOrder
  alarm_contact?: Prisma.SortOrderInput | Prisma.SortOrder
  temperature?: Prisma.SortOrderInput | Prisma.SortOrder
  kwh?: Prisma.SortOrderInput | Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  machine_id?: Prisma.SortOrder
  machine?: Prisma.MachineOrderByWithRelationInput
}

export type LogHistoryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.LogHistoryWhereInput | Prisma.LogHistoryWhereInput[]
  OR?: Prisma.LogHistoryWhereInput[]
  NOT?: Prisma.LogHistoryWhereInput | Prisma.LogHistoryWhereInput[]
  on_contact?: Prisma.IntNullableFilter<"LogHistory"> | number | null
  alarm_contact?: Prisma.IntNullableFilter<"LogHistory"> | number | null
  temperature?: Prisma.StringNullableFilter<"LogHistory"> | string | null
  kwh?: Prisma.StringNullableFilter<"LogHistory"> | string | null
  timestamp?: Prisma.DateTimeFilter<"LogHistory"> | Date | string
  machine_id?: Prisma.IntFilter<"LogHistory"> | number
  machine?: Prisma.XOR<Prisma.MachineScalarRelationFilter, Prisma.MachineWhereInput>
}, "id">

export type LogHistoryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  on_contact?: Prisma.SortOrderInput | Prisma.SortOrder
  alarm_contact?: Prisma.SortOrderInput | Prisma.SortOrder
  temperature?: Prisma.SortOrderInput | Prisma.SortOrder
  kwh?: Prisma.SortOrderInput | Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  machine_id?: Prisma.SortOrder
  _count?: Prisma.LogHistoryCountOrderByAggregateInput
  _avg?: Prisma.LogHistoryAvgOrderByAggregateInput
  _max?: Prisma.LogHistoryMaxOrderByAggregateInput
  _min?: Prisma.LogHistoryMinOrderByAggregateInput
  _sum?: Prisma.LogHistorySumOrderByAggregateInput
}

export type LogHistoryScalarWhereWithAggregatesInput = {
  AND?: Prisma.LogHistoryScalarWhereWithAggregatesInput | Prisma.LogHistoryScalarWhereWithAggregatesInput[]
  OR?: Prisma.LogHistoryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LogHistoryScalarWhereWithAggregatesInput | Prisma.LogHistoryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"LogHistory"> | string
  on_contact?: Prisma.IntNullableWithAggregatesFilter<"LogHistory"> | number | null
  alarm_contact?: Prisma.IntNullableWithAggregatesFilter<"LogHistory"> | number | null
  temperature?: Prisma.StringNullableWithAggregatesFilter<"LogHistory"> | string | null
  kwh?: Prisma.StringNullableWithAggregatesFilter<"LogHistory"> | string | null
  timestamp?: Prisma.DateTimeWithAggregatesFilter<"LogHistory"> | Date | string
  machine_id?: Prisma.IntWithAggregatesFilter<"LogHistory"> | number
}

export type LogHistoryCreateInput = {
  id?: string
  on_contact?: number | null
  alarm_contact?: number | null
  temperature?: string | null
  kwh?: string | null
  timestamp: Date | string
  machine: Prisma.MachineCreateNestedOneWithoutLogsInput
}

export type LogHistoryUncheckedCreateInput = {
  id?: string
  on_contact?: number | null
  alarm_contact?: number | null
  temperature?: string | null
  kwh?: string | null
  timestamp: Date | string
  machine_id: number
}

export type LogHistoryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  on_contact?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  alarm_contact?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  temperature?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kwh?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  machine?: Prisma.MachineUpdateOneRequiredWithoutLogsNestedInput
}

export type LogHistoryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  on_contact?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  alarm_contact?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  temperature?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kwh?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  machine_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type LogHistoryCreateManyInput = {
  id?: string
  on_contact?: number | null
  alarm_contact?: number | null
  temperature?: string | null
  kwh?: string | null
  timestamp: Date | string
  machine_id: number
}

export type LogHistoryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  on_contact?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  alarm_contact?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  temperature?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kwh?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LogHistoryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  on_contact?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  alarm_contact?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  temperature?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kwh?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  machine_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type LogHistoryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  on_contact?: Prisma.SortOrder
  alarm_contact?: Prisma.SortOrder
  temperature?: Prisma.SortOrder
  kwh?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  machine_id?: Prisma.SortOrder
}

export type LogHistoryAvgOrderByAggregateInput = {
  on_contact?: Prisma.SortOrder
  alarm_contact?: Prisma.SortOrder
  machine_id?: Prisma.SortOrder
}

export type LogHistoryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  on_contact?: Prisma.SortOrder
  alarm_contact?: Prisma.SortOrder
  temperature?: Prisma.SortOrder
  kwh?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  machine_id?: Prisma.SortOrder
}

export type LogHistoryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  on_contact?: Prisma.SortOrder
  alarm_contact?: Prisma.SortOrder
  temperature?: Prisma.SortOrder
  kwh?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  machine_id?: Prisma.SortOrder
}

export type LogHistorySumOrderByAggregateInput = {
  on_contact?: Prisma.SortOrder
  alarm_contact?: Prisma.SortOrder
  machine_id?: Prisma.SortOrder
}

export type LogHistoryListRelationFilter = {
  every?: Prisma.LogHistoryWhereInput
  some?: Prisma.LogHistoryWhereInput
  none?: Prisma.LogHistoryWhereInput
}

export type LogHistoryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type LogHistoryCreateNestedManyWithoutMachineInput = {
  create?: Prisma.XOR<Prisma.LogHistoryCreateWithoutMachineInput, Prisma.LogHistoryUncheckedCreateWithoutMachineInput> | Prisma.LogHistoryCreateWithoutMachineInput[] | Prisma.LogHistoryUncheckedCreateWithoutMachineInput[]
  connectOrCreate?: Prisma.LogHistoryCreateOrConnectWithoutMachineInput | Prisma.LogHistoryCreateOrConnectWithoutMachineInput[]
  createMany?: Prisma.LogHistoryCreateManyMachineInputEnvelope
  connect?: Prisma.LogHistoryWhereUniqueInput | Prisma.LogHistoryWhereUniqueInput[]
}

export type LogHistoryUncheckedCreateNestedManyWithoutMachineInput = {
  create?: Prisma.XOR<Prisma.LogHistoryCreateWithoutMachineInput, Prisma.LogHistoryUncheckedCreateWithoutMachineInput> | Prisma.LogHistoryCreateWithoutMachineInput[] | Prisma.LogHistoryUncheckedCreateWithoutMachineInput[]
  connectOrCreate?: Prisma.LogHistoryCreateOrConnectWithoutMachineInput | Prisma.LogHistoryCreateOrConnectWithoutMachineInput[]
  createMany?: Prisma.LogHistoryCreateManyMachineInputEnvelope
  connect?: Prisma.LogHistoryWhereUniqueInput | Prisma.LogHistoryWhereUniqueInput[]
}

export type LogHistoryUpdateManyWithoutMachineNestedInput = {
  create?: Prisma.XOR<Prisma.LogHistoryCreateWithoutMachineInput, Prisma.LogHistoryUncheckedCreateWithoutMachineInput> | Prisma.LogHistoryCreateWithoutMachineInput[] | Prisma.LogHistoryUncheckedCreateWithoutMachineInput[]
  connectOrCreate?: Prisma.LogHistoryCreateOrConnectWithoutMachineInput | Prisma.LogHistoryCreateOrConnectWithoutMachineInput[]
  upsert?: Prisma.LogHistoryUpsertWithWhereUniqueWithoutMachineInput | Prisma.LogHistoryUpsertWithWhereUniqueWithoutMachineInput[]
  createMany?: Prisma.LogHistoryCreateManyMachineInputEnvelope
  set?: Prisma.LogHistoryWhereUniqueInput | Prisma.LogHistoryWhereUniqueInput[]
  disconnect?: Prisma.LogHistoryWhereUniqueInput | Prisma.LogHistoryWhereUniqueInput[]
  delete?: Prisma.LogHistoryWhereUniqueInput | Prisma.LogHistoryWhereUniqueInput[]
  connect?: Prisma.LogHistoryWhereUniqueInput | Prisma.LogHistoryWhereUniqueInput[]
  update?: Prisma.LogHistoryUpdateWithWhereUniqueWithoutMachineInput | Prisma.LogHistoryUpdateWithWhereUniqueWithoutMachineInput[]
  updateMany?: Prisma.LogHistoryUpdateManyWithWhereWithoutMachineInput | Prisma.LogHistoryUpdateManyWithWhereWithoutMachineInput[]
  deleteMany?: Prisma.LogHistoryScalarWhereInput | Prisma.LogHistoryScalarWhereInput[]
}

export type LogHistoryUncheckedUpdateManyWithoutMachineNestedInput = {
  create?: Prisma.XOR<Prisma.LogHistoryCreateWithoutMachineInput, Prisma.LogHistoryUncheckedCreateWithoutMachineInput> | Prisma.LogHistoryCreateWithoutMachineInput[] | Prisma.LogHistoryUncheckedCreateWithoutMachineInput[]
  connectOrCreate?: Prisma.LogHistoryCreateOrConnectWithoutMachineInput | Prisma.LogHistoryCreateOrConnectWithoutMachineInput[]
  upsert?: Prisma.LogHistoryUpsertWithWhereUniqueWithoutMachineInput | Prisma.LogHistoryUpsertWithWhereUniqueWithoutMachineInput[]
  createMany?: Prisma.LogHistoryCreateManyMachineInputEnvelope
  set?: Prisma.LogHistoryWhereUniqueInput | Prisma.LogHistoryWhereUniqueInput[]
  disconnect?: Prisma.LogHistoryWhereUniqueInput | Prisma.LogHistoryWhereUniqueInput[]
  delete?: Prisma.LogHistoryWhereUniqueInput | Prisma.LogHistoryWhereUniqueInput[]
  connect?: Prisma.LogHistoryWhereUniqueInput | Prisma.LogHistoryWhereUniqueInput[]
  update?: Prisma.LogHistoryUpdateWithWhereUniqueWithoutMachineInput | Prisma.LogHistoryUpdateWithWhereUniqueWithoutMachineInput[]
  updateMany?: Prisma.LogHistoryUpdateManyWithWhereWithoutMachineInput | Prisma.LogHistoryUpdateManyWithWhereWithoutMachineInput[]
  deleteMany?: Prisma.LogHistoryScalarWhereInput | Prisma.LogHistoryScalarWhereInput[]
}

export type LogHistoryCreateWithoutMachineInput = {
  id?: string
  on_contact?: number | null
  alarm_contact?: number | null
  temperature?: string | null
  kwh?: string | null
  timestamp: Date | string
}

export type LogHistoryUncheckedCreateWithoutMachineInput = {
  id?: string
  on_contact?: number | null
  alarm_contact?: number | null
  temperature?: string | null
  kwh?: string | null
  timestamp: Date | string
}

export type LogHistoryCreateOrConnectWithoutMachineInput = {
  where: Prisma.LogHistoryWhereUniqueInput
  create: Prisma.XOR<Prisma.LogHistoryCreateWithoutMachineInput, Prisma.LogHistoryUncheckedCreateWithoutMachineInput>
}

export type LogHistoryCreateManyMachineInputEnvelope = {
  data: Prisma.LogHistoryCreateManyMachineInput | Prisma.LogHistoryCreateManyMachineInput[]
  skipDuplicates?: boolean
}

export type LogHistoryUpsertWithWhereUniqueWithoutMachineInput = {
  where: Prisma.LogHistoryWhereUniqueInput
  update: Prisma.XOR<Prisma.LogHistoryUpdateWithoutMachineInput, Prisma.LogHistoryUncheckedUpdateWithoutMachineInput>
  create: Prisma.XOR<Prisma.LogHistoryCreateWithoutMachineInput, Prisma.LogHistoryUncheckedCreateWithoutMachineInput>
}

export type LogHistoryUpdateWithWhereUniqueWithoutMachineInput = {
  where: Prisma.LogHistoryWhereUniqueInput
  data: Prisma.XOR<Prisma.LogHistoryUpdateWithoutMachineInput, Prisma.LogHistoryUncheckedUpdateWithoutMachineInput>
}

export type LogHistoryUpdateManyWithWhereWithoutMachineInput = {
  where: Prisma.LogHistoryScalarWhereInput
  data: Prisma.XOR<Prisma.LogHistoryUpdateManyMutationInput, Prisma.LogHistoryUncheckedUpdateManyWithoutMachineInput>
}

export type LogHistoryScalarWhereInput = {
  AND?: Prisma.LogHistoryScalarWhereInput | Prisma.LogHistoryScalarWhereInput[]
  OR?: Prisma.LogHistoryScalarWhereInput[]
  NOT?: Prisma.LogHistoryScalarWhereInput | Prisma.LogHistoryScalarWhereInput[]
  id?: Prisma.StringFilter<"LogHistory"> | string
  on_contact?: Prisma.IntNullableFilter<"LogHistory"> | number | null
  alarm_contact?: Prisma.IntNullableFilter<"LogHistory"> | number | null
  temperature?: Prisma.StringNullableFilter<"LogHistory"> | string | null
  kwh?: Prisma.StringNullableFilter<"LogHistory"> | string | null
  timestamp?: Prisma.DateTimeFilter<"LogHistory"> | Date | string
  machine_id?: Prisma.IntFilter<"LogHistory"> | number
}

export type LogHistoryCreateManyMachineInput = {
  id?: string
  on_contact?: number | null
  alarm_contact?: number | null
  temperature?: string | null
  kwh?: string | null
  timestamp: Date | string
}

export type LogHistoryUpdateWithoutMachineInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  on_contact?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  alarm_contact?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  temperature?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kwh?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LogHistoryUncheckedUpdateWithoutMachineInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  on_contact?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  alarm_contact?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  temperature?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kwh?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LogHistoryUncheckedUpdateManyWithoutMachineInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  on_contact?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  alarm_contact?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  temperature?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kwh?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type LogHistorySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  on_contact?: boolean
  alarm_contact?: boolean
  temperature?: boolean
  kwh?: boolean
  timestamp?: boolean
  machine_id?: boolean
  machine?: boolean | Prisma.MachineDefaultArgs<ExtArgs>
}, ExtArgs["result"]["logHistory"]>

export type LogHistorySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  on_contact?: boolean
  alarm_contact?: boolean
  temperature?: boolean
  kwh?: boolean
  timestamp?: boolean
  machine_id?: boolean
  machine?: boolean | Prisma.MachineDefaultArgs<ExtArgs>
}, ExtArgs["result"]["logHistory"]>

export type LogHistorySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  on_contact?: boolean
  alarm_contact?: boolean
  temperature?: boolean
  kwh?: boolean
  timestamp?: boolean
  machine_id?: boolean
  machine?: boolean | Prisma.MachineDefaultArgs<ExtArgs>
}, ExtArgs["result"]["logHistory"]>

export type LogHistorySelectScalar = {
  id?: boolean
  on_contact?: boolean
  alarm_contact?: boolean
  temperature?: boolean
  kwh?: boolean
  timestamp?: boolean
  machine_id?: boolean
}

export type LogHistoryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "on_contact" | "alarm_contact" | "temperature" | "kwh" | "timestamp" | "machine_id", ExtArgs["result"]["logHistory"]>
export type LogHistoryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  machine?: boolean | Prisma.MachineDefaultArgs<ExtArgs>
}
export type LogHistoryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  machine?: boolean | Prisma.MachineDefaultArgs<ExtArgs>
}
export type LogHistoryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  machine?: boolean | Prisma.MachineDefaultArgs<ExtArgs>
}

export type $LogHistoryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "LogHistory"
  objects: {
    machine: Prisma.$MachinePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    on_contact: number | null
    alarm_contact: number | null
    temperature: string | null
    kwh: string | null
    timestamp: Date
    machine_id: number
  }, ExtArgs["result"]["logHistory"]>
  composites: {}
}

export type LogHistoryGetPayload<S extends boolean | null | undefined | LogHistoryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LogHistoryPayload, S>

export type LogHistoryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LogHistoryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LogHistoryCountAggregateInputType | true
  }

export interface LogHistoryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['LogHistory'], meta: { name: 'LogHistory' } }
  /**
   * Find zero or one LogHistory that matches the filter.
   * @param {LogHistoryFindUniqueArgs} args - Arguments to find a LogHistory
   * @example
   * // Get one LogHistory
   * const logHistory = await prisma.logHistory.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LogHistoryFindUniqueArgs>(args: Prisma.SelectSubset<T, LogHistoryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LogHistoryClient<runtime.Types.Result.GetResult<Prisma.$LogHistoryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one LogHistory that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LogHistoryFindUniqueOrThrowArgs} args - Arguments to find a LogHistory
   * @example
   * // Get one LogHistory
   * const logHistory = await prisma.logHistory.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LogHistoryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LogHistoryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LogHistoryClient<runtime.Types.Result.GetResult<Prisma.$LogHistoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LogHistory that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LogHistoryFindFirstArgs} args - Arguments to find a LogHistory
   * @example
   * // Get one LogHistory
   * const logHistory = await prisma.logHistory.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LogHistoryFindFirstArgs>(args?: Prisma.SelectSubset<T, LogHistoryFindFirstArgs<ExtArgs>>): Prisma.Prisma__LogHistoryClient<runtime.Types.Result.GetResult<Prisma.$LogHistoryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LogHistory that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LogHistoryFindFirstOrThrowArgs} args - Arguments to find a LogHistory
   * @example
   * // Get one LogHistory
   * const logHistory = await prisma.logHistory.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LogHistoryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LogHistoryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LogHistoryClient<runtime.Types.Result.GetResult<Prisma.$LogHistoryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more LogHistories that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LogHistoryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all LogHistories
   * const logHistories = await prisma.logHistory.findMany()
   * 
   * // Get first 10 LogHistories
   * const logHistories = await prisma.logHistory.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const logHistoryWithIdOnly = await prisma.logHistory.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LogHistoryFindManyArgs>(args?: Prisma.SelectSubset<T, LogHistoryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LogHistoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a LogHistory.
   * @param {LogHistoryCreateArgs} args - Arguments to create a LogHistory.
   * @example
   * // Create one LogHistory
   * const LogHistory = await prisma.logHistory.create({
   *   data: {
   *     // ... data to create a LogHistory
   *   }
   * })
   * 
   */
  create<T extends LogHistoryCreateArgs>(args: Prisma.SelectSubset<T, LogHistoryCreateArgs<ExtArgs>>): Prisma.Prisma__LogHistoryClient<runtime.Types.Result.GetResult<Prisma.$LogHistoryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many LogHistories.
   * @param {LogHistoryCreateManyArgs} args - Arguments to create many LogHistories.
   * @example
   * // Create many LogHistories
   * const logHistory = await prisma.logHistory.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LogHistoryCreateManyArgs>(args?: Prisma.SelectSubset<T, LogHistoryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many LogHistories and returns the data saved in the database.
   * @param {LogHistoryCreateManyAndReturnArgs} args - Arguments to create many LogHistories.
   * @example
   * // Create many LogHistories
   * const logHistory = await prisma.logHistory.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many LogHistories and only return the `id`
   * const logHistoryWithIdOnly = await prisma.logHistory.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LogHistoryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LogHistoryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LogHistoryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a LogHistory.
   * @param {LogHistoryDeleteArgs} args - Arguments to delete one LogHistory.
   * @example
   * // Delete one LogHistory
   * const LogHistory = await prisma.logHistory.delete({
   *   where: {
   *     // ... filter to delete one LogHistory
   *   }
   * })
   * 
   */
  delete<T extends LogHistoryDeleteArgs>(args: Prisma.SelectSubset<T, LogHistoryDeleteArgs<ExtArgs>>): Prisma.Prisma__LogHistoryClient<runtime.Types.Result.GetResult<Prisma.$LogHistoryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one LogHistory.
   * @param {LogHistoryUpdateArgs} args - Arguments to update one LogHistory.
   * @example
   * // Update one LogHistory
   * const logHistory = await prisma.logHistory.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LogHistoryUpdateArgs>(args: Prisma.SelectSubset<T, LogHistoryUpdateArgs<ExtArgs>>): Prisma.Prisma__LogHistoryClient<runtime.Types.Result.GetResult<Prisma.$LogHistoryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more LogHistories.
   * @param {LogHistoryDeleteManyArgs} args - Arguments to filter LogHistories to delete.
   * @example
   * // Delete a few LogHistories
   * const { count } = await prisma.logHistory.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LogHistoryDeleteManyArgs>(args?: Prisma.SelectSubset<T, LogHistoryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LogHistories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LogHistoryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many LogHistories
   * const logHistory = await prisma.logHistory.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LogHistoryUpdateManyArgs>(args: Prisma.SelectSubset<T, LogHistoryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LogHistories and returns the data updated in the database.
   * @param {LogHistoryUpdateManyAndReturnArgs} args - Arguments to update many LogHistories.
   * @example
   * // Update many LogHistories
   * const logHistory = await prisma.logHistory.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more LogHistories and only return the `id`
   * const logHistoryWithIdOnly = await prisma.logHistory.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LogHistoryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LogHistoryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LogHistoryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one LogHistory.
   * @param {LogHistoryUpsertArgs} args - Arguments to update or create a LogHistory.
   * @example
   * // Update or create a LogHistory
   * const logHistory = await prisma.logHistory.upsert({
   *   create: {
   *     // ... data to create a LogHistory
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the LogHistory we want to update
   *   }
   * })
   */
  upsert<T extends LogHistoryUpsertArgs>(args: Prisma.SelectSubset<T, LogHistoryUpsertArgs<ExtArgs>>): Prisma.Prisma__LogHistoryClient<runtime.Types.Result.GetResult<Prisma.$LogHistoryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of LogHistories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LogHistoryCountArgs} args - Arguments to filter LogHistories to count.
   * @example
   * // Count the number of LogHistories
   * const count = await prisma.logHistory.count({
   *   where: {
   *     // ... the filter for the LogHistories we want to count
   *   }
   * })
  **/
  count<T extends LogHistoryCountArgs>(
    args?: Prisma.Subset<T, LogHistoryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LogHistoryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a LogHistory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LogHistoryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LogHistoryAggregateArgs>(args: Prisma.Subset<T, LogHistoryAggregateArgs>): Prisma.PrismaPromise<GetLogHistoryAggregateType<T>>

  /**
   * Group by LogHistory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LogHistoryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LogHistoryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LogHistoryGroupByArgs['orderBy'] }
      : { orderBy?: LogHistoryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LogHistoryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLogHistoryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the LogHistory model
 */
readonly fields: LogHistoryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for LogHistory.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LogHistoryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  machine<T extends Prisma.MachineDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MachineDefaultArgs<ExtArgs>>): Prisma.Prisma__MachineClient<runtime.Types.Result.GetResult<Prisma.$MachinePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the LogHistory model
 */
export interface LogHistoryFieldRefs {
  readonly id: Prisma.FieldRef<"LogHistory", 'String'>
  readonly on_contact: Prisma.FieldRef<"LogHistory", 'Int'>
  readonly alarm_contact: Prisma.FieldRef<"LogHistory", 'Int'>
  readonly temperature: Prisma.FieldRef<"LogHistory", 'String'>
  readonly kwh: Prisma.FieldRef<"LogHistory", 'String'>
  readonly timestamp: Prisma.FieldRef<"LogHistory", 'DateTime'>
  readonly machine_id: Prisma.FieldRef<"LogHistory", 'Int'>
}
    

// Custom InputTypes
/**
 * LogHistory findUnique
 */
export type LogHistoryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogHistory
   */
  select?: Prisma.LogHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LogHistory
   */
  omit?: Prisma.LogHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogHistoryInclude<ExtArgs> | null
  /**
   * Filter, which LogHistory to fetch.
   */
  where: Prisma.LogHistoryWhereUniqueInput
}

/**
 * LogHistory findUniqueOrThrow
 */
export type LogHistoryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogHistory
   */
  select?: Prisma.LogHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LogHistory
   */
  omit?: Prisma.LogHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogHistoryInclude<ExtArgs> | null
  /**
   * Filter, which LogHistory to fetch.
   */
  where: Prisma.LogHistoryWhereUniqueInput
}

/**
 * LogHistory findFirst
 */
export type LogHistoryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogHistory
   */
  select?: Prisma.LogHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LogHistory
   */
  omit?: Prisma.LogHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogHistoryInclude<ExtArgs> | null
  /**
   * Filter, which LogHistory to fetch.
   */
  where?: Prisma.LogHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LogHistories to fetch.
   */
  orderBy?: Prisma.LogHistoryOrderByWithRelationInput | Prisma.LogHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LogHistories.
   */
  cursor?: Prisma.LogHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LogHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LogHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LogHistories.
   */
  distinct?: Prisma.LogHistoryScalarFieldEnum | Prisma.LogHistoryScalarFieldEnum[]
}

/**
 * LogHistory findFirstOrThrow
 */
export type LogHistoryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogHistory
   */
  select?: Prisma.LogHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LogHistory
   */
  omit?: Prisma.LogHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogHistoryInclude<ExtArgs> | null
  /**
   * Filter, which LogHistory to fetch.
   */
  where?: Prisma.LogHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LogHistories to fetch.
   */
  orderBy?: Prisma.LogHistoryOrderByWithRelationInput | Prisma.LogHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LogHistories.
   */
  cursor?: Prisma.LogHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LogHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LogHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LogHistories.
   */
  distinct?: Prisma.LogHistoryScalarFieldEnum | Prisma.LogHistoryScalarFieldEnum[]
}

/**
 * LogHistory findMany
 */
export type LogHistoryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogHistory
   */
  select?: Prisma.LogHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LogHistory
   */
  omit?: Prisma.LogHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogHistoryInclude<ExtArgs> | null
  /**
   * Filter, which LogHistories to fetch.
   */
  where?: Prisma.LogHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LogHistories to fetch.
   */
  orderBy?: Prisma.LogHistoryOrderByWithRelationInput | Prisma.LogHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing LogHistories.
   */
  cursor?: Prisma.LogHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LogHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LogHistories.
   */
  skip?: number
  distinct?: Prisma.LogHistoryScalarFieldEnum | Prisma.LogHistoryScalarFieldEnum[]
}

/**
 * LogHistory create
 */
export type LogHistoryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogHistory
   */
  select?: Prisma.LogHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LogHistory
   */
  omit?: Prisma.LogHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogHistoryInclude<ExtArgs> | null
  /**
   * The data needed to create a LogHistory.
   */
  data: Prisma.XOR<Prisma.LogHistoryCreateInput, Prisma.LogHistoryUncheckedCreateInput>
}

/**
 * LogHistory createMany
 */
export type LogHistoryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many LogHistories.
   */
  data: Prisma.LogHistoryCreateManyInput | Prisma.LogHistoryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * LogHistory createManyAndReturn
 */
export type LogHistoryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogHistory
   */
  select?: Prisma.LogHistorySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LogHistory
   */
  omit?: Prisma.LogHistoryOmit<ExtArgs> | null
  /**
   * The data used to create many LogHistories.
   */
  data: Prisma.LogHistoryCreateManyInput | Prisma.LogHistoryCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogHistoryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * LogHistory update
 */
export type LogHistoryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogHistory
   */
  select?: Prisma.LogHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LogHistory
   */
  omit?: Prisma.LogHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogHistoryInclude<ExtArgs> | null
  /**
   * The data needed to update a LogHistory.
   */
  data: Prisma.XOR<Prisma.LogHistoryUpdateInput, Prisma.LogHistoryUncheckedUpdateInput>
  /**
   * Choose, which LogHistory to update.
   */
  where: Prisma.LogHistoryWhereUniqueInput
}

/**
 * LogHistory updateMany
 */
export type LogHistoryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update LogHistories.
   */
  data: Prisma.XOR<Prisma.LogHistoryUpdateManyMutationInput, Prisma.LogHistoryUncheckedUpdateManyInput>
  /**
   * Filter which LogHistories to update
   */
  where?: Prisma.LogHistoryWhereInput
  /**
   * Limit how many LogHistories to update.
   */
  limit?: number
}

/**
 * LogHistory updateManyAndReturn
 */
export type LogHistoryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogHistory
   */
  select?: Prisma.LogHistorySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LogHistory
   */
  omit?: Prisma.LogHistoryOmit<ExtArgs> | null
  /**
   * The data used to update LogHistories.
   */
  data: Prisma.XOR<Prisma.LogHistoryUpdateManyMutationInput, Prisma.LogHistoryUncheckedUpdateManyInput>
  /**
   * Filter which LogHistories to update
   */
  where?: Prisma.LogHistoryWhereInput
  /**
   * Limit how many LogHistories to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogHistoryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * LogHistory upsert
 */
export type LogHistoryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogHistory
   */
  select?: Prisma.LogHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LogHistory
   */
  omit?: Prisma.LogHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogHistoryInclude<ExtArgs> | null
  /**
   * The filter to search for the LogHistory to update in case it exists.
   */
  where: Prisma.LogHistoryWhereUniqueInput
  /**
   * In case the LogHistory found by the `where` argument doesn't exist, create a new LogHistory with this data.
   */
  create: Prisma.XOR<Prisma.LogHistoryCreateInput, Prisma.LogHistoryUncheckedCreateInput>
  /**
   * In case the LogHistory was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LogHistoryUpdateInput, Prisma.LogHistoryUncheckedUpdateInput>
}

/**
 * LogHistory delete
 */
export type LogHistoryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogHistory
   */
  select?: Prisma.LogHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LogHistory
   */
  omit?: Prisma.LogHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogHistoryInclude<ExtArgs> | null
  /**
   * Filter which LogHistory to delete.
   */
  where: Prisma.LogHistoryWhereUniqueInput
}

/**
 * LogHistory deleteMany
 */
export type LogHistoryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LogHistories to delete
   */
  where?: Prisma.LogHistoryWhereInput
  /**
   * Limit how many LogHistories to delete.
   */
  limit?: number
}

/**
 * LogHistory without action
 */
export type LogHistoryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogHistory
   */
  select?: Prisma.LogHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LogHistory
   */
  omit?: Prisma.LogHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogHistoryInclude<ExtArgs> | null
}
