
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Mapping` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Mapping
 * 
 */
export type MappingModel = runtime.Types.Result.DefaultSelection<Prisma.$MappingPayload>

export type AggregateMapping = {
  _count: MappingCountAggregateOutputType | null
  _avg: MappingAvgAggregateOutputType | null
  _sum: MappingSumAggregateOutputType | null
  _min: MappingMinAggregateOutputType | null
  _max: MappingMaxAggregateOutputType | null
}

export type MappingAvgAggregateOutputType = {
  id: number | null
}

export type MappingSumAggregateOutputType = {
  id: number | null
}

export type MappingMinAggregateOutputType = {
  id: number | null
  type: string | null
}

export type MappingMaxAggregateOutputType = {
  id: number | null
  type: string | null
}

export type MappingCountAggregateOutputType = {
  id: number
  type: number
  params: number
  _all: number
}


export type MappingAvgAggregateInputType = {
  id?: true
}

export type MappingSumAggregateInputType = {
  id?: true
}

export type MappingMinAggregateInputType = {
  id?: true
  type?: true
}

export type MappingMaxAggregateInputType = {
  id?: true
  type?: true
}

export type MappingCountAggregateInputType = {
  id?: true
  type?: true
  params?: true
  _all?: true
}

export type MappingAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Mapping to aggregate.
   */
  where?: Prisma.MappingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Mappings to fetch.
   */
  orderBy?: Prisma.MappingOrderByWithRelationInput | Prisma.MappingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MappingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Mappings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Mappings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Mappings
  **/
  _count?: true | MappingCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MappingAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MappingSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MappingMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MappingMaxAggregateInputType
}

export type GetMappingAggregateType<T extends MappingAggregateArgs> = {
      [P in keyof T & keyof AggregateMapping]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMapping[P]>
    : Prisma.GetScalarType<T[P], AggregateMapping[P]>
}




export type MappingGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MappingWhereInput
  orderBy?: Prisma.MappingOrderByWithAggregationInput | Prisma.MappingOrderByWithAggregationInput[]
  by: Prisma.MappingScalarFieldEnum[] | Prisma.MappingScalarFieldEnum
  having?: Prisma.MappingScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MappingCountAggregateInputType | true
  _avg?: MappingAvgAggregateInputType
  _sum?: MappingSumAggregateInputType
  _min?: MappingMinAggregateInputType
  _max?: MappingMaxAggregateInputType
}

export type MappingGroupByOutputType = {
  id: number
  type: string
  params: runtime.JsonValue
  _count: MappingCountAggregateOutputType | null
  _avg: MappingAvgAggregateOutputType | null
  _sum: MappingSumAggregateOutputType | null
  _min: MappingMinAggregateOutputType | null
  _max: MappingMaxAggregateOutputType | null
}

type GetMappingGroupByPayload<T extends MappingGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MappingGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MappingGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MappingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MappingGroupByOutputType[P]>
      }
    >
  >



export type MappingWhereInput = {
  AND?: Prisma.MappingWhereInput | Prisma.MappingWhereInput[]
  OR?: Prisma.MappingWhereInput[]
  NOT?: Prisma.MappingWhereInput | Prisma.MappingWhereInput[]
  id?: Prisma.IntFilter<"Mapping"> | number
  type?: Prisma.StringFilter<"Mapping"> | string
  params?: Prisma.JsonFilter<"Mapping">
  power_meters?: Prisma.PowerMeterListRelationFilter
  temp_sensors?: Prisma.TemperatureSensorListRelationFilter
  on_contact_sensors?: Prisma.OnContactSensorListRelationFilter
  alarm_contact_sensors?: Prisma.AlarmContactSensorListRelationFilter
}

export type MappingOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  params?: Prisma.SortOrder
  power_meters?: Prisma.PowerMeterOrderByRelationAggregateInput
  temp_sensors?: Prisma.TemperatureSensorOrderByRelationAggregateInput
  on_contact_sensors?: Prisma.OnContactSensorOrderByRelationAggregateInput
  alarm_contact_sensors?: Prisma.AlarmContactSensorOrderByRelationAggregateInput
}

export type MappingWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.MappingWhereInput | Prisma.MappingWhereInput[]
  OR?: Prisma.MappingWhereInput[]
  NOT?: Prisma.MappingWhereInput | Prisma.MappingWhereInput[]
  type?: Prisma.StringFilter<"Mapping"> | string
  params?: Prisma.JsonFilter<"Mapping">
  power_meters?: Prisma.PowerMeterListRelationFilter
  temp_sensors?: Prisma.TemperatureSensorListRelationFilter
  on_contact_sensors?: Prisma.OnContactSensorListRelationFilter
  alarm_contact_sensors?: Prisma.AlarmContactSensorListRelationFilter
}, "id">

export type MappingOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  params?: Prisma.SortOrder
  _count?: Prisma.MappingCountOrderByAggregateInput
  _avg?: Prisma.MappingAvgOrderByAggregateInput
  _max?: Prisma.MappingMaxOrderByAggregateInput
  _min?: Prisma.MappingMinOrderByAggregateInput
  _sum?: Prisma.MappingSumOrderByAggregateInput
}

export type MappingScalarWhereWithAggregatesInput = {
  AND?: Prisma.MappingScalarWhereWithAggregatesInput | Prisma.MappingScalarWhereWithAggregatesInput[]
  OR?: Prisma.MappingScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MappingScalarWhereWithAggregatesInput | Prisma.MappingScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Mapping"> | number
  type?: Prisma.StringWithAggregatesFilter<"Mapping"> | string
  params?: Prisma.JsonWithAggregatesFilter<"Mapping">
}

export type MappingCreateInput = {
  type: string
  params: Prisma.JsonNullValueInput | runtime.InputJsonValue
  power_meters?: Prisma.PowerMeterCreateNestedManyWithoutMappingInput
  temp_sensors?: Prisma.TemperatureSensorCreateNestedManyWithoutMappingInput
  on_contact_sensors?: Prisma.OnContactSensorCreateNestedManyWithoutMappingInput
  alarm_contact_sensors?: Prisma.AlarmContactSensorCreateNestedManyWithoutMappingInput
}

export type MappingUncheckedCreateInput = {
  id?: number
  type: string
  params: Prisma.JsonNullValueInput | runtime.InputJsonValue
  power_meters?: Prisma.PowerMeterUncheckedCreateNestedManyWithoutMappingInput
  temp_sensors?: Prisma.TemperatureSensorUncheckedCreateNestedManyWithoutMappingInput
  on_contact_sensors?: Prisma.OnContactSensorUncheckedCreateNestedManyWithoutMappingInput
  alarm_contact_sensors?: Prisma.AlarmContactSensorUncheckedCreateNestedManyWithoutMappingInput
}

export type MappingUpdateInput = {
  type?: Prisma.StringFieldUpdateOperationsInput | string
  params?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  power_meters?: Prisma.PowerMeterUpdateManyWithoutMappingNestedInput
  temp_sensors?: Prisma.TemperatureSensorUpdateManyWithoutMappingNestedInput
  on_contact_sensors?: Prisma.OnContactSensorUpdateManyWithoutMappingNestedInput
  alarm_contact_sensors?: Prisma.AlarmContactSensorUpdateManyWithoutMappingNestedInput
}

export type MappingUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  params?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  power_meters?: Prisma.PowerMeterUncheckedUpdateManyWithoutMappingNestedInput
  temp_sensors?: Prisma.TemperatureSensorUncheckedUpdateManyWithoutMappingNestedInput
  on_contact_sensors?: Prisma.OnContactSensorUncheckedUpdateManyWithoutMappingNestedInput
  alarm_contact_sensors?: Prisma.AlarmContactSensorUncheckedUpdateManyWithoutMappingNestedInput
}

export type MappingCreateManyInput = {
  id?: number
  type: string
  params: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type MappingUpdateManyMutationInput = {
  type?: Prisma.StringFieldUpdateOperationsInput | string
  params?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type MappingUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  params?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type MappingScalarRelationFilter = {
  is?: Prisma.MappingWhereInput
  isNot?: Prisma.MappingWhereInput
}

export type MappingCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  params?: Prisma.SortOrder
}

export type MappingAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type MappingMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
}

export type MappingMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
}

export type MappingSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type MappingCreateNestedOneWithoutPower_metersInput = {
  create?: Prisma.XOR<Prisma.MappingCreateWithoutPower_metersInput, Prisma.MappingUncheckedCreateWithoutPower_metersInput>
  connectOrCreate?: Prisma.MappingCreateOrConnectWithoutPower_metersInput
  connect?: Prisma.MappingWhereUniqueInput
}

export type MappingUpdateOneRequiredWithoutPower_metersNestedInput = {
  create?: Prisma.XOR<Prisma.MappingCreateWithoutPower_metersInput, Prisma.MappingUncheckedCreateWithoutPower_metersInput>
  connectOrCreate?: Prisma.MappingCreateOrConnectWithoutPower_metersInput
  upsert?: Prisma.MappingUpsertWithoutPower_metersInput
  connect?: Prisma.MappingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MappingUpdateToOneWithWhereWithoutPower_metersInput, Prisma.MappingUpdateWithoutPower_metersInput>, Prisma.MappingUncheckedUpdateWithoutPower_metersInput>
}

export type MappingCreateNestedOneWithoutTemp_sensorsInput = {
  create?: Prisma.XOR<Prisma.MappingCreateWithoutTemp_sensorsInput, Prisma.MappingUncheckedCreateWithoutTemp_sensorsInput>
  connectOrCreate?: Prisma.MappingCreateOrConnectWithoutTemp_sensorsInput
  connect?: Prisma.MappingWhereUniqueInput
}

export type MappingUpdateOneRequiredWithoutTemp_sensorsNestedInput = {
  create?: Prisma.XOR<Prisma.MappingCreateWithoutTemp_sensorsInput, Prisma.MappingUncheckedCreateWithoutTemp_sensorsInput>
  connectOrCreate?: Prisma.MappingCreateOrConnectWithoutTemp_sensorsInput
  upsert?: Prisma.MappingUpsertWithoutTemp_sensorsInput
  connect?: Prisma.MappingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MappingUpdateToOneWithWhereWithoutTemp_sensorsInput, Prisma.MappingUpdateWithoutTemp_sensorsInput>, Prisma.MappingUncheckedUpdateWithoutTemp_sensorsInput>
}

export type MappingCreateNestedOneWithoutOn_contact_sensorsInput = {
  create?: Prisma.XOR<Prisma.MappingCreateWithoutOn_contact_sensorsInput, Prisma.MappingUncheckedCreateWithoutOn_contact_sensorsInput>
  connectOrCreate?: Prisma.MappingCreateOrConnectWithoutOn_contact_sensorsInput
  connect?: Prisma.MappingWhereUniqueInput
}

export type MappingUpdateOneRequiredWithoutOn_contact_sensorsNestedInput = {
  create?: Prisma.XOR<Prisma.MappingCreateWithoutOn_contact_sensorsInput, Prisma.MappingUncheckedCreateWithoutOn_contact_sensorsInput>
  connectOrCreate?: Prisma.MappingCreateOrConnectWithoutOn_contact_sensorsInput
  upsert?: Prisma.MappingUpsertWithoutOn_contact_sensorsInput
  connect?: Prisma.MappingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MappingUpdateToOneWithWhereWithoutOn_contact_sensorsInput, Prisma.MappingUpdateWithoutOn_contact_sensorsInput>, Prisma.MappingUncheckedUpdateWithoutOn_contact_sensorsInput>
}

export type MappingCreateNestedOneWithoutAlarm_contact_sensorsInput = {
  create?: Prisma.XOR<Prisma.MappingCreateWithoutAlarm_contact_sensorsInput, Prisma.MappingUncheckedCreateWithoutAlarm_contact_sensorsInput>
  connectOrCreate?: Prisma.MappingCreateOrConnectWithoutAlarm_contact_sensorsInput
  connect?: Prisma.MappingWhereUniqueInput
}

export type MappingUpdateOneRequiredWithoutAlarm_contact_sensorsNestedInput = {
  create?: Prisma.XOR<Prisma.MappingCreateWithoutAlarm_contact_sensorsInput, Prisma.MappingUncheckedCreateWithoutAlarm_contact_sensorsInput>
  connectOrCreate?: Prisma.MappingCreateOrConnectWithoutAlarm_contact_sensorsInput
  upsert?: Prisma.MappingUpsertWithoutAlarm_contact_sensorsInput
  connect?: Prisma.MappingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MappingUpdateToOneWithWhereWithoutAlarm_contact_sensorsInput, Prisma.MappingUpdateWithoutAlarm_contact_sensorsInput>, Prisma.MappingUncheckedUpdateWithoutAlarm_contact_sensorsInput>
}

export type MappingCreateWithoutPower_metersInput = {
  type: string
  params: Prisma.JsonNullValueInput | runtime.InputJsonValue
  temp_sensors?: Prisma.TemperatureSensorCreateNestedManyWithoutMappingInput
  on_contact_sensors?: Prisma.OnContactSensorCreateNestedManyWithoutMappingInput
  alarm_contact_sensors?: Prisma.AlarmContactSensorCreateNestedManyWithoutMappingInput
}

export type MappingUncheckedCreateWithoutPower_metersInput = {
  id?: number
  type: string
  params: Prisma.JsonNullValueInput | runtime.InputJsonValue
  temp_sensors?: Prisma.TemperatureSensorUncheckedCreateNestedManyWithoutMappingInput
  on_contact_sensors?: Prisma.OnContactSensorUncheckedCreateNestedManyWithoutMappingInput
  alarm_contact_sensors?: Prisma.AlarmContactSensorUncheckedCreateNestedManyWithoutMappingInput
}

export type MappingCreateOrConnectWithoutPower_metersInput = {
  where: Prisma.MappingWhereUniqueInput
  create: Prisma.XOR<Prisma.MappingCreateWithoutPower_metersInput, Prisma.MappingUncheckedCreateWithoutPower_metersInput>
}

export type MappingUpsertWithoutPower_metersInput = {
  update: Prisma.XOR<Prisma.MappingUpdateWithoutPower_metersInput, Prisma.MappingUncheckedUpdateWithoutPower_metersInput>
  create: Prisma.XOR<Prisma.MappingCreateWithoutPower_metersInput, Prisma.MappingUncheckedCreateWithoutPower_metersInput>
  where?: Prisma.MappingWhereInput
}

export type MappingUpdateToOneWithWhereWithoutPower_metersInput = {
  where?: Prisma.MappingWhereInput
  data: Prisma.XOR<Prisma.MappingUpdateWithoutPower_metersInput, Prisma.MappingUncheckedUpdateWithoutPower_metersInput>
}

export type MappingUpdateWithoutPower_metersInput = {
  type?: Prisma.StringFieldUpdateOperationsInput | string
  params?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  temp_sensors?: Prisma.TemperatureSensorUpdateManyWithoutMappingNestedInput
  on_contact_sensors?: Prisma.OnContactSensorUpdateManyWithoutMappingNestedInput
  alarm_contact_sensors?: Prisma.AlarmContactSensorUpdateManyWithoutMappingNestedInput
}

export type MappingUncheckedUpdateWithoutPower_metersInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  params?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  temp_sensors?: Prisma.TemperatureSensorUncheckedUpdateManyWithoutMappingNestedInput
  on_contact_sensors?: Prisma.OnContactSensorUncheckedUpdateManyWithoutMappingNestedInput
  alarm_contact_sensors?: Prisma.AlarmContactSensorUncheckedUpdateManyWithoutMappingNestedInput
}

export type MappingCreateWithoutTemp_sensorsInput = {
  type: string
  params: Prisma.JsonNullValueInput | runtime.InputJsonValue
  power_meters?: Prisma.PowerMeterCreateNestedManyWithoutMappingInput
  on_contact_sensors?: Prisma.OnContactSensorCreateNestedManyWithoutMappingInput
  alarm_contact_sensors?: Prisma.AlarmContactSensorCreateNestedManyWithoutMappingInput
}

export type MappingUncheckedCreateWithoutTemp_sensorsInput = {
  id?: number
  type: string
  params: Prisma.JsonNullValueInput | runtime.InputJsonValue
  power_meters?: Prisma.PowerMeterUncheckedCreateNestedManyWithoutMappingInput
  on_contact_sensors?: Prisma.OnContactSensorUncheckedCreateNestedManyWithoutMappingInput
  alarm_contact_sensors?: Prisma.AlarmContactSensorUncheckedCreateNestedManyWithoutMappingInput
}

export type MappingCreateOrConnectWithoutTemp_sensorsInput = {
  where: Prisma.MappingWhereUniqueInput
  create: Prisma.XOR<Prisma.MappingCreateWithoutTemp_sensorsInput, Prisma.MappingUncheckedCreateWithoutTemp_sensorsInput>
}

export type MappingUpsertWithoutTemp_sensorsInput = {
  update: Prisma.XOR<Prisma.MappingUpdateWithoutTemp_sensorsInput, Prisma.MappingUncheckedUpdateWithoutTemp_sensorsInput>
  create: Prisma.XOR<Prisma.MappingCreateWithoutTemp_sensorsInput, Prisma.MappingUncheckedCreateWithoutTemp_sensorsInput>
  where?: Prisma.MappingWhereInput
}

export type MappingUpdateToOneWithWhereWithoutTemp_sensorsInput = {
  where?: Prisma.MappingWhereInput
  data: Prisma.XOR<Prisma.MappingUpdateWithoutTemp_sensorsInput, Prisma.MappingUncheckedUpdateWithoutTemp_sensorsInput>
}

export type MappingUpdateWithoutTemp_sensorsInput = {
  type?: Prisma.StringFieldUpdateOperationsInput | string
  params?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  power_meters?: Prisma.PowerMeterUpdateManyWithoutMappingNestedInput
  on_contact_sensors?: Prisma.OnContactSensorUpdateManyWithoutMappingNestedInput
  alarm_contact_sensors?: Prisma.AlarmContactSensorUpdateManyWithoutMappingNestedInput
}

export type MappingUncheckedUpdateWithoutTemp_sensorsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  params?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  power_meters?: Prisma.PowerMeterUncheckedUpdateManyWithoutMappingNestedInput
  on_contact_sensors?: Prisma.OnContactSensorUncheckedUpdateManyWithoutMappingNestedInput
  alarm_contact_sensors?: Prisma.AlarmContactSensorUncheckedUpdateManyWithoutMappingNestedInput
}

export type MappingCreateWithoutOn_contact_sensorsInput = {
  type: string
  params: Prisma.JsonNullValueInput | runtime.InputJsonValue
  power_meters?: Prisma.PowerMeterCreateNestedManyWithoutMappingInput
  temp_sensors?: Prisma.TemperatureSensorCreateNestedManyWithoutMappingInput
  alarm_contact_sensors?: Prisma.AlarmContactSensorCreateNestedManyWithoutMappingInput
}

export type MappingUncheckedCreateWithoutOn_contact_sensorsInput = {
  id?: number
  type: string
  params: Prisma.JsonNullValueInput | runtime.InputJsonValue
  power_meters?: Prisma.PowerMeterUncheckedCreateNestedManyWithoutMappingInput
  temp_sensors?: Prisma.TemperatureSensorUncheckedCreateNestedManyWithoutMappingInput
  alarm_contact_sensors?: Prisma.AlarmContactSensorUncheckedCreateNestedManyWithoutMappingInput
}

export type MappingCreateOrConnectWithoutOn_contact_sensorsInput = {
  where: Prisma.MappingWhereUniqueInput
  create: Prisma.XOR<Prisma.MappingCreateWithoutOn_contact_sensorsInput, Prisma.MappingUncheckedCreateWithoutOn_contact_sensorsInput>
}

export type MappingUpsertWithoutOn_contact_sensorsInput = {
  update: Prisma.XOR<Prisma.MappingUpdateWithoutOn_contact_sensorsInput, Prisma.MappingUncheckedUpdateWithoutOn_contact_sensorsInput>
  create: Prisma.XOR<Prisma.MappingCreateWithoutOn_contact_sensorsInput, Prisma.MappingUncheckedCreateWithoutOn_contact_sensorsInput>
  where?: Prisma.MappingWhereInput
}

export type MappingUpdateToOneWithWhereWithoutOn_contact_sensorsInput = {
  where?: Prisma.MappingWhereInput
  data: Prisma.XOR<Prisma.MappingUpdateWithoutOn_contact_sensorsInput, Prisma.MappingUncheckedUpdateWithoutOn_contact_sensorsInput>
}

export type MappingUpdateWithoutOn_contact_sensorsInput = {
  type?: Prisma.StringFieldUpdateOperationsInput | string
  params?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  power_meters?: Prisma.PowerMeterUpdateManyWithoutMappingNestedInput
  temp_sensors?: Prisma.TemperatureSensorUpdateManyWithoutMappingNestedInput
  alarm_contact_sensors?: Prisma.AlarmContactSensorUpdateManyWithoutMappingNestedInput
}

export type MappingUncheckedUpdateWithoutOn_contact_sensorsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  params?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  power_meters?: Prisma.PowerMeterUncheckedUpdateManyWithoutMappingNestedInput
  temp_sensors?: Prisma.TemperatureSensorUncheckedUpdateManyWithoutMappingNestedInput
  alarm_contact_sensors?: Prisma.AlarmContactSensorUncheckedUpdateManyWithoutMappingNestedInput
}

export type MappingCreateWithoutAlarm_contact_sensorsInput = {
  type: string
  params: Prisma.JsonNullValueInput | runtime.InputJsonValue
  power_meters?: Prisma.PowerMeterCreateNestedManyWithoutMappingInput
  temp_sensors?: Prisma.TemperatureSensorCreateNestedManyWithoutMappingInput
  on_contact_sensors?: Prisma.OnContactSensorCreateNestedManyWithoutMappingInput
}

export type MappingUncheckedCreateWithoutAlarm_contact_sensorsInput = {
  id?: number
  type: string
  params: Prisma.JsonNullValueInput | runtime.InputJsonValue
  power_meters?: Prisma.PowerMeterUncheckedCreateNestedManyWithoutMappingInput
  temp_sensors?: Prisma.TemperatureSensorUncheckedCreateNestedManyWithoutMappingInput
  on_contact_sensors?: Prisma.OnContactSensorUncheckedCreateNestedManyWithoutMappingInput
}

export type MappingCreateOrConnectWithoutAlarm_contact_sensorsInput = {
  where: Prisma.MappingWhereUniqueInput
  create: Prisma.XOR<Prisma.MappingCreateWithoutAlarm_contact_sensorsInput, Prisma.MappingUncheckedCreateWithoutAlarm_contact_sensorsInput>
}

export type MappingUpsertWithoutAlarm_contact_sensorsInput = {
  update: Prisma.XOR<Prisma.MappingUpdateWithoutAlarm_contact_sensorsInput, Prisma.MappingUncheckedUpdateWithoutAlarm_contact_sensorsInput>
  create: Prisma.XOR<Prisma.MappingCreateWithoutAlarm_contact_sensorsInput, Prisma.MappingUncheckedCreateWithoutAlarm_contact_sensorsInput>
  where?: Prisma.MappingWhereInput
}

export type MappingUpdateToOneWithWhereWithoutAlarm_contact_sensorsInput = {
  where?: Prisma.MappingWhereInput
  data: Prisma.XOR<Prisma.MappingUpdateWithoutAlarm_contact_sensorsInput, Prisma.MappingUncheckedUpdateWithoutAlarm_contact_sensorsInput>
}

export type MappingUpdateWithoutAlarm_contact_sensorsInput = {
  type?: Prisma.StringFieldUpdateOperationsInput | string
  params?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  power_meters?: Prisma.PowerMeterUpdateManyWithoutMappingNestedInput
  temp_sensors?: Prisma.TemperatureSensorUpdateManyWithoutMappingNestedInput
  on_contact_sensors?: Prisma.OnContactSensorUpdateManyWithoutMappingNestedInput
}

export type MappingUncheckedUpdateWithoutAlarm_contact_sensorsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  params?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  power_meters?: Prisma.PowerMeterUncheckedUpdateManyWithoutMappingNestedInput
  temp_sensors?: Prisma.TemperatureSensorUncheckedUpdateManyWithoutMappingNestedInput
  on_contact_sensors?: Prisma.OnContactSensorUncheckedUpdateManyWithoutMappingNestedInput
}


/**
 * Count Type MappingCountOutputType
 */

export type MappingCountOutputType = {
  power_meters: number
  temp_sensors: number
  on_contact_sensors: number
  alarm_contact_sensors: number
}

export type MappingCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  power_meters?: boolean | MappingCountOutputTypeCountPower_metersArgs
  temp_sensors?: boolean | MappingCountOutputTypeCountTemp_sensorsArgs
  on_contact_sensors?: boolean | MappingCountOutputTypeCountOn_contact_sensorsArgs
  alarm_contact_sensors?: boolean | MappingCountOutputTypeCountAlarm_contact_sensorsArgs
}

/**
 * MappingCountOutputType without action
 */
export type MappingCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MappingCountOutputType
   */
  select?: Prisma.MappingCountOutputTypeSelect<ExtArgs> | null
}

/**
 * MappingCountOutputType without action
 */
export type MappingCountOutputTypeCountPower_metersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PowerMeterWhereInput
}

/**
 * MappingCountOutputType without action
 */
export type MappingCountOutputTypeCountTemp_sensorsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TemperatureSensorWhereInput
}

/**
 * MappingCountOutputType without action
 */
export type MappingCountOutputTypeCountOn_contact_sensorsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OnContactSensorWhereInput
}

/**
 * MappingCountOutputType without action
 */
export type MappingCountOutputTypeCountAlarm_contact_sensorsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AlarmContactSensorWhereInput
}


export type MappingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  params?: boolean
  power_meters?: boolean | Prisma.Mapping$power_metersArgs<ExtArgs>
  temp_sensors?: boolean | Prisma.Mapping$temp_sensorsArgs<ExtArgs>
  on_contact_sensors?: boolean | Prisma.Mapping$on_contact_sensorsArgs<ExtArgs>
  alarm_contact_sensors?: boolean | Prisma.Mapping$alarm_contact_sensorsArgs<ExtArgs>
  _count?: boolean | Prisma.MappingCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["mapping"]>

export type MappingSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  params?: boolean
}, ExtArgs["result"]["mapping"]>

export type MappingSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  params?: boolean
}, ExtArgs["result"]["mapping"]>

export type MappingSelectScalar = {
  id?: boolean
  type?: boolean
  params?: boolean
}

export type MappingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "type" | "params", ExtArgs["result"]["mapping"]>
export type MappingInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  power_meters?: boolean | Prisma.Mapping$power_metersArgs<ExtArgs>
  temp_sensors?: boolean | Prisma.Mapping$temp_sensorsArgs<ExtArgs>
  on_contact_sensors?: boolean | Prisma.Mapping$on_contact_sensorsArgs<ExtArgs>
  alarm_contact_sensors?: boolean | Prisma.Mapping$alarm_contact_sensorsArgs<ExtArgs>
  _count?: boolean | Prisma.MappingCountOutputTypeDefaultArgs<ExtArgs>
}
export type MappingIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type MappingIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $MappingPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Mapping"
  objects: {
    power_meters: Prisma.$PowerMeterPayload<ExtArgs>[]
    temp_sensors: Prisma.$TemperatureSensorPayload<ExtArgs>[]
    on_contact_sensors: Prisma.$OnContactSensorPayload<ExtArgs>[]
    alarm_contact_sensors: Prisma.$AlarmContactSensorPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    type: string
    params: runtime.JsonValue
  }, ExtArgs["result"]["mapping"]>
  composites: {}
}

export type MappingGetPayload<S extends boolean | null | undefined | MappingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MappingPayload, S>

export type MappingCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MappingFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MappingCountAggregateInputType | true
  }

export interface MappingDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Mapping'], meta: { name: 'Mapping' } }
  /**
   * Find zero or one Mapping that matches the filter.
   * @param {MappingFindUniqueArgs} args - Arguments to find a Mapping
   * @example
   * // Get one Mapping
   * const mapping = await prisma.mapping.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MappingFindUniqueArgs>(args: Prisma.SelectSubset<T, MappingFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MappingClient<runtime.Types.Result.GetResult<Prisma.$MappingPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Mapping that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MappingFindUniqueOrThrowArgs} args - Arguments to find a Mapping
   * @example
   * // Get one Mapping
   * const mapping = await prisma.mapping.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MappingFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MappingFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MappingClient<runtime.Types.Result.GetResult<Prisma.$MappingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Mapping that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MappingFindFirstArgs} args - Arguments to find a Mapping
   * @example
   * // Get one Mapping
   * const mapping = await prisma.mapping.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MappingFindFirstArgs>(args?: Prisma.SelectSubset<T, MappingFindFirstArgs<ExtArgs>>): Prisma.Prisma__MappingClient<runtime.Types.Result.GetResult<Prisma.$MappingPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Mapping that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MappingFindFirstOrThrowArgs} args - Arguments to find a Mapping
   * @example
   * // Get one Mapping
   * const mapping = await prisma.mapping.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MappingFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MappingFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MappingClient<runtime.Types.Result.GetResult<Prisma.$MappingPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Mappings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MappingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Mappings
   * const mappings = await prisma.mapping.findMany()
   * 
   * // Get first 10 Mappings
   * const mappings = await prisma.mapping.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const mappingWithIdOnly = await prisma.mapping.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MappingFindManyArgs>(args?: Prisma.SelectSubset<T, MappingFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MappingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Mapping.
   * @param {MappingCreateArgs} args - Arguments to create a Mapping.
   * @example
   * // Create one Mapping
   * const Mapping = await prisma.mapping.create({
   *   data: {
   *     // ... data to create a Mapping
   *   }
   * })
   * 
   */
  create<T extends MappingCreateArgs>(args: Prisma.SelectSubset<T, MappingCreateArgs<ExtArgs>>): Prisma.Prisma__MappingClient<runtime.Types.Result.GetResult<Prisma.$MappingPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Mappings.
   * @param {MappingCreateManyArgs} args - Arguments to create many Mappings.
   * @example
   * // Create many Mappings
   * const mapping = await prisma.mapping.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MappingCreateManyArgs>(args?: Prisma.SelectSubset<T, MappingCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Mappings and returns the data saved in the database.
   * @param {MappingCreateManyAndReturnArgs} args - Arguments to create many Mappings.
   * @example
   * // Create many Mappings
   * const mapping = await prisma.mapping.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Mappings and only return the `id`
   * const mappingWithIdOnly = await prisma.mapping.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MappingCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MappingCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MappingPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Mapping.
   * @param {MappingDeleteArgs} args - Arguments to delete one Mapping.
   * @example
   * // Delete one Mapping
   * const Mapping = await prisma.mapping.delete({
   *   where: {
   *     // ... filter to delete one Mapping
   *   }
   * })
   * 
   */
  delete<T extends MappingDeleteArgs>(args: Prisma.SelectSubset<T, MappingDeleteArgs<ExtArgs>>): Prisma.Prisma__MappingClient<runtime.Types.Result.GetResult<Prisma.$MappingPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Mapping.
   * @param {MappingUpdateArgs} args - Arguments to update one Mapping.
   * @example
   * // Update one Mapping
   * const mapping = await prisma.mapping.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MappingUpdateArgs>(args: Prisma.SelectSubset<T, MappingUpdateArgs<ExtArgs>>): Prisma.Prisma__MappingClient<runtime.Types.Result.GetResult<Prisma.$MappingPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Mappings.
   * @param {MappingDeleteManyArgs} args - Arguments to filter Mappings to delete.
   * @example
   * // Delete a few Mappings
   * const { count } = await prisma.mapping.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MappingDeleteManyArgs>(args?: Prisma.SelectSubset<T, MappingDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Mappings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MappingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Mappings
   * const mapping = await prisma.mapping.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MappingUpdateManyArgs>(args: Prisma.SelectSubset<T, MappingUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Mappings and returns the data updated in the database.
   * @param {MappingUpdateManyAndReturnArgs} args - Arguments to update many Mappings.
   * @example
   * // Update many Mappings
   * const mapping = await prisma.mapping.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Mappings and only return the `id`
   * const mappingWithIdOnly = await prisma.mapping.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MappingUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MappingUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MappingPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Mapping.
   * @param {MappingUpsertArgs} args - Arguments to update or create a Mapping.
   * @example
   * // Update or create a Mapping
   * const mapping = await prisma.mapping.upsert({
   *   create: {
   *     // ... data to create a Mapping
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Mapping we want to update
   *   }
   * })
   */
  upsert<T extends MappingUpsertArgs>(args: Prisma.SelectSubset<T, MappingUpsertArgs<ExtArgs>>): Prisma.Prisma__MappingClient<runtime.Types.Result.GetResult<Prisma.$MappingPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Mappings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MappingCountArgs} args - Arguments to filter Mappings to count.
   * @example
   * // Count the number of Mappings
   * const count = await prisma.mapping.count({
   *   where: {
   *     // ... the filter for the Mappings we want to count
   *   }
   * })
  **/
  count<T extends MappingCountArgs>(
    args?: Prisma.Subset<T, MappingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MappingCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Mapping.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MappingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MappingAggregateArgs>(args: Prisma.Subset<T, MappingAggregateArgs>): Prisma.PrismaPromise<GetMappingAggregateType<T>>

  /**
   * Group by Mapping.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MappingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MappingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MappingGroupByArgs['orderBy'] }
      : { orderBy?: MappingGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MappingGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMappingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Mapping model
 */
readonly fields: MappingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Mapping.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MappingClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  power_meters<T extends Prisma.Mapping$power_metersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Mapping$power_metersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PowerMeterPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  temp_sensors<T extends Prisma.Mapping$temp_sensorsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Mapping$temp_sensorsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TemperatureSensorPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  on_contact_sensors<T extends Prisma.Mapping$on_contact_sensorsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Mapping$on_contact_sensorsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OnContactSensorPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  alarm_contact_sensors<T extends Prisma.Mapping$alarm_contact_sensorsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Mapping$alarm_contact_sensorsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AlarmContactSensorPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Mapping model
 */
export interface MappingFieldRefs {
  readonly id: Prisma.FieldRef<"Mapping", 'Int'>
  readonly type: Prisma.FieldRef<"Mapping", 'String'>
  readonly params: Prisma.FieldRef<"Mapping", 'Json'>
}
    

// Custom InputTypes
/**
 * Mapping findUnique
 */
export type MappingFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mapping
   */
  select?: Prisma.MappingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mapping
   */
  omit?: Prisma.MappingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MappingInclude<ExtArgs> | null
  /**
   * Filter, which Mapping to fetch.
   */
  where: Prisma.MappingWhereUniqueInput
}

/**
 * Mapping findUniqueOrThrow
 */
export type MappingFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mapping
   */
  select?: Prisma.MappingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mapping
   */
  omit?: Prisma.MappingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MappingInclude<ExtArgs> | null
  /**
   * Filter, which Mapping to fetch.
   */
  where: Prisma.MappingWhereUniqueInput
}

/**
 * Mapping findFirst
 */
export type MappingFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mapping
   */
  select?: Prisma.MappingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mapping
   */
  omit?: Prisma.MappingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MappingInclude<ExtArgs> | null
  /**
   * Filter, which Mapping to fetch.
   */
  where?: Prisma.MappingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Mappings to fetch.
   */
  orderBy?: Prisma.MappingOrderByWithRelationInput | Prisma.MappingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Mappings.
   */
  cursor?: Prisma.MappingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Mappings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Mappings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Mappings.
   */
  distinct?: Prisma.MappingScalarFieldEnum | Prisma.MappingScalarFieldEnum[]
}

/**
 * Mapping findFirstOrThrow
 */
export type MappingFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mapping
   */
  select?: Prisma.MappingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mapping
   */
  omit?: Prisma.MappingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MappingInclude<ExtArgs> | null
  /**
   * Filter, which Mapping to fetch.
   */
  where?: Prisma.MappingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Mappings to fetch.
   */
  orderBy?: Prisma.MappingOrderByWithRelationInput | Prisma.MappingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Mappings.
   */
  cursor?: Prisma.MappingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Mappings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Mappings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Mappings.
   */
  distinct?: Prisma.MappingScalarFieldEnum | Prisma.MappingScalarFieldEnum[]
}

/**
 * Mapping findMany
 */
export type MappingFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mapping
   */
  select?: Prisma.MappingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mapping
   */
  omit?: Prisma.MappingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MappingInclude<ExtArgs> | null
  /**
   * Filter, which Mappings to fetch.
   */
  where?: Prisma.MappingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Mappings to fetch.
   */
  orderBy?: Prisma.MappingOrderByWithRelationInput | Prisma.MappingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Mappings.
   */
  cursor?: Prisma.MappingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Mappings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Mappings.
   */
  skip?: number
  distinct?: Prisma.MappingScalarFieldEnum | Prisma.MappingScalarFieldEnum[]
}

/**
 * Mapping create
 */
export type MappingCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mapping
   */
  select?: Prisma.MappingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mapping
   */
  omit?: Prisma.MappingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MappingInclude<ExtArgs> | null
  /**
   * The data needed to create a Mapping.
   */
  data: Prisma.XOR<Prisma.MappingCreateInput, Prisma.MappingUncheckedCreateInput>
}

/**
 * Mapping createMany
 */
export type MappingCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Mappings.
   */
  data: Prisma.MappingCreateManyInput | Prisma.MappingCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Mapping createManyAndReturn
 */
export type MappingCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mapping
   */
  select?: Prisma.MappingSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Mapping
   */
  omit?: Prisma.MappingOmit<ExtArgs> | null
  /**
   * The data used to create many Mappings.
   */
  data: Prisma.MappingCreateManyInput | Prisma.MappingCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Mapping update
 */
export type MappingUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mapping
   */
  select?: Prisma.MappingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mapping
   */
  omit?: Prisma.MappingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MappingInclude<ExtArgs> | null
  /**
   * The data needed to update a Mapping.
   */
  data: Prisma.XOR<Prisma.MappingUpdateInput, Prisma.MappingUncheckedUpdateInput>
  /**
   * Choose, which Mapping to update.
   */
  where: Prisma.MappingWhereUniqueInput
}

/**
 * Mapping updateMany
 */
export type MappingUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Mappings.
   */
  data: Prisma.XOR<Prisma.MappingUpdateManyMutationInput, Prisma.MappingUncheckedUpdateManyInput>
  /**
   * Filter which Mappings to update
   */
  where?: Prisma.MappingWhereInput
  /**
   * Limit how many Mappings to update.
   */
  limit?: number
}

/**
 * Mapping updateManyAndReturn
 */
export type MappingUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mapping
   */
  select?: Prisma.MappingSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Mapping
   */
  omit?: Prisma.MappingOmit<ExtArgs> | null
  /**
   * The data used to update Mappings.
   */
  data: Prisma.XOR<Prisma.MappingUpdateManyMutationInput, Prisma.MappingUncheckedUpdateManyInput>
  /**
   * Filter which Mappings to update
   */
  where?: Prisma.MappingWhereInput
  /**
   * Limit how many Mappings to update.
   */
  limit?: number
}

/**
 * Mapping upsert
 */
export type MappingUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mapping
   */
  select?: Prisma.MappingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mapping
   */
  omit?: Prisma.MappingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MappingInclude<ExtArgs> | null
  /**
   * The filter to search for the Mapping to update in case it exists.
   */
  where: Prisma.MappingWhereUniqueInput
  /**
   * In case the Mapping found by the `where` argument doesn't exist, create a new Mapping with this data.
   */
  create: Prisma.XOR<Prisma.MappingCreateInput, Prisma.MappingUncheckedCreateInput>
  /**
   * In case the Mapping was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MappingUpdateInput, Prisma.MappingUncheckedUpdateInput>
}

/**
 * Mapping delete
 */
export type MappingDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mapping
   */
  select?: Prisma.MappingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mapping
   */
  omit?: Prisma.MappingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MappingInclude<ExtArgs> | null
  /**
   * Filter which Mapping to delete.
   */
  where: Prisma.MappingWhereUniqueInput
}

/**
 * Mapping deleteMany
 */
export type MappingDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Mappings to delete
   */
  where?: Prisma.MappingWhereInput
  /**
   * Limit how many Mappings to delete.
   */
  limit?: number
}

/**
 * Mapping.power_meters
 */
export type Mapping$power_metersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PowerMeter
   */
  select?: Prisma.PowerMeterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PowerMeter
   */
  omit?: Prisma.PowerMeterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PowerMeterInclude<ExtArgs> | null
  where?: Prisma.PowerMeterWhereInput
  orderBy?: Prisma.PowerMeterOrderByWithRelationInput | Prisma.PowerMeterOrderByWithRelationInput[]
  cursor?: Prisma.PowerMeterWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PowerMeterScalarFieldEnum | Prisma.PowerMeterScalarFieldEnum[]
}

/**
 * Mapping.temp_sensors
 */
export type Mapping$temp_sensorsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TemperatureSensor
   */
  select?: Prisma.TemperatureSensorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TemperatureSensor
   */
  omit?: Prisma.TemperatureSensorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TemperatureSensorInclude<ExtArgs> | null
  where?: Prisma.TemperatureSensorWhereInput
  orderBy?: Prisma.TemperatureSensorOrderByWithRelationInput | Prisma.TemperatureSensorOrderByWithRelationInput[]
  cursor?: Prisma.TemperatureSensorWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TemperatureSensorScalarFieldEnum | Prisma.TemperatureSensorScalarFieldEnum[]
}

/**
 * Mapping.on_contact_sensors
 */
export type Mapping$on_contact_sensorsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OnContactSensor
   */
  select?: Prisma.OnContactSensorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OnContactSensor
   */
  omit?: Prisma.OnContactSensorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OnContactSensorInclude<ExtArgs> | null
  where?: Prisma.OnContactSensorWhereInput
  orderBy?: Prisma.OnContactSensorOrderByWithRelationInput | Prisma.OnContactSensorOrderByWithRelationInput[]
  cursor?: Prisma.OnContactSensorWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OnContactSensorScalarFieldEnum | Prisma.OnContactSensorScalarFieldEnum[]
}

/**
 * Mapping.alarm_contact_sensors
 */
export type Mapping$alarm_contact_sensorsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AlarmContactSensor
   */
  select?: Prisma.AlarmContactSensorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AlarmContactSensor
   */
  omit?: Prisma.AlarmContactSensorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AlarmContactSensorInclude<ExtArgs> | null
  where?: Prisma.AlarmContactSensorWhereInput
  orderBy?: Prisma.AlarmContactSensorOrderByWithRelationInput | Prisma.AlarmContactSensorOrderByWithRelationInput[]
  cursor?: Prisma.AlarmContactSensorWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AlarmContactSensorScalarFieldEnum | Prisma.AlarmContactSensorScalarFieldEnum[]
}

/**
 * Mapping without action
 */
export type MappingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mapping
   */
  select?: Prisma.MappingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mapping
   */
  omit?: Prisma.MappingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MappingInclude<ExtArgs> | null
}
