
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `McRunHour` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model McRunHour
 * 
 */
export type McRunHourModel = runtime.Types.Result.DefaultSelection<Prisma.$McRunHourPayload>

export type AggregateMcRunHour = {
  _count: McRunHourCountAggregateOutputType | null
  _avg: McRunHourAvgAggregateOutputType | null
  _sum: McRunHourSumAggregateOutputType | null
  _min: McRunHourMinAggregateOutputType | null
  _max: McRunHourMaxAggregateOutputType | null
}

export type McRunHourAvgAggregateOutputType = {
  machine_id: number | null
}

export type McRunHourSumAggregateOutputType = {
  machine_id: number | null
}

export type McRunHourMinAggregateOutputType = {
  id: string | null
  date: Date | null
  machine_id: number | null
  mc_run_h: string | null
  mc_run_kwh: string | null
  heat_up_h: string | null
  heat_up_kwh: string | null
  iddle_h: string | null
  iddle_kwh: string | null
  mc_production_h: string | null
  mc_production_kwh: string | null
  is_one_block: boolean | null
}

export type McRunHourMaxAggregateOutputType = {
  id: string | null
  date: Date | null
  machine_id: number | null
  mc_run_h: string | null
  mc_run_kwh: string | null
  heat_up_h: string | null
  heat_up_kwh: string | null
  iddle_h: string | null
  iddle_kwh: string | null
  mc_production_h: string | null
  mc_production_kwh: string | null
  is_one_block: boolean | null
}

export type McRunHourCountAggregateOutputType = {
  id: number
  date: number
  machine_id: number
  mc_run_h: number
  mc_run_kwh: number
  heat_up_h: number
  heat_up_kwh: number
  iddle_h: number
  iddle_kwh: number
  mc_production_h: number
  mc_production_kwh: number
  is_one_block: number
  _all: number
}


export type McRunHourAvgAggregateInputType = {
  machine_id?: true
}

export type McRunHourSumAggregateInputType = {
  machine_id?: true
}

export type McRunHourMinAggregateInputType = {
  id?: true
  date?: true
  machine_id?: true
  mc_run_h?: true
  mc_run_kwh?: true
  heat_up_h?: true
  heat_up_kwh?: true
  iddle_h?: true
  iddle_kwh?: true
  mc_production_h?: true
  mc_production_kwh?: true
  is_one_block?: true
}

export type McRunHourMaxAggregateInputType = {
  id?: true
  date?: true
  machine_id?: true
  mc_run_h?: true
  mc_run_kwh?: true
  heat_up_h?: true
  heat_up_kwh?: true
  iddle_h?: true
  iddle_kwh?: true
  mc_production_h?: true
  mc_production_kwh?: true
  is_one_block?: true
}

export type McRunHourCountAggregateInputType = {
  id?: true
  date?: true
  machine_id?: true
  mc_run_h?: true
  mc_run_kwh?: true
  heat_up_h?: true
  heat_up_kwh?: true
  iddle_h?: true
  iddle_kwh?: true
  mc_production_h?: true
  mc_production_kwh?: true
  is_one_block?: true
  _all?: true
}

export type McRunHourAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which McRunHour to aggregate.
   */
  where?: Prisma.McRunHourWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of McRunHours to fetch.
   */
  orderBy?: Prisma.McRunHourOrderByWithRelationInput | Prisma.McRunHourOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.McRunHourWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` McRunHours from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` McRunHours.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned McRunHours
  **/
  _count?: true | McRunHourCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: McRunHourAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: McRunHourSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: McRunHourMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: McRunHourMaxAggregateInputType
}

export type GetMcRunHourAggregateType<T extends McRunHourAggregateArgs> = {
      [P in keyof T & keyof AggregateMcRunHour]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMcRunHour[P]>
    : Prisma.GetScalarType<T[P], AggregateMcRunHour[P]>
}




export type McRunHourGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.McRunHourWhereInput
  orderBy?: Prisma.McRunHourOrderByWithAggregationInput | Prisma.McRunHourOrderByWithAggregationInput[]
  by: Prisma.McRunHourScalarFieldEnum[] | Prisma.McRunHourScalarFieldEnum
  having?: Prisma.McRunHourScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: McRunHourCountAggregateInputType | true
  _avg?: McRunHourAvgAggregateInputType
  _sum?: McRunHourSumAggregateInputType
  _min?: McRunHourMinAggregateInputType
  _max?: McRunHourMaxAggregateInputType
}

export type McRunHourGroupByOutputType = {
  id: string
  date: Date
  machine_id: number
  mc_run_h: string
  mc_run_kwh: string
  heat_up_h: string
  heat_up_kwh: string
  iddle_h: string
  iddle_kwh: string
  mc_production_h: string
  mc_production_kwh: string
  is_one_block: boolean
  _count: McRunHourCountAggregateOutputType | null
  _avg: McRunHourAvgAggregateOutputType | null
  _sum: McRunHourSumAggregateOutputType | null
  _min: McRunHourMinAggregateOutputType | null
  _max: McRunHourMaxAggregateOutputType | null
}

type GetMcRunHourGroupByPayload<T extends McRunHourGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<McRunHourGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof McRunHourGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], McRunHourGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], McRunHourGroupByOutputType[P]>
      }
    >
  >



export type McRunHourWhereInput = {
  AND?: Prisma.McRunHourWhereInput | Prisma.McRunHourWhereInput[]
  OR?: Prisma.McRunHourWhereInput[]
  NOT?: Prisma.McRunHourWhereInput | Prisma.McRunHourWhereInput[]
  id?: Prisma.StringFilter<"McRunHour"> | string
  date?: Prisma.DateTimeFilter<"McRunHour"> | Date | string
  machine_id?: Prisma.IntFilter<"McRunHour"> | number
  mc_run_h?: Prisma.StringFilter<"McRunHour"> | string
  mc_run_kwh?: Prisma.StringFilter<"McRunHour"> | string
  heat_up_h?: Prisma.StringFilter<"McRunHour"> | string
  heat_up_kwh?: Prisma.StringFilter<"McRunHour"> | string
  iddle_h?: Prisma.StringFilter<"McRunHour"> | string
  iddle_kwh?: Prisma.StringFilter<"McRunHour"> | string
  mc_production_h?: Prisma.StringFilter<"McRunHour"> | string
  mc_production_kwh?: Prisma.StringFilter<"McRunHour"> | string
  is_one_block?: Prisma.BoolFilter<"McRunHour"> | boolean
  machine?: Prisma.XOR<Prisma.MachineScalarRelationFilter, Prisma.MachineWhereInput>
}

export type McRunHourOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  machine_id?: Prisma.SortOrder
  mc_run_h?: Prisma.SortOrder
  mc_run_kwh?: Prisma.SortOrder
  heat_up_h?: Prisma.SortOrder
  heat_up_kwh?: Prisma.SortOrder
  iddle_h?: Prisma.SortOrder
  iddle_kwh?: Prisma.SortOrder
  mc_production_h?: Prisma.SortOrder
  mc_production_kwh?: Prisma.SortOrder
  is_one_block?: Prisma.SortOrder
  machine?: Prisma.MachineOrderByWithRelationInput
}

export type McRunHourWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.McRunHourWhereInput | Prisma.McRunHourWhereInput[]
  OR?: Prisma.McRunHourWhereInput[]
  NOT?: Prisma.McRunHourWhereInput | Prisma.McRunHourWhereInput[]
  date?: Prisma.DateTimeFilter<"McRunHour"> | Date | string
  machine_id?: Prisma.IntFilter<"McRunHour"> | number
  mc_run_h?: Prisma.StringFilter<"McRunHour"> | string
  mc_run_kwh?: Prisma.StringFilter<"McRunHour"> | string
  heat_up_h?: Prisma.StringFilter<"McRunHour"> | string
  heat_up_kwh?: Prisma.StringFilter<"McRunHour"> | string
  iddle_h?: Prisma.StringFilter<"McRunHour"> | string
  iddle_kwh?: Prisma.StringFilter<"McRunHour"> | string
  mc_production_h?: Prisma.StringFilter<"McRunHour"> | string
  mc_production_kwh?: Prisma.StringFilter<"McRunHour"> | string
  is_one_block?: Prisma.BoolFilter<"McRunHour"> | boolean
  machine?: Prisma.XOR<Prisma.MachineScalarRelationFilter, Prisma.MachineWhereInput>
}, "id">

export type McRunHourOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  machine_id?: Prisma.SortOrder
  mc_run_h?: Prisma.SortOrder
  mc_run_kwh?: Prisma.SortOrder
  heat_up_h?: Prisma.SortOrder
  heat_up_kwh?: Prisma.SortOrder
  iddle_h?: Prisma.SortOrder
  iddle_kwh?: Prisma.SortOrder
  mc_production_h?: Prisma.SortOrder
  mc_production_kwh?: Prisma.SortOrder
  is_one_block?: Prisma.SortOrder
  _count?: Prisma.McRunHourCountOrderByAggregateInput
  _avg?: Prisma.McRunHourAvgOrderByAggregateInput
  _max?: Prisma.McRunHourMaxOrderByAggregateInput
  _min?: Prisma.McRunHourMinOrderByAggregateInput
  _sum?: Prisma.McRunHourSumOrderByAggregateInput
}

export type McRunHourScalarWhereWithAggregatesInput = {
  AND?: Prisma.McRunHourScalarWhereWithAggregatesInput | Prisma.McRunHourScalarWhereWithAggregatesInput[]
  OR?: Prisma.McRunHourScalarWhereWithAggregatesInput[]
  NOT?: Prisma.McRunHourScalarWhereWithAggregatesInput | Prisma.McRunHourScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"McRunHour"> | string
  date?: Prisma.DateTimeWithAggregatesFilter<"McRunHour"> | Date | string
  machine_id?: Prisma.IntWithAggregatesFilter<"McRunHour"> | number
  mc_run_h?: Prisma.StringWithAggregatesFilter<"McRunHour"> | string
  mc_run_kwh?: Prisma.StringWithAggregatesFilter<"McRunHour"> | string
  heat_up_h?: Prisma.StringWithAggregatesFilter<"McRunHour"> | string
  heat_up_kwh?: Prisma.StringWithAggregatesFilter<"McRunHour"> | string
  iddle_h?: Prisma.StringWithAggregatesFilter<"McRunHour"> | string
  iddle_kwh?: Prisma.StringWithAggregatesFilter<"McRunHour"> | string
  mc_production_h?: Prisma.StringWithAggregatesFilter<"McRunHour"> | string
  mc_production_kwh?: Prisma.StringWithAggregatesFilter<"McRunHour"> | string
  is_one_block?: Prisma.BoolWithAggregatesFilter<"McRunHour"> | boolean
}

export type McRunHourCreateInput = {
  id?: string
  date: Date | string
  mc_run_h: string
  mc_run_kwh: string
  heat_up_h: string
  heat_up_kwh: string
  iddle_h: string
  iddle_kwh: string
  mc_production_h: string
  mc_production_kwh: string
  is_one_block: boolean
  machine: Prisma.MachineCreateNestedOneWithoutRun_hoursInput
}

export type McRunHourUncheckedCreateInput = {
  id?: string
  date: Date | string
  machine_id: number
  mc_run_h: string
  mc_run_kwh: string
  heat_up_h: string
  heat_up_kwh: string
  iddle_h: string
  iddle_kwh: string
  mc_production_h: string
  mc_production_kwh: string
  is_one_block: boolean
}

export type McRunHourUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mc_run_h?: Prisma.StringFieldUpdateOperationsInput | string
  mc_run_kwh?: Prisma.StringFieldUpdateOperationsInput | string
  heat_up_h?: Prisma.StringFieldUpdateOperationsInput | string
  heat_up_kwh?: Prisma.StringFieldUpdateOperationsInput | string
  iddle_h?: Prisma.StringFieldUpdateOperationsInput | string
  iddle_kwh?: Prisma.StringFieldUpdateOperationsInput | string
  mc_production_h?: Prisma.StringFieldUpdateOperationsInput | string
  mc_production_kwh?: Prisma.StringFieldUpdateOperationsInput | string
  is_one_block?: Prisma.BoolFieldUpdateOperationsInput | boolean
  machine?: Prisma.MachineUpdateOneRequiredWithoutRun_hoursNestedInput
}

export type McRunHourUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  machine_id?: Prisma.IntFieldUpdateOperationsInput | number
  mc_run_h?: Prisma.StringFieldUpdateOperationsInput | string
  mc_run_kwh?: Prisma.StringFieldUpdateOperationsInput | string
  heat_up_h?: Prisma.StringFieldUpdateOperationsInput | string
  heat_up_kwh?: Prisma.StringFieldUpdateOperationsInput | string
  iddle_h?: Prisma.StringFieldUpdateOperationsInput | string
  iddle_kwh?: Prisma.StringFieldUpdateOperationsInput | string
  mc_production_h?: Prisma.StringFieldUpdateOperationsInput | string
  mc_production_kwh?: Prisma.StringFieldUpdateOperationsInput | string
  is_one_block?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type McRunHourCreateManyInput = {
  id?: string
  date: Date | string
  machine_id: number
  mc_run_h: string
  mc_run_kwh: string
  heat_up_h: string
  heat_up_kwh: string
  iddle_h: string
  iddle_kwh: string
  mc_production_h: string
  mc_production_kwh: string
  is_one_block: boolean
}

export type McRunHourUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mc_run_h?: Prisma.StringFieldUpdateOperationsInput | string
  mc_run_kwh?: Prisma.StringFieldUpdateOperationsInput | string
  heat_up_h?: Prisma.StringFieldUpdateOperationsInput | string
  heat_up_kwh?: Prisma.StringFieldUpdateOperationsInput | string
  iddle_h?: Prisma.StringFieldUpdateOperationsInput | string
  iddle_kwh?: Prisma.StringFieldUpdateOperationsInput | string
  mc_production_h?: Prisma.StringFieldUpdateOperationsInput | string
  mc_production_kwh?: Prisma.StringFieldUpdateOperationsInput | string
  is_one_block?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type McRunHourUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  machine_id?: Prisma.IntFieldUpdateOperationsInput | number
  mc_run_h?: Prisma.StringFieldUpdateOperationsInput | string
  mc_run_kwh?: Prisma.StringFieldUpdateOperationsInput | string
  heat_up_h?: Prisma.StringFieldUpdateOperationsInput | string
  heat_up_kwh?: Prisma.StringFieldUpdateOperationsInput | string
  iddle_h?: Prisma.StringFieldUpdateOperationsInput | string
  iddle_kwh?: Prisma.StringFieldUpdateOperationsInput | string
  mc_production_h?: Prisma.StringFieldUpdateOperationsInput | string
  mc_production_kwh?: Prisma.StringFieldUpdateOperationsInput | string
  is_one_block?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type McRunHourListRelationFilter = {
  every?: Prisma.McRunHourWhereInput
  some?: Prisma.McRunHourWhereInput
  none?: Prisma.McRunHourWhereInput
}

export type McRunHourOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type McRunHourCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  machine_id?: Prisma.SortOrder
  mc_run_h?: Prisma.SortOrder
  mc_run_kwh?: Prisma.SortOrder
  heat_up_h?: Prisma.SortOrder
  heat_up_kwh?: Prisma.SortOrder
  iddle_h?: Prisma.SortOrder
  iddle_kwh?: Prisma.SortOrder
  mc_production_h?: Prisma.SortOrder
  mc_production_kwh?: Prisma.SortOrder
  is_one_block?: Prisma.SortOrder
}

export type McRunHourAvgOrderByAggregateInput = {
  machine_id?: Prisma.SortOrder
}

export type McRunHourMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  machine_id?: Prisma.SortOrder
  mc_run_h?: Prisma.SortOrder
  mc_run_kwh?: Prisma.SortOrder
  heat_up_h?: Prisma.SortOrder
  heat_up_kwh?: Prisma.SortOrder
  iddle_h?: Prisma.SortOrder
  iddle_kwh?: Prisma.SortOrder
  mc_production_h?: Prisma.SortOrder
  mc_production_kwh?: Prisma.SortOrder
  is_one_block?: Prisma.SortOrder
}

export type McRunHourMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  machine_id?: Prisma.SortOrder
  mc_run_h?: Prisma.SortOrder
  mc_run_kwh?: Prisma.SortOrder
  heat_up_h?: Prisma.SortOrder
  heat_up_kwh?: Prisma.SortOrder
  iddle_h?: Prisma.SortOrder
  iddle_kwh?: Prisma.SortOrder
  mc_production_h?: Prisma.SortOrder
  mc_production_kwh?: Prisma.SortOrder
  is_one_block?: Prisma.SortOrder
}

export type McRunHourSumOrderByAggregateInput = {
  machine_id?: Prisma.SortOrder
}

export type McRunHourCreateNestedManyWithoutMachineInput = {
  create?: Prisma.XOR<Prisma.McRunHourCreateWithoutMachineInput, Prisma.McRunHourUncheckedCreateWithoutMachineInput> | Prisma.McRunHourCreateWithoutMachineInput[] | Prisma.McRunHourUncheckedCreateWithoutMachineInput[]
  connectOrCreate?: Prisma.McRunHourCreateOrConnectWithoutMachineInput | Prisma.McRunHourCreateOrConnectWithoutMachineInput[]
  createMany?: Prisma.McRunHourCreateManyMachineInputEnvelope
  connect?: Prisma.McRunHourWhereUniqueInput | Prisma.McRunHourWhereUniqueInput[]
}

export type McRunHourUncheckedCreateNestedManyWithoutMachineInput = {
  create?: Prisma.XOR<Prisma.McRunHourCreateWithoutMachineInput, Prisma.McRunHourUncheckedCreateWithoutMachineInput> | Prisma.McRunHourCreateWithoutMachineInput[] | Prisma.McRunHourUncheckedCreateWithoutMachineInput[]
  connectOrCreate?: Prisma.McRunHourCreateOrConnectWithoutMachineInput | Prisma.McRunHourCreateOrConnectWithoutMachineInput[]
  createMany?: Prisma.McRunHourCreateManyMachineInputEnvelope
  connect?: Prisma.McRunHourWhereUniqueInput | Prisma.McRunHourWhereUniqueInput[]
}

export type McRunHourUpdateManyWithoutMachineNestedInput = {
  create?: Prisma.XOR<Prisma.McRunHourCreateWithoutMachineInput, Prisma.McRunHourUncheckedCreateWithoutMachineInput> | Prisma.McRunHourCreateWithoutMachineInput[] | Prisma.McRunHourUncheckedCreateWithoutMachineInput[]
  connectOrCreate?: Prisma.McRunHourCreateOrConnectWithoutMachineInput | Prisma.McRunHourCreateOrConnectWithoutMachineInput[]
  upsert?: Prisma.McRunHourUpsertWithWhereUniqueWithoutMachineInput | Prisma.McRunHourUpsertWithWhereUniqueWithoutMachineInput[]
  createMany?: Prisma.McRunHourCreateManyMachineInputEnvelope
  set?: Prisma.McRunHourWhereUniqueInput | Prisma.McRunHourWhereUniqueInput[]
  disconnect?: Prisma.McRunHourWhereUniqueInput | Prisma.McRunHourWhereUniqueInput[]
  delete?: Prisma.McRunHourWhereUniqueInput | Prisma.McRunHourWhereUniqueInput[]
  connect?: Prisma.McRunHourWhereUniqueInput | Prisma.McRunHourWhereUniqueInput[]
  update?: Prisma.McRunHourUpdateWithWhereUniqueWithoutMachineInput | Prisma.McRunHourUpdateWithWhereUniqueWithoutMachineInput[]
  updateMany?: Prisma.McRunHourUpdateManyWithWhereWithoutMachineInput | Prisma.McRunHourUpdateManyWithWhereWithoutMachineInput[]
  deleteMany?: Prisma.McRunHourScalarWhereInput | Prisma.McRunHourScalarWhereInput[]
}

export type McRunHourUncheckedUpdateManyWithoutMachineNestedInput = {
  create?: Prisma.XOR<Prisma.McRunHourCreateWithoutMachineInput, Prisma.McRunHourUncheckedCreateWithoutMachineInput> | Prisma.McRunHourCreateWithoutMachineInput[] | Prisma.McRunHourUncheckedCreateWithoutMachineInput[]
  connectOrCreate?: Prisma.McRunHourCreateOrConnectWithoutMachineInput | Prisma.McRunHourCreateOrConnectWithoutMachineInput[]
  upsert?: Prisma.McRunHourUpsertWithWhereUniqueWithoutMachineInput | Prisma.McRunHourUpsertWithWhereUniqueWithoutMachineInput[]
  createMany?: Prisma.McRunHourCreateManyMachineInputEnvelope
  set?: Prisma.McRunHourWhereUniqueInput | Prisma.McRunHourWhereUniqueInput[]
  disconnect?: Prisma.McRunHourWhereUniqueInput | Prisma.McRunHourWhereUniqueInput[]
  delete?: Prisma.McRunHourWhereUniqueInput | Prisma.McRunHourWhereUniqueInput[]
  connect?: Prisma.McRunHourWhereUniqueInput | Prisma.McRunHourWhereUniqueInput[]
  update?: Prisma.McRunHourUpdateWithWhereUniqueWithoutMachineInput | Prisma.McRunHourUpdateWithWhereUniqueWithoutMachineInput[]
  updateMany?: Prisma.McRunHourUpdateManyWithWhereWithoutMachineInput | Prisma.McRunHourUpdateManyWithWhereWithoutMachineInput[]
  deleteMany?: Prisma.McRunHourScalarWhereInput | Prisma.McRunHourScalarWhereInput[]
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type McRunHourCreateWithoutMachineInput = {
  id?: string
  date: Date | string
  mc_run_h: string
  mc_run_kwh: string
  heat_up_h: string
  heat_up_kwh: string
  iddle_h: string
  iddle_kwh: string
  mc_production_h: string
  mc_production_kwh: string
  is_one_block: boolean
}

export type McRunHourUncheckedCreateWithoutMachineInput = {
  id?: string
  date: Date | string
  mc_run_h: string
  mc_run_kwh: string
  heat_up_h: string
  heat_up_kwh: string
  iddle_h: string
  iddle_kwh: string
  mc_production_h: string
  mc_production_kwh: string
  is_one_block: boolean
}

export type McRunHourCreateOrConnectWithoutMachineInput = {
  where: Prisma.McRunHourWhereUniqueInput
  create: Prisma.XOR<Prisma.McRunHourCreateWithoutMachineInput, Prisma.McRunHourUncheckedCreateWithoutMachineInput>
}

export type McRunHourCreateManyMachineInputEnvelope = {
  data: Prisma.McRunHourCreateManyMachineInput | Prisma.McRunHourCreateManyMachineInput[]
  skipDuplicates?: boolean
}

export type McRunHourUpsertWithWhereUniqueWithoutMachineInput = {
  where: Prisma.McRunHourWhereUniqueInput
  update: Prisma.XOR<Prisma.McRunHourUpdateWithoutMachineInput, Prisma.McRunHourUncheckedUpdateWithoutMachineInput>
  create: Prisma.XOR<Prisma.McRunHourCreateWithoutMachineInput, Prisma.McRunHourUncheckedCreateWithoutMachineInput>
}

export type McRunHourUpdateWithWhereUniqueWithoutMachineInput = {
  where: Prisma.McRunHourWhereUniqueInput
  data: Prisma.XOR<Prisma.McRunHourUpdateWithoutMachineInput, Prisma.McRunHourUncheckedUpdateWithoutMachineInput>
}

export type McRunHourUpdateManyWithWhereWithoutMachineInput = {
  where: Prisma.McRunHourScalarWhereInput
  data: Prisma.XOR<Prisma.McRunHourUpdateManyMutationInput, Prisma.McRunHourUncheckedUpdateManyWithoutMachineInput>
}

export type McRunHourScalarWhereInput = {
  AND?: Prisma.McRunHourScalarWhereInput | Prisma.McRunHourScalarWhereInput[]
  OR?: Prisma.McRunHourScalarWhereInput[]
  NOT?: Prisma.McRunHourScalarWhereInput | Prisma.McRunHourScalarWhereInput[]
  id?: Prisma.StringFilter<"McRunHour"> | string
  date?: Prisma.DateTimeFilter<"McRunHour"> | Date | string
  machine_id?: Prisma.IntFilter<"McRunHour"> | number
  mc_run_h?: Prisma.StringFilter<"McRunHour"> | string
  mc_run_kwh?: Prisma.StringFilter<"McRunHour"> | string
  heat_up_h?: Prisma.StringFilter<"McRunHour"> | string
  heat_up_kwh?: Prisma.StringFilter<"McRunHour"> | string
  iddle_h?: Prisma.StringFilter<"McRunHour"> | string
  iddle_kwh?: Prisma.StringFilter<"McRunHour"> | string
  mc_production_h?: Prisma.StringFilter<"McRunHour"> | string
  mc_production_kwh?: Prisma.StringFilter<"McRunHour"> | string
  is_one_block?: Prisma.BoolFilter<"McRunHour"> | boolean
}

export type McRunHourCreateManyMachineInput = {
  id?: string
  date: Date | string
  mc_run_h: string
  mc_run_kwh: string
  heat_up_h: string
  heat_up_kwh: string
  iddle_h: string
  iddle_kwh: string
  mc_production_h: string
  mc_production_kwh: string
  is_one_block: boolean
}

export type McRunHourUpdateWithoutMachineInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mc_run_h?: Prisma.StringFieldUpdateOperationsInput | string
  mc_run_kwh?: Prisma.StringFieldUpdateOperationsInput | string
  heat_up_h?: Prisma.StringFieldUpdateOperationsInput | string
  heat_up_kwh?: Prisma.StringFieldUpdateOperationsInput | string
  iddle_h?: Prisma.StringFieldUpdateOperationsInput | string
  iddle_kwh?: Prisma.StringFieldUpdateOperationsInput | string
  mc_production_h?: Prisma.StringFieldUpdateOperationsInput | string
  mc_production_kwh?: Prisma.StringFieldUpdateOperationsInput | string
  is_one_block?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type McRunHourUncheckedUpdateWithoutMachineInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mc_run_h?: Prisma.StringFieldUpdateOperationsInput | string
  mc_run_kwh?: Prisma.StringFieldUpdateOperationsInput | string
  heat_up_h?: Prisma.StringFieldUpdateOperationsInput | string
  heat_up_kwh?: Prisma.StringFieldUpdateOperationsInput | string
  iddle_h?: Prisma.StringFieldUpdateOperationsInput | string
  iddle_kwh?: Prisma.StringFieldUpdateOperationsInput | string
  mc_production_h?: Prisma.StringFieldUpdateOperationsInput | string
  mc_production_kwh?: Prisma.StringFieldUpdateOperationsInput | string
  is_one_block?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type McRunHourUncheckedUpdateManyWithoutMachineInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mc_run_h?: Prisma.StringFieldUpdateOperationsInput | string
  mc_run_kwh?: Prisma.StringFieldUpdateOperationsInput | string
  heat_up_h?: Prisma.StringFieldUpdateOperationsInput | string
  heat_up_kwh?: Prisma.StringFieldUpdateOperationsInput | string
  iddle_h?: Prisma.StringFieldUpdateOperationsInput | string
  iddle_kwh?: Prisma.StringFieldUpdateOperationsInput | string
  mc_production_h?: Prisma.StringFieldUpdateOperationsInput | string
  mc_production_kwh?: Prisma.StringFieldUpdateOperationsInput | string
  is_one_block?: Prisma.BoolFieldUpdateOperationsInput | boolean
}



export type McRunHourSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  machine_id?: boolean
  mc_run_h?: boolean
  mc_run_kwh?: boolean
  heat_up_h?: boolean
  heat_up_kwh?: boolean
  iddle_h?: boolean
  iddle_kwh?: boolean
  mc_production_h?: boolean
  mc_production_kwh?: boolean
  is_one_block?: boolean
  machine?: boolean | Prisma.MachineDefaultArgs<ExtArgs>
}, ExtArgs["result"]["mcRunHour"]>

export type McRunHourSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  machine_id?: boolean
  mc_run_h?: boolean
  mc_run_kwh?: boolean
  heat_up_h?: boolean
  heat_up_kwh?: boolean
  iddle_h?: boolean
  iddle_kwh?: boolean
  mc_production_h?: boolean
  mc_production_kwh?: boolean
  is_one_block?: boolean
  machine?: boolean | Prisma.MachineDefaultArgs<ExtArgs>
}, ExtArgs["result"]["mcRunHour"]>

export type McRunHourSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  machine_id?: boolean
  mc_run_h?: boolean
  mc_run_kwh?: boolean
  heat_up_h?: boolean
  heat_up_kwh?: boolean
  iddle_h?: boolean
  iddle_kwh?: boolean
  mc_production_h?: boolean
  mc_production_kwh?: boolean
  is_one_block?: boolean
  machine?: boolean | Prisma.MachineDefaultArgs<ExtArgs>
}, ExtArgs["result"]["mcRunHour"]>

export type McRunHourSelectScalar = {
  id?: boolean
  date?: boolean
  machine_id?: boolean
  mc_run_h?: boolean
  mc_run_kwh?: boolean
  heat_up_h?: boolean
  heat_up_kwh?: boolean
  iddle_h?: boolean
  iddle_kwh?: boolean
  mc_production_h?: boolean
  mc_production_kwh?: boolean
  is_one_block?: boolean
}

export type McRunHourOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "date" | "machine_id" | "mc_run_h" | "mc_run_kwh" | "heat_up_h" | "heat_up_kwh" | "iddle_h" | "iddle_kwh" | "mc_production_h" | "mc_production_kwh" | "is_one_block", ExtArgs["result"]["mcRunHour"]>
export type McRunHourInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  machine?: boolean | Prisma.MachineDefaultArgs<ExtArgs>
}
export type McRunHourIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  machine?: boolean | Prisma.MachineDefaultArgs<ExtArgs>
}
export type McRunHourIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  machine?: boolean | Prisma.MachineDefaultArgs<ExtArgs>
}

export type $McRunHourPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "McRunHour"
  objects: {
    machine: Prisma.$MachinePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    date: Date
    machine_id: number
    mc_run_h: string
    mc_run_kwh: string
    heat_up_h: string
    heat_up_kwh: string
    iddle_h: string
    iddle_kwh: string
    mc_production_h: string
    mc_production_kwh: string
    is_one_block: boolean
  }, ExtArgs["result"]["mcRunHour"]>
  composites: {}
}

export type McRunHourGetPayload<S extends boolean | null | undefined | McRunHourDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$McRunHourPayload, S>

export type McRunHourCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<McRunHourFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: McRunHourCountAggregateInputType | true
  }

export interface McRunHourDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['McRunHour'], meta: { name: 'McRunHour' } }
  /**
   * Find zero or one McRunHour that matches the filter.
   * @param {McRunHourFindUniqueArgs} args - Arguments to find a McRunHour
   * @example
   * // Get one McRunHour
   * const mcRunHour = await prisma.mcRunHour.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends McRunHourFindUniqueArgs>(args: Prisma.SelectSubset<T, McRunHourFindUniqueArgs<ExtArgs>>): Prisma.Prisma__McRunHourClient<runtime.Types.Result.GetResult<Prisma.$McRunHourPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one McRunHour that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {McRunHourFindUniqueOrThrowArgs} args - Arguments to find a McRunHour
   * @example
   * // Get one McRunHour
   * const mcRunHour = await prisma.mcRunHour.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends McRunHourFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, McRunHourFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__McRunHourClient<runtime.Types.Result.GetResult<Prisma.$McRunHourPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first McRunHour that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {McRunHourFindFirstArgs} args - Arguments to find a McRunHour
   * @example
   * // Get one McRunHour
   * const mcRunHour = await prisma.mcRunHour.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends McRunHourFindFirstArgs>(args?: Prisma.SelectSubset<T, McRunHourFindFirstArgs<ExtArgs>>): Prisma.Prisma__McRunHourClient<runtime.Types.Result.GetResult<Prisma.$McRunHourPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first McRunHour that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {McRunHourFindFirstOrThrowArgs} args - Arguments to find a McRunHour
   * @example
   * // Get one McRunHour
   * const mcRunHour = await prisma.mcRunHour.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends McRunHourFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, McRunHourFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__McRunHourClient<runtime.Types.Result.GetResult<Prisma.$McRunHourPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more McRunHours that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {McRunHourFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all McRunHours
   * const mcRunHours = await prisma.mcRunHour.findMany()
   * 
   * // Get first 10 McRunHours
   * const mcRunHours = await prisma.mcRunHour.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const mcRunHourWithIdOnly = await prisma.mcRunHour.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends McRunHourFindManyArgs>(args?: Prisma.SelectSubset<T, McRunHourFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$McRunHourPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a McRunHour.
   * @param {McRunHourCreateArgs} args - Arguments to create a McRunHour.
   * @example
   * // Create one McRunHour
   * const McRunHour = await prisma.mcRunHour.create({
   *   data: {
   *     // ... data to create a McRunHour
   *   }
   * })
   * 
   */
  create<T extends McRunHourCreateArgs>(args: Prisma.SelectSubset<T, McRunHourCreateArgs<ExtArgs>>): Prisma.Prisma__McRunHourClient<runtime.Types.Result.GetResult<Prisma.$McRunHourPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many McRunHours.
   * @param {McRunHourCreateManyArgs} args - Arguments to create many McRunHours.
   * @example
   * // Create many McRunHours
   * const mcRunHour = await prisma.mcRunHour.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends McRunHourCreateManyArgs>(args?: Prisma.SelectSubset<T, McRunHourCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many McRunHours and returns the data saved in the database.
   * @param {McRunHourCreateManyAndReturnArgs} args - Arguments to create many McRunHours.
   * @example
   * // Create many McRunHours
   * const mcRunHour = await prisma.mcRunHour.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many McRunHours and only return the `id`
   * const mcRunHourWithIdOnly = await prisma.mcRunHour.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends McRunHourCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, McRunHourCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$McRunHourPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a McRunHour.
   * @param {McRunHourDeleteArgs} args - Arguments to delete one McRunHour.
   * @example
   * // Delete one McRunHour
   * const McRunHour = await prisma.mcRunHour.delete({
   *   where: {
   *     // ... filter to delete one McRunHour
   *   }
   * })
   * 
   */
  delete<T extends McRunHourDeleteArgs>(args: Prisma.SelectSubset<T, McRunHourDeleteArgs<ExtArgs>>): Prisma.Prisma__McRunHourClient<runtime.Types.Result.GetResult<Prisma.$McRunHourPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one McRunHour.
   * @param {McRunHourUpdateArgs} args - Arguments to update one McRunHour.
   * @example
   * // Update one McRunHour
   * const mcRunHour = await prisma.mcRunHour.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends McRunHourUpdateArgs>(args: Prisma.SelectSubset<T, McRunHourUpdateArgs<ExtArgs>>): Prisma.Prisma__McRunHourClient<runtime.Types.Result.GetResult<Prisma.$McRunHourPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more McRunHours.
   * @param {McRunHourDeleteManyArgs} args - Arguments to filter McRunHours to delete.
   * @example
   * // Delete a few McRunHours
   * const { count } = await prisma.mcRunHour.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends McRunHourDeleteManyArgs>(args?: Prisma.SelectSubset<T, McRunHourDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more McRunHours.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {McRunHourUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many McRunHours
   * const mcRunHour = await prisma.mcRunHour.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends McRunHourUpdateManyArgs>(args: Prisma.SelectSubset<T, McRunHourUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more McRunHours and returns the data updated in the database.
   * @param {McRunHourUpdateManyAndReturnArgs} args - Arguments to update many McRunHours.
   * @example
   * // Update many McRunHours
   * const mcRunHour = await prisma.mcRunHour.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more McRunHours and only return the `id`
   * const mcRunHourWithIdOnly = await prisma.mcRunHour.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends McRunHourUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, McRunHourUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$McRunHourPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one McRunHour.
   * @param {McRunHourUpsertArgs} args - Arguments to update or create a McRunHour.
   * @example
   * // Update or create a McRunHour
   * const mcRunHour = await prisma.mcRunHour.upsert({
   *   create: {
   *     // ... data to create a McRunHour
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the McRunHour we want to update
   *   }
   * })
   */
  upsert<T extends McRunHourUpsertArgs>(args: Prisma.SelectSubset<T, McRunHourUpsertArgs<ExtArgs>>): Prisma.Prisma__McRunHourClient<runtime.Types.Result.GetResult<Prisma.$McRunHourPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of McRunHours.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {McRunHourCountArgs} args - Arguments to filter McRunHours to count.
   * @example
   * // Count the number of McRunHours
   * const count = await prisma.mcRunHour.count({
   *   where: {
   *     // ... the filter for the McRunHours we want to count
   *   }
   * })
  **/
  count<T extends McRunHourCountArgs>(
    args?: Prisma.Subset<T, McRunHourCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], McRunHourCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a McRunHour.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {McRunHourAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends McRunHourAggregateArgs>(args: Prisma.Subset<T, McRunHourAggregateArgs>): Prisma.PrismaPromise<GetMcRunHourAggregateType<T>>

  /**
   * Group by McRunHour.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {McRunHourGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends McRunHourGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: McRunHourGroupByArgs['orderBy'] }
      : { orderBy?: McRunHourGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, McRunHourGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMcRunHourGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the McRunHour model
 */
readonly fields: McRunHourFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for McRunHour.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__McRunHourClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  machine<T extends Prisma.MachineDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MachineDefaultArgs<ExtArgs>>): Prisma.Prisma__MachineClient<runtime.Types.Result.GetResult<Prisma.$MachinePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the McRunHour model
 */
export interface McRunHourFieldRefs {
  readonly id: Prisma.FieldRef<"McRunHour", 'String'>
  readonly date: Prisma.FieldRef<"McRunHour", 'DateTime'>
  readonly machine_id: Prisma.FieldRef<"McRunHour", 'Int'>
  readonly mc_run_h: Prisma.FieldRef<"McRunHour", 'String'>
  readonly mc_run_kwh: Prisma.FieldRef<"McRunHour", 'String'>
  readonly heat_up_h: Prisma.FieldRef<"McRunHour", 'String'>
  readonly heat_up_kwh: Prisma.FieldRef<"McRunHour", 'String'>
  readonly iddle_h: Prisma.FieldRef<"McRunHour", 'String'>
  readonly iddle_kwh: Prisma.FieldRef<"McRunHour", 'String'>
  readonly mc_production_h: Prisma.FieldRef<"McRunHour", 'String'>
  readonly mc_production_kwh: Prisma.FieldRef<"McRunHour", 'String'>
  readonly is_one_block: Prisma.FieldRef<"McRunHour", 'Boolean'>
}
    

// Custom InputTypes
/**
 * McRunHour findUnique
 */
export type McRunHourFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McRunHour
   */
  select?: Prisma.McRunHourSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McRunHour
   */
  omit?: Prisma.McRunHourOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.McRunHourInclude<ExtArgs> | null
  /**
   * Filter, which McRunHour to fetch.
   */
  where: Prisma.McRunHourWhereUniqueInput
}

/**
 * McRunHour findUniqueOrThrow
 */
export type McRunHourFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McRunHour
   */
  select?: Prisma.McRunHourSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McRunHour
   */
  omit?: Prisma.McRunHourOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.McRunHourInclude<ExtArgs> | null
  /**
   * Filter, which McRunHour to fetch.
   */
  where: Prisma.McRunHourWhereUniqueInput
}

/**
 * McRunHour findFirst
 */
export type McRunHourFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McRunHour
   */
  select?: Prisma.McRunHourSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McRunHour
   */
  omit?: Prisma.McRunHourOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.McRunHourInclude<ExtArgs> | null
  /**
   * Filter, which McRunHour to fetch.
   */
  where?: Prisma.McRunHourWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of McRunHours to fetch.
   */
  orderBy?: Prisma.McRunHourOrderByWithRelationInput | Prisma.McRunHourOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for McRunHours.
   */
  cursor?: Prisma.McRunHourWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` McRunHours from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` McRunHours.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of McRunHours.
   */
  distinct?: Prisma.McRunHourScalarFieldEnum | Prisma.McRunHourScalarFieldEnum[]
}

/**
 * McRunHour findFirstOrThrow
 */
export type McRunHourFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McRunHour
   */
  select?: Prisma.McRunHourSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McRunHour
   */
  omit?: Prisma.McRunHourOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.McRunHourInclude<ExtArgs> | null
  /**
   * Filter, which McRunHour to fetch.
   */
  where?: Prisma.McRunHourWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of McRunHours to fetch.
   */
  orderBy?: Prisma.McRunHourOrderByWithRelationInput | Prisma.McRunHourOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for McRunHours.
   */
  cursor?: Prisma.McRunHourWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` McRunHours from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` McRunHours.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of McRunHours.
   */
  distinct?: Prisma.McRunHourScalarFieldEnum | Prisma.McRunHourScalarFieldEnum[]
}

/**
 * McRunHour findMany
 */
export type McRunHourFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McRunHour
   */
  select?: Prisma.McRunHourSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McRunHour
   */
  omit?: Prisma.McRunHourOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.McRunHourInclude<ExtArgs> | null
  /**
   * Filter, which McRunHours to fetch.
   */
  where?: Prisma.McRunHourWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of McRunHours to fetch.
   */
  orderBy?: Prisma.McRunHourOrderByWithRelationInput | Prisma.McRunHourOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing McRunHours.
   */
  cursor?: Prisma.McRunHourWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` McRunHours from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` McRunHours.
   */
  skip?: number
  distinct?: Prisma.McRunHourScalarFieldEnum | Prisma.McRunHourScalarFieldEnum[]
}

/**
 * McRunHour create
 */
export type McRunHourCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McRunHour
   */
  select?: Prisma.McRunHourSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McRunHour
   */
  omit?: Prisma.McRunHourOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.McRunHourInclude<ExtArgs> | null
  /**
   * The data needed to create a McRunHour.
   */
  data: Prisma.XOR<Prisma.McRunHourCreateInput, Prisma.McRunHourUncheckedCreateInput>
}

/**
 * McRunHour createMany
 */
export type McRunHourCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many McRunHours.
   */
  data: Prisma.McRunHourCreateManyInput | Prisma.McRunHourCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * McRunHour createManyAndReturn
 */
export type McRunHourCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McRunHour
   */
  select?: Prisma.McRunHourSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the McRunHour
   */
  omit?: Prisma.McRunHourOmit<ExtArgs> | null
  /**
   * The data used to create many McRunHours.
   */
  data: Prisma.McRunHourCreateManyInput | Prisma.McRunHourCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.McRunHourIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * McRunHour update
 */
export type McRunHourUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McRunHour
   */
  select?: Prisma.McRunHourSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McRunHour
   */
  omit?: Prisma.McRunHourOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.McRunHourInclude<ExtArgs> | null
  /**
   * The data needed to update a McRunHour.
   */
  data: Prisma.XOR<Prisma.McRunHourUpdateInput, Prisma.McRunHourUncheckedUpdateInput>
  /**
   * Choose, which McRunHour to update.
   */
  where: Prisma.McRunHourWhereUniqueInput
}

/**
 * McRunHour updateMany
 */
export type McRunHourUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update McRunHours.
   */
  data: Prisma.XOR<Prisma.McRunHourUpdateManyMutationInput, Prisma.McRunHourUncheckedUpdateManyInput>
  /**
   * Filter which McRunHours to update
   */
  where?: Prisma.McRunHourWhereInput
  /**
   * Limit how many McRunHours to update.
   */
  limit?: number
}

/**
 * McRunHour updateManyAndReturn
 */
export type McRunHourUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McRunHour
   */
  select?: Prisma.McRunHourSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the McRunHour
   */
  omit?: Prisma.McRunHourOmit<ExtArgs> | null
  /**
   * The data used to update McRunHours.
   */
  data: Prisma.XOR<Prisma.McRunHourUpdateManyMutationInput, Prisma.McRunHourUncheckedUpdateManyInput>
  /**
   * Filter which McRunHours to update
   */
  where?: Prisma.McRunHourWhereInput
  /**
   * Limit how many McRunHours to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.McRunHourIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * McRunHour upsert
 */
export type McRunHourUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McRunHour
   */
  select?: Prisma.McRunHourSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McRunHour
   */
  omit?: Prisma.McRunHourOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.McRunHourInclude<ExtArgs> | null
  /**
   * The filter to search for the McRunHour to update in case it exists.
   */
  where: Prisma.McRunHourWhereUniqueInput
  /**
   * In case the McRunHour found by the `where` argument doesn't exist, create a new McRunHour with this data.
   */
  create: Prisma.XOR<Prisma.McRunHourCreateInput, Prisma.McRunHourUncheckedCreateInput>
  /**
   * In case the McRunHour was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.McRunHourUpdateInput, Prisma.McRunHourUncheckedUpdateInput>
}

/**
 * McRunHour delete
 */
export type McRunHourDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McRunHour
   */
  select?: Prisma.McRunHourSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McRunHour
   */
  omit?: Prisma.McRunHourOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.McRunHourInclude<ExtArgs> | null
  /**
   * Filter which McRunHour to delete.
   */
  where: Prisma.McRunHourWhereUniqueInput
}

/**
 * McRunHour deleteMany
 */
export type McRunHourDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which McRunHours to delete
   */
  where?: Prisma.McRunHourWhereInput
  /**
   * Limit how many McRunHours to delete.
   */
  limit?: number
}

/**
 * McRunHour without action
 */
export type McRunHourDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McRunHour
   */
  select?: Prisma.McRunHourSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McRunHour
   */
  omit?: Prisma.McRunHourOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.McRunHourInclude<ExtArgs> | null
}
