
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `OnContactSensor` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model OnContactSensor
 * 
 */
export type OnContactSensorModel = runtime.Types.Result.DefaultSelection<Prisma.$OnContactSensorPayload>

export type AggregateOnContactSensor = {
  _count: OnContactSensorCountAggregateOutputType | null
  _avg: OnContactSensorAvgAggregateOutputType | null
  _sum: OnContactSensorSumAggregateOutputType | null
  _min: OnContactSensorMinAggregateOutputType | null
  _max: OnContactSensorMaxAggregateOutputType | null
}

export type OnContactSensorAvgAggregateOutputType = {
  id: number | null
  address: number | null
  gateway_id: number | null
  mapping_id: number | null
}

export type OnContactSensorSumAggregateOutputType = {
  id: number | null
  address: number | null
  gateway_id: number | null
  mapping_id: number | null
}

export type OnContactSensorMinAggregateOutputType = {
  id: number | null
  name: string | null
  address: number | null
  gateway_id: number | null
  mapping_id: number | null
}

export type OnContactSensorMaxAggregateOutputType = {
  id: number | null
  name: string | null
  address: number | null
  gateway_id: number | null
  mapping_id: number | null
}

export type OnContactSensorCountAggregateOutputType = {
  id: number
  name: number
  address: number
  gateway_id: number
  mapping_id: number
  _all: number
}


export type OnContactSensorAvgAggregateInputType = {
  id?: true
  address?: true
  gateway_id?: true
  mapping_id?: true
}

export type OnContactSensorSumAggregateInputType = {
  id?: true
  address?: true
  gateway_id?: true
  mapping_id?: true
}

export type OnContactSensorMinAggregateInputType = {
  id?: true
  name?: true
  address?: true
  gateway_id?: true
  mapping_id?: true
}

export type OnContactSensorMaxAggregateInputType = {
  id?: true
  name?: true
  address?: true
  gateway_id?: true
  mapping_id?: true
}

export type OnContactSensorCountAggregateInputType = {
  id?: true
  name?: true
  address?: true
  gateway_id?: true
  mapping_id?: true
  _all?: true
}

export type OnContactSensorAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OnContactSensor to aggregate.
   */
  where?: Prisma.OnContactSensorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OnContactSensors to fetch.
   */
  orderBy?: Prisma.OnContactSensorOrderByWithRelationInput | Prisma.OnContactSensorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.OnContactSensorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OnContactSensors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OnContactSensors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned OnContactSensors
  **/
  _count?: true | OnContactSensorCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: OnContactSensorAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: OnContactSensorSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: OnContactSensorMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: OnContactSensorMaxAggregateInputType
}

export type GetOnContactSensorAggregateType<T extends OnContactSensorAggregateArgs> = {
      [P in keyof T & keyof AggregateOnContactSensor]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOnContactSensor[P]>
    : Prisma.GetScalarType<T[P], AggregateOnContactSensor[P]>
}




export type OnContactSensorGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OnContactSensorWhereInput
  orderBy?: Prisma.OnContactSensorOrderByWithAggregationInput | Prisma.OnContactSensorOrderByWithAggregationInput[]
  by: Prisma.OnContactSensorScalarFieldEnum[] | Prisma.OnContactSensorScalarFieldEnum
  having?: Prisma.OnContactSensorScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: OnContactSensorCountAggregateInputType | true
  _avg?: OnContactSensorAvgAggregateInputType
  _sum?: OnContactSensorSumAggregateInputType
  _min?: OnContactSensorMinAggregateInputType
  _max?: OnContactSensorMaxAggregateInputType
}

export type OnContactSensorGroupByOutputType = {
  id: number
  name: string
  address: number
  gateway_id: number
  mapping_id: number
  _count: OnContactSensorCountAggregateOutputType | null
  _avg: OnContactSensorAvgAggregateOutputType | null
  _sum: OnContactSensorSumAggregateOutputType | null
  _min: OnContactSensorMinAggregateOutputType | null
  _max: OnContactSensorMaxAggregateOutputType | null
}

type GetOnContactSensorGroupByPayload<T extends OnContactSensorGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<OnContactSensorGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof OnContactSensorGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], OnContactSensorGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], OnContactSensorGroupByOutputType[P]>
      }
    >
  >



export type OnContactSensorWhereInput = {
  AND?: Prisma.OnContactSensorWhereInput | Prisma.OnContactSensorWhereInput[]
  OR?: Prisma.OnContactSensorWhereInput[]
  NOT?: Prisma.OnContactSensorWhereInput | Prisma.OnContactSensorWhereInput[]
  id?: Prisma.IntFilter<"OnContactSensor"> | number
  name?: Prisma.StringFilter<"OnContactSensor"> | string
  address?: Prisma.IntFilter<"OnContactSensor"> | number
  gateway_id?: Prisma.IntFilter<"OnContactSensor"> | number
  mapping_id?: Prisma.IntFilter<"OnContactSensor"> | number
  gateway?: Prisma.XOR<Prisma.GatewayScalarRelationFilter, Prisma.GatewayWhereInput>
  mapping?: Prisma.XOR<Prisma.MappingScalarRelationFilter, Prisma.MappingWhereInput>
  machines?: Prisma.MachineListRelationFilter
}

export type OnContactSensorOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  address?: Prisma.SortOrder
  gateway_id?: Prisma.SortOrder
  mapping_id?: Prisma.SortOrder
  gateway?: Prisma.GatewayOrderByWithRelationInput
  mapping?: Prisma.MappingOrderByWithRelationInput
  machines?: Prisma.MachineOrderByRelationAggregateInput
}

export type OnContactSensorWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.OnContactSensorWhereInput | Prisma.OnContactSensorWhereInput[]
  OR?: Prisma.OnContactSensorWhereInput[]
  NOT?: Prisma.OnContactSensorWhereInput | Prisma.OnContactSensorWhereInput[]
  name?: Prisma.StringFilter<"OnContactSensor"> | string
  address?: Prisma.IntFilter<"OnContactSensor"> | number
  gateway_id?: Prisma.IntFilter<"OnContactSensor"> | number
  mapping_id?: Prisma.IntFilter<"OnContactSensor"> | number
  gateway?: Prisma.XOR<Prisma.GatewayScalarRelationFilter, Prisma.GatewayWhereInput>
  mapping?: Prisma.XOR<Prisma.MappingScalarRelationFilter, Prisma.MappingWhereInput>
  machines?: Prisma.MachineListRelationFilter
}, "id">

export type OnContactSensorOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  address?: Prisma.SortOrder
  gateway_id?: Prisma.SortOrder
  mapping_id?: Prisma.SortOrder
  _count?: Prisma.OnContactSensorCountOrderByAggregateInput
  _avg?: Prisma.OnContactSensorAvgOrderByAggregateInput
  _max?: Prisma.OnContactSensorMaxOrderByAggregateInput
  _min?: Prisma.OnContactSensorMinOrderByAggregateInput
  _sum?: Prisma.OnContactSensorSumOrderByAggregateInput
}

export type OnContactSensorScalarWhereWithAggregatesInput = {
  AND?: Prisma.OnContactSensorScalarWhereWithAggregatesInput | Prisma.OnContactSensorScalarWhereWithAggregatesInput[]
  OR?: Prisma.OnContactSensorScalarWhereWithAggregatesInput[]
  NOT?: Prisma.OnContactSensorScalarWhereWithAggregatesInput | Prisma.OnContactSensorScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"OnContactSensor"> | number
  name?: Prisma.StringWithAggregatesFilter<"OnContactSensor"> | string
  address?: Prisma.IntWithAggregatesFilter<"OnContactSensor"> | number
  gateway_id?: Prisma.IntWithAggregatesFilter<"OnContactSensor"> | number
  mapping_id?: Prisma.IntWithAggregatesFilter<"OnContactSensor"> | number
}

export type OnContactSensorCreateInput = {
  name: string
  address: number
  gateway: Prisma.GatewayCreateNestedOneWithoutOn_contact_sensorsInput
  mapping: Prisma.MappingCreateNestedOneWithoutOn_contact_sensorsInput
  machines?: Prisma.MachineCreateNestedManyWithoutOn_contact_sensorInput
}

export type OnContactSensorUncheckedCreateInput = {
  id?: number
  name: string
  address: number
  gateway_id: number
  mapping_id: number
  machines?: Prisma.MachineUncheckedCreateNestedManyWithoutOn_contact_sensorInput
}

export type OnContactSensorUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.IntFieldUpdateOperationsInput | number
  gateway?: Prisma.GatewayUpdateOneRequiredWithoutOn_contact_sensorsNestedInput
  mapping?: Prisma.MappingUpdateOneRequiredWithoutOn_contact_sensorsNestedInput
  machines?: Prisma.MachineUpdateManyWithoutOn_contact_sensorNestedInput
}

export type OnContactSensorUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.IntFieldUpdateOperationsInput | number
  gateway_id?: Prisma.IntFieldUpdateOperationsInput | number
  mapping_id?: Prisma.IntFieldUpdateOperationsInput | number
  machines?: Prisma.MachineUncheckedUpdateManyWithoutOn_contact_sensorNestedInput
}

export type OnContactSensorCreateManyInput = {
  id?: number
  name: string
  address: number
  gateway_id: number
  mapping_id: number
}

export type OnContactSensorUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.IntFieldUpdateOperationsInput | number
}

export type OnContactSensorUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.IntFieldUpdateOperationsInput | number
  gateway_id?: Prisma.IntFieldUpdateOperationsInput | number
  mapping_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type OnContactSensorListRelationFilter = {
  every?: Prisma.OnContactSensorWhereInput
  some?: Prisma.OnContactSensorWhereInput
  none?: Prisma.OnContactSensorWhereInput
}

export type OnContactSensorOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type OnContactSensorCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  address?: Prisma.SortOrder
  gateway_id?: Prisma.SortOrder
  mapping_id?: Prisma.SortOrder
}

export type OnContactSensorAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  address?: Prisma.SortOrder
  gateway_id?: Prisma.SortOrder
  mapping_id?: Prisma.SortOrder
}

export type OnContactSensorMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  address?: Prisma.SortOrder
  gateway_id?: Prisma.SortOrder
  mapping_id?: Prisma.SortOrder
}

export type OnContactSensorMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  address?: Prisma.SortOrder
  gateway_id?: Prisma.SortOrder
  mapping_id?: Prisma.SortOrder
}

export type OnContactSensorSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  address?: Prisma.SortOrder
  gateway_id?: Prisma.SortOrder
  mapping_id?: Prisma.SortOrder
}

export type OnContactSensorScalarRelationFilter = {
  is?: Prisma.OnContactSensorWhereInput
  isNot?: Prisma.OnContactSensorWhereInput
}

export type OnContactSensorCreateNestedManyWithoutGatewayInput = {
  create?: Prisma.XOR<Prisma.OnContactSensorCreateWithoutGatewayInput, Prisma.OnContactSensorUncheckedCreateWithoutGatewayInput> | Prisma.OnContactSensorCreateWithoutGatewayInput[] | Prisma.OnContactSensorUncheckedCreateWithoutGatewayInput[]
  connectOrCreate?: Prisma.OnContactSensorCreateOrConnectWithoutGatewayInput | Prisma.OnContactSensorCreateOrConnectWithoutGatewayInput[]
  createMany?: Prisma.OnContactSensorCreateManyGatewayInputEnvelope
  connect?: Prisma.OnContactSensorWhereUniqueInput | Prisma.OnContactSensorWhereUniqueInput[]
}

export type OnContactSensorUncheckedCreateNestedManyWithoutGatewayInput = {
  create?: Prisma.XOR<Prisma.OnContactSensorCreateWithoutGatewayInput, Prisma.OnContactSensorUncheckedCreateWithoutGatewayInput> | Prisma.OnContactSensorCreateWithoutGatewayInput[] | Prisma.OnContactSensorUncheckedCreateWithoutGatewayInput[]
  connectOrCreate?: Prisma.OnContactSensorCreateOrConnectWithoutGatewayInput | Prisma.OnContactSensorCreateOrConnectWithoutGatewayInput[]
  createMany?: Prisma.OnContactSensorCreateManyGatewayInputEnvelope
  connect?: Prisma.OnContactSensorWhereUniqueInput | Prisma.OnContactSensorWhereUniqueInput[]
}

export type OnContactSensorUpdateManyWithoutGatewayNestedInput = {
  create?: Prisma.XOR<Prisma.OnContactSensorCreateWithoutGatewayInput, Prisma.OnContactSensorUncheckedCreateWithoutGatewayInput> | Prisma.OnContactSensorCreateWithoutGatewayInput[] | Prisma.OnContactSensorUncheckedCreateWithoutGatewayInput[]
  connectOrCreate?: Prisma.OnContactSensorCreateOrConnectWithoutGatewayInput | Prisma.OnContactSensorCreateOrConnectWithoutGatewayInput[]
  upsert?: Prisma.OnContactSensorUpsertWithWhereUniqueWithoutGatewayInput | Prisma.OnContactSensorUpsertWithWhereUniqueWithoutGatewayInput[]
  createMany?: Prisma.OnContactSensorCreateManyGatewayInputEnvelope
  set?: Prisma.OnContactSensorWhereUniqueInput | Prisma.OnContactSensorWhereUniqueInput[]
  disconnect?: Prisma.OnContactSensorWhereUniqueInput | Prisma.OnContactSensorWhereUniqueInput[]
  delete?: Prisma.OnContactSensorWhereUniqueInput | Prisma.OnContactSensorWhereUniqueInput[]
  connect?: Prisma.OnContactSensorWhereUniqueInput | Prisma.OnContactSensorWhereUniqueInput[]
  update?: Prisma.OnContactSensorUpdateWithWhereUniqueWithoutGatewayInput | Prisma.OnContactSensorUpdateWithWhereUniqueWithoutGatewayInput[]
  updateMany?: Prisma.OnContactSensorUpdateManyWithWhereWithoutGatewayInput | Prisma.OnContactSensorUpdateManyWithWhereWithoutGatewayInput[]
  deleteMany?: Prisma.OnContactSensorScalarWhereInput | Prisma.OnContactSensorScalarWhereInput[]
}

export type OnContactSensorUncheckedUpdateManyWithoutGatewayNestedInput = {
  create?: Prisma.XOR<Prisma.OnContactSensorCreateWithoutGatewayInput, Prisma.OnContactSensorUncheckedCreateWithoutGatewayInput> | Prisma.OnContactSensorCreateWithoutGatewayInput[] | Prisma.OnContactSensorUncheckedCreateWithoutGatewayInput[]
  connectOrCreate?: Prisma.OnContactSensorCreateOrConnectWithoutGatewayInput | Prisma.OnContactSensorCreateOrConnectWithoutGatewayInput[]
  upsert?: Prisma.OnContactSensorUpsertWithWhereUniqueWithoutGatewayInput | Prisma.OnContactSensorUpsertWithWhereUniqueWithoutGatewayInput[]
  createMany?: Prisma.OnContactSensorCreateManyGatewayInputEnvelope
  set?: Prisma.OnContactSensorWhereUniqueInput | Prisma.OnContactSensorWhereUniqueInput[]
  disconnect?: Prisma.OnContactSensorWhereUniqueInput | Prisma.OnContactSensorWhereUniqueInput[]
  delete?: Prisma.OnContactSensorWhereUniqueInput | Prisma.OnContactSensorWhereUniqueInput[]
  connect?: Prisma.OnContactSensorWhereUniqueInput | Prisma.OnContactSensorWhereUniqueInput[]
  update?: Prisma.OnContactSensorUpdateWithWhereUniqueWithoutGatewayInput | Prisma.OnContactSensorUpdateWithWhereUniqueWithoutGatewayInput[]
  updateMany?: Prisma.OnContactSensorUpdateManyWithWhereWithoutGatewayInput | Prisma.OnContactSensorUpdateManyWithWhereWithoutGatewayInput[]
  deleteMany?: Prisma.OnContactSensorScalarWhereInput | Prisma.OnContactSensorScalarWhereInput[]
}

export type OnContactSensorCreateNestedManyWithoutMappingInput = {
  create?: Prisma.XOR<Prisma.OnContactSensorCreateWithoutMappingInput, Prisma.OnContactSensorUncheckedCreateWithoutMappingInput> | Prisma.OnContactSensorCreateWithoutMappingInput[] | Prisma.OnContactSensorUncheckedCreateWithoutMappingInput[]
  connectOrCreate?: Prisma.OnContactSensorCreateOrConnectWithoutMappingInput | Prisma.OnContactSensorCreateOrConnectWithoutMappingInput[]
  createMany?: Prisma.OnContactSensorCreateManyMappingInputEnvelope
  connect?: Prisma.OnContactSensorWhereUniqueInput | Prisma.OnContactSensorWhereUniqueInput[]
}

export type OnContactSensorUncheckedCreateNestedManyWithoutMappingInput = {
  create?: Prisma.XOR<Prisma.OnContactSensorCreateWithoutMappingInput, Prisma.OnContactSensorUncheckedCreateWithoutMappingInput> | Prisma.OnContactSensorCreateWithoutMappingInput[] | Prisma.OnContactSensorUncheckedCreateWithoutMappingInput[]
  connectOrCreate?: Prisma.OnContactSensorCreateOrConnectWithoutMappingInput | Prisma.OnContactSensorCreateOrConnectWithoutMappingInput[]
  createMany?: Prisma.OnContactSensorCreateManyMappingInputEnvelope
  connect?: Prisma.OnContactSensorWhereUniqueInput | Prisma.OnContactSensorWhereUniqueInput[]
}

export type OnContactSensorUpdateManyWithoutMappingNestedInput = {
  create?: Prisma.XOR<Prisma.OnContactSensorCreateWithoutMappingInput, Prisma.OnContactSensorUncheckedCreateWithoutMappingInput> | Prisma.OnContactSensorCreateWithoutMappingInput[] | Prisma.OnContactSensorUncheckedCreateWithoutMappingInput[]
  connectOrCreate?: Prisma.OnContactSensorCreateOrConnectWithoutMappingInput | Prisma.OnContactSensorCreateOrConnectWithoutMappingInput[]
  upsert?: Prisma.OnContactSensorUpsertWithWhereUniqueWithoutMappingInput | Prisma.OnContactSensorUpsertWithWhereUniqueWithoutMappingInput[]
  createMany?: Prisma.OnContactSensorCreateManyMappingInputEnvelope
  set?: Prisma.OnContactSensorWhereUniqueInput | Prisma.OnContactSensorWhereUniqueInput[]
  disconnect?: Prisma.OnContactSensorWhereUniqueInput | Prisma.OnContactSensorWhereUniqueInput[]
  delete?: Prisma.OnContactSensorWhereUniqueInput | Prisma.OnContactSensorWhereUniqueInput[]
  connect?: Prisma.OnContactSensorWhereUniqueInput | Prisma.OnContactSensorWhereUniqueInput[]
  update?: Prisma.OnContactSensorUpdateWithWhereUniqueWithoutMappingInput | Prisma.OnContactSensorUpdateWithWhereUniqueWithoutMappingInput[]
  updateMany?: Prisma.OnContactSensorUpdateManyWithWhereWithoutMappingInput | Prisma.OnContactSensorUpdateManyWithWhereWithoutMappingInput[]
  deleteMany?: Prisma.OnContactSensorScalarWhereInput | Prisma.OnContactSensorScalarWhereInput[]
}

export type OnContactSensorUncheckedUpdateManyWithoutMappingNestedInput = {
  create?: Prisma.XOR<Prisma.OnContactSensorCreateWithoutMappingInput, Prisma.OnContactSensorUncheckedCreateWithoutMappingInput> | Prisma.OnContactSensorCreateWithoutMappingInput[] | Prisma.OnContactSensorUncheckedCreateWithoutMappingInput[]
  connectOrCreate?: Prisma.OnContactSensorCreateOrConnectWithoutMappingInput | Prisma.OnContactSensorCreateOrConnectWithoutMappingInput[]
  upsert?: Prisma.OnContactSensorUpsertWithWhereUniqueWithoutMappingInput | Prisma.OnContactSensorUpsertWithWhereUniqueWithoutMappingInput[]
  createMany?: Prisma.OnContactSensorCreateManyMappingInputEnvelope
  set?: Prisma.OnContactSensorWhereUniqueInput | Prisma.OnContactSensorWhereUniqueInput[]
  disconnect?: Prisma.OnContactSensorWhereUniqueInput | Prisma.OnContactSensorWhereUniqueInput[]
  delete?: Prisma.OnContactSensorWhereUniqueInput | Prisma.OnContactSensorWhereUniqueInput[]
  connect?: Prisma.OnContactSensorWhereUniqueInput | Prisma.OnContactSensorWhereUniqueInput[]
  update?: Prisma.OnContactSensorUpdateWithWhereUniqueWithoutMappingInput | Prisma.OnContactSensorUpdateWithWhereUniqueWithoutMappingInput[]
  updateMany?: Prisma.OnContactSensorUpdateManyWithWhereWithoutMappingInput | Prisma.OnContactSensorUpdateManyWithWhereWithoutMappingInput[]
  deleteMany?: Prisma.OnContactSensorScalarWhereInput | Prisma.OnContactSensorScalarWhereInput[]
}

export type OnContactSensorCreateNestedOneWithoutMachinesInput = {
  create?: Prisma.XOR<Prisma.OnContactSensorCreateWithoutMachinesInput, Prisma.OnContactSensorUncheckedCreateWithoutMachinesInput>
  connectOrCreate?: Prisma.OnContactSensorCreateOrConnectWithoutMachinesInput
  connect?: Prisma.OnContactSensorWhereUniqueInput
}

export type OnContactSensorUpdateOneRequiredWithoutMachinesNestedInput = {
  create?: Prisma.XOR<Prisma.OnContactSensorCreateWithoutMachinesInput, Prisma.OnContactSensorUncheckedCreateWithoutMachinesInput>
  connectOrCreate?: Prisma.OnContactSensorCreateOrConnectWithoutMachinesInput
  upsert?: Prisma.OnContactSensorUpsertWithoutMachinesInput
  connect?: Prisma.OnContactSensorWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.OnContactSensorUpdateToOneWithWhereWithoutMachinesInput, Prisma.OnContactSensorUpdateWithoutMachinesInput>, Prisma.OnContactSensorUncheckedUpdateWithoutMachinesInput>
}

export type OnContactSensorCreateWithoutGatewayInput = {
  name: string
  address: number
  mapping: Prisma.MappingCreateNestedOneWithoutOn_contact_sensorsInput
  machines?: Prisma.MachineCreateNestedManyWithoutOn_contact_sensorInput
}

export type OnContactSensorUncheckedCreateWithoutGatewayInput = {
  id?: number
  name: string
  address: number
  mapping_id: number
  machines?: Prisma.MachineUncheckedCreateNestedManyWithoutOn_contact_sensorInput
}

export type OnContactSensorCreateOrConnectWithoutGatewayInput = {
  where: Prisma.OnContactSensorWhereUniqueInput
  create: Prisma.XOR<Prisma.OnContactSensorCreateWithoutGatewayInput, Prisma.OnContactSensorUncheckedCreateWithoutGatewayInput>
}

export type OnContactSensorCreateManyGatewayInputEnvelope = {
  data: Prisma.OnContactSensorCreateManyGatewayInput | Prisma.OnContactSensorCreateManyGatewayInput[]
  skipDuplicates?: boolean
}

export type OnContactSensorUpsertWithWhereUniqueWithoutGatewayInput = {
  where: Prisma.OnContactSensorWhereUniqueInput
  update: Prisma.XOR<Prisma.OnContactSensorUpdateWithoutGatewayInput, Prisma.OnContactSensorUncheckedUpdateWithoutGatewayInput>
  create: Prisma.XOR<Prisma.OnContactSensorCreateWithoutGatewayInput, Prisma.OnContactSensorUncheckedCreateWithoutGatewayInput>
}

export type OnContactSensorUpdateWithWhereUniqueWithoutGatewayInput = {
  where: Prisma.OnContactSensorWhereUniqueInput
  data: Prisma.XOR<Prisma.OnContactSensorUpdateWithoutGatewayInput, Prisma.OnContactSensorUncheckedUpdateWithoutGatewayInput>
}

export type OnContactSensorUpdateManyWithWhereWithoutGatewayInput = {
  where: Prisma.OnContactSensorScalarWhereInput
  data: Prisma.XOR<Prisma.OnContactSensorUpdateManyMutationInput, Prisma.OnContactSensorUncheckedUpdateManyWithoutGatewayInput>
}

export type OnContactSensorScalarWhereInput = {
  AND?: Prisma.OnContactSensorScalarWhereInput | Prisma.OnContactSensorScalarWhereInput[]
  OR?: Prisma.OnContactSensorScalarWhereInput[]
  NOT?: Prisma.OnContactSensorScalarWhereInput | Prisma.OnContactSensorScalarWhereInput[]
  id?: Prisma.IntFilter<"OnContactSensor"> | number
  name?: Prisma.StringFilter<"OnContactSensor"> | string
  address?: Prisma.IntFilter<"OnContactSensor"> | number
  gateway_id?: Prisma.IntFilter<"OnContactSensor"> | number
  mapping_id?: Prisma.IntFilter<"OnContactSensor"> | number
}

export type OnContactSensorCreateWithoutMappingInput = {
  name: string
  address: number
  gateway: Prisma.GatewayCreateNestedOneWithoutOn_contact_sensorsInput
  machines?: Prisma.MachineCreateNestedManyWithoutOn_contact_sensorInput
}

export type OnContactSensorUncheckedCreateWithoutMappingInput = {
  id?: number
  name: string
  address: number
  gateway_id: number
  machines?: Prisma.MachineUncheckedCreateNestedManyWithoutOn_contact_sensorInput
}

export type OnContactSensorCreateOrConnectWithoutMappingInput = {
  where: Prisma.OnContactSensorWhereUniqueInput
  create: Prisma.XOR<Prisma.OnContactSensorCreateWithoutMappingInput, Prisma.OnContactSensorUncheckedCreateWithoutMappingInput>
}

export type OnContactSensorCreateManyMappingInputEnvelope = {
  data: Prisma.OnContactSensorCreateManyMappingInput | Prisma.OnContactSensorCreateManyMappingInput[]
  skipDuplicates?: boolean
}

export type OnContactSensorUpsertWithWhereUniqueWithoutMappingInput = {
  where: Prisma.OnContactSensorWhereUniqueInput
  update: Prisma.XOR<Prisma.OnContactSensorUpdateWithoutMappingInput, Prisma.OnContactSensorUncheckedUpdateWithoutMappingInput>
  create: Prisma.XOR<Prisma.OnContactSensorCreateWithoutMappingInput, Prisma.OnContactSensorUncheckedCreateWithoutMappingInput>
}

export type OnContactSensorUpdateWithWhereUniqueWithoutMappingInput = {
  where: Prisma.OnContactSensorWhereUniqueInput
  data: Prisma.XOR<Prisma.OnContactSensorUpdateWithoutMappingInput, Prisma.OnContactSensorUncheckedUpdateWithoutMappingInput>
}

export type OnContactSensorUpdateManyWithWhereWithoutMappingInput = {
  where: Prisma.OnContactSensorScalarWhereInput
  data: Prisma.XOR<Prisma.OnContactSensorUpdateManyMutationInput, Prisma.OnContactSensorUncheckedUpdateManyWithoutMappingInput>
}

export type OnContactSensorCreateWithoutMachinesInput = {
  name: string
  address: number
  gateway: Prisma.GatewayCreateNestedOneWithoutOn_contact_sensorsInput
  mapping: Prisma.MappingCreateNestedOneWithoutOn_contact_sensorsInput
}

export type OnContactSensorUncheckedCreateWithoutMachinesInput = {
  id?: number
  name: string
  address: number
  gateway_id: number
  mapping_id: number
}

export type OnContactSensorCreateOrConnectWithoutMachinesInput = {
  where: Prisma.OnContactSensorWhereUniqueInput
  create: Prisma.XOR<Prisma.OnContactSensorCreateWithoutMachinesInput, Prisma.OnContactSensorUncheckedCreateWithoutMachinesInput>
}

export type OnContactSensorUpsertWithoutMachinesInput = {
  update: Prisma.XOR<Prisma.OnContactSensorUpdateWithoutMachinesInput, Prisma.OnContactSensorUncheckedUpdateWithoutMachinesInput>
  create: Prisma.XOR<Prisma.OnContactSensorCreateWithoutMachinesInput, Prisma.OnContactSensorUncheckedCreateWithoutMachinesInput>
  where?: Prisma.OnContactSensorWhereInput
}

export type OnContactSensorUpdateToOneWithWhereWithoutMachinesInput = {
  where?: Prisma.OnContactSensorWhereInput
  data: Prisma.XOR<Prisma.OnContactSensorUpdateWithoutMachinesInput, Prisma.OnContactSensorUncheckedUpdateWithoutMachinesInput>
}

export type OnContactSensorUpdateWithoutMachinesInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.IntFieldUpdateOperationsInput | number
  gateway?: Prisma.GatewayUpdateOneRequiredWithoutOn_contact_sensorsNestedInput
  mapping?: Prisma.MappingUpdateOneRequiredWithoutOn_contact_sensorsNestedInput
}

export type OnContactSensorUncheckedUpdateWithoutMachinesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.IntFieldUpdateOperationsInput | number
  gateway_id?: Prisma.IntFieldUpdateOperationsInput | number
  mapping_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type OnContactSensorCreateManyGatewayInput = {
  id?: number
  name: string
  address: number
  mapping_id: number
}

export type OnContactSensorUpdateWithoutGatewayInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.IntFieldUpdateOperationsInput | number
  mapping?: Prisma.MappingUpdateOneRequiredWithoutOn_contact_sensorsNestedInput
  machines?: Prisma.MachineUpdateManyWithoutOn_contact_sensorNestedInput
}

export type OnContactSensorUncheckedUpdateWithoutGatewayInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.IntFieldUpdateOperationsInput | number
  mapping_id?: Prisma.IntFieldUpdateOperationsInput | number
  machines?: Prisma.MachineUncheckedUpdateManyWithoutOn_contact_sensorNestedInput
}

export type OnContactSensorUncheckedUpdateManyWithoutGatewayInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.IntFieldUpdateOperationsInput | number
  mapping_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type OnContactSensorCreateManyMappingInput = {
  id?: number
  name: string
  address: number
  gateway_id: number
}

export type OnContactSensorUpdateWithoutMappingInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.IntFieldUpdateOperationsInput | number
  gateway?: Prisma.GatewayUpdateOneRequiredWithoutOn_contact_sensorsNestedInput
  machines?: Prisma.MachineUpdateManyWithoutOn_contact_sensorNestedInput
}

export type OnContactSensorUncheckedUpdateWithoutMappingInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.IntFieldUpdateOperationsInput | number
  gateway_id?: Prisma.IntFieldUpdateOperationsInput | number
  machines?: Prisma.MachineUncheckedUpdateManyWithoutOn_contact_sensorNestedInput
}

export type OnContactSensorUncheckedUpdateManyWithoutMappingInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.IntFieldUpdateOperationsInput | number
  gateway_id?: Prisma.IntFieldUpdateOperationsInput | number
}


/**
 * Count Type OnContactSensorCountOutputType
 */

export type OnContactSensorCountOutputType = {
  machines: number
}

export type OnContactSensorCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  machines?: boolean | OnContactSensorCountOutputTypeCountMachinesArgs
}

/**
 * OnContactSensorCountOutputType without action
 */
export type OnContactSensorCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OnContactSensorCountOutputType
   */
  select?: Prisma.OnContactSensorCountOutputTypeSelect<ExtArgs> | null
}

/**
 * OnContactSensorCountOutputType without action
 */
export type OnContactSensorCountOutputTypeCountMachinesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MachineWhereInput
}


export type OnContactSensorSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  address?: boolean
  gateway_id?: boolean
  mapping_id?: boolean
  gateway?: boolean | Prisma.GatewayDefaultArgs<ExtArgs>
  mapping?: boolean | Prisma.MappingDefaultArgs<ExtArgs>
  machines?: boolean | Prisma.OnContactSensor$machinesArgs<ExtArgs>
  _count?: boolean | Prisma.OnContactSensorCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["onContactSensor"]>

export type OnContactSensorSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  address?: boolean
  gateway_id?: boolean
  mapping_id?: boolean
  gateway?: boolean | Prisma.GatewayDefaultArgs<ExtArgs>
  mapping?: boolean | Prisma.MappingDefaultArgs<ExtArgs>
}, ExtArgs["result"]["onContactSensor"]>

export type OnContactSensorSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  address?: boolean
  gateway_id?: boolean
  mapping_id?: boolean
  gateway?: boolean | Prisma.GatewayDefaultArgs<ExtArgs>
  mapping?: boolean | Prisma.MappingDefaultArgs<ExtArgs>
}, ExtArgs["result"]["onContactSensor"]>

export type OnContactSensorSelectScalar = {
  id?: boolean
  name?: boolean
  address?: boolean
  gateway_id?: boolean
  mapping_id?: boolean
}

export type OnContactSensorOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "address" | "gateway_id" | "mapping_id", ExtArgs["result"]["onContactSensor"]>
export type OnContactSensorInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  gateway?: boolean | Prisma.GatewayDefaultArgs<ExtArgs>
  mapping?: boolean | Prisma.MappingDefaultArgs<ExtArgs>
  machines?: boolean | Prisma.OnContactSensor$machinesArgs<ExtArgs>
  _count?: boolean | Prisma.OnContactSensorCountOutputTypeDefaultArgs<ExtArgs>
}
export type OnContactSensorIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  gateway?: boolean | Prisma.GatewayDefaultArgs<ExtArgs>
  mapping?: boolean | Prisma.MappingDefaultArgs<ExtArgs>
}
export type OnContactSensorIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  gateway?: boolean | Prisma.GatewayDefaultArgs<ExtArgs>
  mapping?: boolean | Prisma.MappingDefaultArgs<ExtArgs>
}

export type $OnContactSensorPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "OnContactSensor"
  objects: {
    gateway: Prisma.$GatewayPayload<ExtArgs>
    mapping: Prisma.$MappingPayload<ExtArgs>
    machines: Prisma.$MachinePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
    address: number
    gateway_id: number
    mapping_id: number
  }, ExtArgs["result"]["onContactSensor"]>
  composites: {}
}

export type OnContactSensorGetPayload<S extends boolean | null | undefined | OnContactSensorDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$OnContactSensorPayload, S>

export type OnContactSensorCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<OnContactSensorFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: OnContactSensorCountAggregateInputType | true
  }

export interface OnContactSensorDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['OnContactSensor'], meta: { name: 'OnContactSensor' } }
  /**
   * Find zero or one OnContactSensor that matches the filter.
   * @param {OnContactSensorFindUniqueArgs} args - Arguments to find a OnContactSensor
   * @example
   * // Get one OnContactSensor
   * const onContactSensor = await prisma.onContactSensor.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends OnContactSensorFindUniqueArgs>(args: Prisma.SelectSubset<T, OnContactSensorFindUniqueArgs<ExtArgs>>): Prisma.Prisma__OnContactSensorClient<runtime.Types.Result.GetResult<Prisma.$OnContactSensorPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one OnContactSensor that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {OnContactSensorFindUniqueOrThrowArgs} args - Arguments to find a OnContactSensor
   * @example
   * // Get one OnContactSensor
   * const onContactSensor = await prisma.onContactSensor.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends OnContactSensorFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, OnContactSensorFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__OnContactSensorClient<runtime.Types.Result.GetResult<Prisma.$OnContactSensorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OnContactSensor that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OnContactSensorFindFirstArgs} args - Arguments to find a OnContactSensor
   * @example
   * // Get one OnContactSensor
   * const onContactSensor = await prisma.onContactSensor.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends OnContactSensorFindFirstArgs>(args?: Prisma.SelectSubset<T, OnContactSensorFindFirstArgs<ExtArgs>>): Prisma.Prisma__OnContactSensorClient<runtime.Types.Result.GetResult<Prisma.$OnContactSensorPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OnContactSensor that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OnContactSensorFindFirstOrThrowArgs} args - Arguments to find a OnContactSensor
   * @example
   * // Get one OnContactSensor
   * const onContactSensor = await prisma.onContactSensor.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends OnContactSensorFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, OnContactSensorFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__OnContactSensorClient<runtime.Types.Result.GetResult<Prisma.$OnContactSensorPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more OnContactSensors that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OnContactSensorFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all OnContactSensors
   * const onContactSensors = await prisma.onContactSensor.findMany()
   * 
   * // Get first 10 OnContactSensors
   * const onContactSensors = await prisma.onContactSensor.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const onContactSensorWithIdOnly = await prisma.onContactSensor.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends OnContactSensorFindManyArgs>(args?: Prisma.SelectSubset<T, OnContactSensorFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OnContactSensorPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a OnContactSensor.
   * @param {OnContactSensorCreateArgs} args - Arguments to create a OnContactSensor.
   * @example
   * // Create one OnContactSensor
   * const OnContactSensor = await prisma.onContactSensor.create({
   *   data: {
   *     // ... data to create a OnContactSensor
   *   }
   * })
   * 
   */
  create<T extends OnContactSensorCreateArgs>(args: Prisma.SelectSubset<T, OnContactSensorCreateArgs<ExtArgs>>): Prisma.Prisma__OnContactSensorClient<runtime.Types.Result.GetResult<Prisma.$OnContactSensorPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many OnContactSensors.
   * @param {OnContactSensorCreateManyArgs} args - Arguments to create many OnContactSensors.
   * @example
   * // Create many OnContactSensors
   * const onContactSensor = await prisma.onContactSensor.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends OnContactSensorCreateManyArgs>(args?: Prisma.SelectSubset<T, OnContactSensorCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many OnContactSensors and returns the data saved in the database.
   * @param {OnContactSensorCreateManyAndReturnArgs} args - Arguments to create many OnContactSensors.
   * @example
   * // Create many OnContactSensors
   * const onContactSensor = await prisma.onContactSensor.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many OnContactSensors and only return the `id`
   * const onContactSensorWithIdOnly = await prisma.onContactSensor.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends OnContactSensorCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, OnContactSensorCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OnContactSensorPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a OnContactSensor.
   * @param {OnContactSensorDeleteArgs} args - Arguments to delete one OnContactSensor.
   * @example
   * // Delete one OnContactSensor
   * const OnContactSensor = await prisma.onContactSensor.delete({
   *   where: {
   *     // ... filter to delete one OnContactSensor
   *   }
   * })
   * 
   */
  delete<T extends OnContactSensorDeleteArgs>(args: Prisma.SelectSubset<T, OnContactSensorDeleteArgs<ExtArgs>>): Prisma.Prisma__OnContactSensorClient<runtime.Types.Result.GetResult<Prisma.$OnContactSensorPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one OnContactSensor.
   * @param {OnContactSensorUpdateArgs} args - Arguments to update one OnContactSensor.
   * @example
   * // Update one OnContactSensor
   * const onContactSensor = await prisma.onContactSensor.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends OnContactSensorUpdateArgs>(args: Prisma.SelectSubset<T, OnContactSensorUpdateArgs<ExtArgs>>): Prisma.Prisma__OnContactSensorClient<runtime.Types.Result.GetResult<Prisma.$OnContactSensorPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more OnContactSensors.
   * @param {OnContactSensorDeleteManyArgs} args - Arguments to filter OnContactSensors to delete.
   * @example
   * // Delete a few OnContactSensors
   * const { count } = await prisma.onContactSensor.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends OnContactSensorDeleteManyArgs>(args?: Prisma.SelectSubset<T, OnContactSensorDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OnContactSensors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OnContactSensorUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many OnContactSensors
   * const onContactSensor = await prisma.onContactSensor.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends OnContactSensorUpdateManyArgs>(args: Prisma.SelectSubset<T, OnContactSensorUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OnContactSensors and returns the data updated in the database.
   * @param {OnContactSensorUpdateManyAndReturnArgs} args - Arguments to update many OnContactSensors.
   * @example
   * // Update many OnContactSensors
   * const onContactSensor = await prisma.onContactSensor.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more OnContactSensors and only return the `id`
   * const onContactSensorWithIdOnly = await prisma.onContactSensor.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends OnContactSensorUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, OnContactSensorUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OnContactSensorPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one OnContactSensor.
   * @param {OnContactSensorUpsertArgs} args - Arguments to update or create a OnContactSensor.
   * @example
   * // Update or create a OnContactSensor
   * const onContactSensor = await prisma.onContactSensor.upsert({
   *   create: {
   *     // ... data to create a OnContactSensor
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the OnContactSensor we want to update
   *   }
   * })
   */
  upsert<T extends OnContactSensorUpsertArgs>(args: Prisma.SelectSubset<T, OnContactSensorUpsertArgs<ExtArgs>>): Prisma.Prisma__OnContactSensorClient<runtime.Types.Result.GetResult<Prisma.$OnContactSensorPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of OnContactSensors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OnContactSensorCountArgs} args - Arguments to filter OnContactSensors to count.
   * @example
   * // Count the number of OnContactSensors
   * const count = await prisma.onContactSensor.count({
   *   where: {
   *     // ... the filter for the OnContactSensors we want to count
   *   }
   * })
  **/
  count<T extends OnContactSensorCountArgs>(
    args?: Prisma.Subset<T, OnContactSensorCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], OnContactSensorCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a OnContactSensor.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OnContactSensorAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends OnContactSensorAggregateArgs>(args: Prisma.Subset<T, OnContactSensorAggregateArgs>): Prisma.PrismaPromise<GetOnContactSensorAggregateType<T>>

  /**
   * Group by OnContactSensor.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OnContactSensorGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends OnContactSensorGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: OnContactSensorGroupByArgs['orderBy'] }
      : { orderBy?: OnContactSensorGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, OnContactSensorGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOnContactSensorGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the OnContactSensor model
 */
readonly fields: OnContactSensorFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for OnContactSensor.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__OnContactSensorClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  gateway<T extends Prisma.GatewayDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GatewayDefaultArgs<ExtArgs>>): Prisma.Prisma__GatewayClient<runtime.Types.Result.GetResult<Prisma.$GatewayPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  mapping<T extends Prisma.MappingDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MappingDefaultArgs<ExtArgs>>): Prisma.Prisma__MappingClient<runtime.Types.Result.GetResult<Prisma.$MappingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  machines<T extends Prisma.OnContactSensor$machinesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OnContactSensor$machinesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MachinePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the OnContactSensor model
 */
export interface OnContactSensorFieldRefs {
  readonly id: Prisma.FieldRef<"OnContactSensor", 'Int'>
  readonly name: Prisma.FieldRef<"OnContactSensor", 'String'>
  readonly address: Prisma.FieldRef<"OnContactSensor", 'Int'>
  readonly gateway_id: Prisma.FieldRef<"OnContactSensor", 'Int'>
  readonly mapping_id: Prisma.FieldRef<"OnContactSensor", 'Int'>
}
    

// Custom InputTypes
/**
 * OnContactSensor findUnique
 */
export type OnContactSensorFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OnContactSensor
   */
  select?: Prisma.OnContactSensorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OnContactSensor
   */
  omit?: Prisma.OnContactSensorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OnContactSensorInclude<ExtArgs> | null
  /**
   * Filter, which OnContactSensor to fetch.
   */
  where: Prisma.OnContactSensorWhereUniqueInput
}

/**
 * OnContactSensor findUniqueOrThrow
 */
export type OnContactSensorFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OnContactSensor
   */
  select?: Prisma.OnContactSensorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OnContactSensor
   */
  omit?: Prisma.OnContactSensorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OnContactSensorInclude<ExtArgs> | null
  /**
   * Filter, which OnContactSensor to fetch.
   */
  where: Prisma.OnContactSensorWhereUniqueInput
}

/**
 * OnContactSensor findFirst
 */
export type OnContactSensorFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OnContactSensor
   */
  select?: Prisma.OnContactSensorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OnContactSensor
   */
  omit?: Prisma.OnContactSensorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OnContactSensorInclude<ExtArgs> | null
  /**
   * Filter, which OnContactSensor to fetch.
   */
  where?: Prisma.OnContactSensorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OnContactSensors to fetch.
   */
  orderBy?: Prisma.OnContactSensorOrderByWithRelationInput | Prisma.OnContactSensorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OnContactSensors.
   */
  cursor?: Prisma.OnContactSensorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OnContactSensors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OnContactSensors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OnContactSensors.
   */
  distinct?: Prisma.OnContactSensorScalarFieldEnum | Prisma.OnContactSensorScalarFieldEnum[]
}

/**
 * OnContactSensor findFirstOrThrow
 */
export type OnContactSensorFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OnContactSensor
   */
  select?: Prisma.OnContactSensorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OnContactSensor
   */
  omit?: Prisma.OnContactSensorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OnContactSensorInclude<ExtArgs> | null
  /**
   * Filter, which OnContactSensor to fetch.
   */
  where?: Prisma.OnContactSensorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OnContactSensors to fetch.
   */
  orderBy?: Prisma.OnContactSensorOrderByWithRelationInput | Prisma.OnContactSensorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OnContactSensors.
   */
  cursor?: Prisma.OnContactSensorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OnContactSensors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OnContactSensors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OnContactSensors.
   */
  distinct?: Prisma.OnContactSensorScalarFieldEnum | Prisma.OnContactSensorScalarFieldEnum[]
}

/**
 * OnContactSensor findMany
 */
export type OnContactSensorFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OnContactSensor
   */
  select?: Prisma.OnContactSensorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OnContactSensor
   */
  omit?: Prisma.OnContactSensorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OnContactSensorInclude<ExtArgs> | null
  /**
   * Filter, which OnContactSensors to fetch.
   */
  where?: Prisma.OnContactSensorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OnContactSensors to fetch.
   */
  orderBy?: Prisma.OnContactSensorOrderByWithRelationInput | Prisma.OnContactSensorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing OnContactSensors.
   */
  cursor?: Prisma.OnContactSensorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OnContactSensors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OnContactSensors.
   */
  skip?: number
  distinct?: Prisma.OnContactSensorScalarFieldEnum | Prisma.OnContactSensorScalarFieldEnum[]
}

/**
 * OnContactSensor create
 */
export type OnContactSensorCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OnContactSensor
   */
  select?: Prisma.OnContactSensorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OnContactSensor
   */
  omit?: Prisma.OnContactSensorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OnContactSensorInclude<ExtArgs> | null
  /**
   * The data needed to create a OnContactSensor.
   */
  data: Prisma.XOR<Prisma.OnContactSensorCreateInput, Prisma.OnContactSensorUncheckedCreateInput>
}

/**
 * OnContactSensor createMany
 */
export type OnContactSensorCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many OnContactSensors.
   */
  data: Prisma.OnContactSensorCreateManyInput | Prisma.OnContactSensorCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * OnContactSensor createManyAndReturn
 */
export type OnContactSensorCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OnContactSensor
   */
  select?: Prisma.OnContactSensorSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OnContactSensor
   */
  omit?: Prisma.OnContactSensorOmit<ExtArgs> | null
  /**
   * The data used to create many OnContactSensors.
   */
  data: Prisma.OnContactSensorCreateManyInput | Prisma.OnContactSensorCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OnContactSensorIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * OnContactSensor update
 */
export type OnContactSensorUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OnContactSensor
   */
  select?: Prisma.OnContactSensorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OnContactSensor
   */
  omit?: Prisma.OnContactSensorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OnContactSensorInclude<ExtArgs> | null
  /**
   * The data needed to update a OnContactSensor.
   */
  data: Prisma.XOR<Prisma.OnContactSensorUpdateInput, Prisma.OnContactSensorUncheckedUpdateInput>
  /**
   * Choose, which OnContactSensor to update.
   */
  where: Prisma.OnContactSensorWhereUniqueInput
}

/**
 * OnContactSensor updateMany
 */
export type OnContactSensorUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update OnContactSensors.
   */
  data: Prisma.XOR<Prisma.OnContactSensorUpdateManyMutationInput, Prisma.OnContactSensorUncheckedUpdateManyInput>
  /**
   * Filter which OnContactSensors to update
   */
  where?: Prisma.OnContactSensorWhereInput
  /**
   * Limit how many OnContactSensors to update.
   */
  limit?: number
}

/**
 * OnContactSensor updateManyAndReturn
 */
export type OnContactSensorUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OnContactSensor
   */
  select?: Prisma.OnContactSensorSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OnContactSensor
   */
  omit?: Prisma.OnContactSensorOmit<ExtArgs> | null
  /**
   * The data used to update OnContactSensors.
   */
  data: Prisma.XOR<Prisma.OnContactSensorUpdateManyMutationInput, Prisma.OnContactSensorUncheckedUpdateManyInput>
  /**
   * Filter which OnContactSensors to update
   */
  where?: Prisma.OnContactSensorWhereInput
  /**
   * Limit how many OnContactSensors to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OnContactSensorIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * OnContactSensor upsert
 */
export type OnContactSensorUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OnContactSensor
   */
  select?: Prisma.OnContactSensorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OnContactSensor
   */
  omit?: Prisma.OnContactSensorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OnContactSensorInclude<ExtArgs> | null
  /**
   * The filter to search for the OnContactSensor to update in case it exists.
   */
  where: Prisma.OnContactSensorWhereUniqueInput
  /**
   * In case the OnContactSensor found by the `where` argument doesn't exist, create a new OnContactSensor with this data.
   */
  create: Prisma.XOR<Prisma.OnContactSensorCreateInput, Prisma.OnContactSensorUncheckedCreateInput>
  /**
   * In case the OnContactSensor was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.OnContactSensorUpdateInput, Prisma.OnContactSensorUncheckedUpdateInput>
}

/**
 * OnContactSensor delete
 */
export type OnContactSensorDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OnContactSensor
   */
  select?: Prisma.OnContactSensorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OnContactSensor
   */
  omit?: Prisma.OnContactSensorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OnContactSensorInclude<ExtArgs> | null
  /**
   * Filter which OnContactSensor to delete.
   */
  where: Prisma.OnContactSensorWhereUniqueInput
}

/**
 * OnContactSensor deleteMany
 */
export type OnContactSensorDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OnContactSensors to delete
   */
  where?: Prisma.OnContactSensorWhereInput
  /**
   * Limit how many OnContactSensors to delete.
   */
  limit?: number
}

/**
 * OnContactSensor.machines
 */
export type OnContactSensor$machinesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Machine
   */
  select?: Prisma.MachineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Machine
   */
  omit?: Prisma.MachineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MachineInclude<ExtArgs> | null
  where?: Prisma.MachineWhereInput
  orderBy?: Prisma.MachineOrderByWithRelationInput | Prisma.MachineOrderByWithRelationInput[]
  cursor?: Prisma.MachineWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MachineScalarFieldEnum | Prisma.MachineScalarFieldEnum[]
}

/**
 * OnContactSensor without action
 */
export type OnContactSensorDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OnContactSensor
   */
  select?: Prisma.OnContactSensorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OnContactSensor
   */
  omit?: Prisma.OnContactSensorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OnContactSensorInclude<ExtArgs> | null
}
