
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models.ts"
import { type PrismaClient } from "./class.ts"

export type * from '../models.ts'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.1.0
 * Query Engine version: ab635e6b9d606fa5c8fb8b1a7f909c3c3c1c98ba
 */
export const prismaVersion: PrismaVersion = {
  client: "7.1.0",
  engine: "ab635e6b9d606fa5c8fb8b1a7f909c3c3c1c98ba"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  User: 'User',
  Session: 'Session',
  LogHistory: 'LogHistory',
  Condition: 'Condition',
  PowerMeter: 'PowerMeter',
  Gateway: 'Gateway',
  Mapping: 'Mapping',
  TemperatureSensor: 'TemperatureSensor',
  OnContactSensor: 'OnContactSensor',
  AlarmContactSensor: 'AlarmContactSensor',
  Machine: 'Machine',
  McRunHour: 'McRunHour',
  General: 'General',
  Conversion: 'Conversion',
  Smtp: 'Smtp'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "user" | "session" | "logHistory" | "condition" | "powerMeter" | "gateway" | "mapping" | "temperatureSensor" | "onContactSensor" | "alarmContactSensor" | "machine" | "mcRunHour" | "general" | "conversion" | "smtp"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    User: {
      payload: Prisma.$UserPayload<ExtArgs>
      fields: Prisma.UserFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findFirst: {
          args: Prisma.UserFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findMany: {
          args: Prisma.UserFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        create: {
          args: Prisma.UserCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        createMany: {
          args: Prisma.UserCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        delete: {
          args: Prisma.UserDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        update: {
          args: Prisma.UserUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        deleteMany: {
          args: Prisma.UserDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        upsert: {
          args: Prisma.UserUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        aggregate: {
          args: Prisma.UserAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUser>
        }
        groupBy: {
          args: Prisma.UserGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserCountAggregateOutputType> | number
        }
      }
    }
    Session: {
      payload: Prisma.$SessionPayload<ExtArgs>
      fields: Prisma.SessionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.SessionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SessionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.SessionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SessionPayload>
        }
        findFirst: {
          args: Prisma.SessionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SessionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.SessionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SessionPayload>
        }
        findMany: {
          args: Prisma.SessionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SessionPayload>[]
        }
        create: {
          args: Prisma.SessionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SessionPayload>
        }
        createMany: {
          args: Prisma.SessionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.SessionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SessionPayload>[]
        }
        delete: {
          args: Prisma.SessionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SessionPayload>
        }
        update: {
          args: Prisma.SessionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SessionPayload>
        }
        deleteMany: {
          args: Prisma.SessionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.SessionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.SessionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SessionPayload>[]
        }
        upsert: {
          args: Prisma.SessionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SessionPayload>
        }
        aggregate: {
          args: Prisma.SessionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateSession>
        }
        groupBy: {
          args: Prisma.SessionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SessionGroupByOutputType>[]
        }
        count: {
          args: Prisma.SessionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SessionCountAggregateOutputType> | number
        }
      }
    }
    LogHistory: {
      payload: Prisma.$LogHistoryPayload<ExtArgs>
      fields: Prisma.LogHistoryFieldRefs
      operations: {
        findUnique: {
          args: Prisma.LogHistoryFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LogHistoryPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.LogHistoryFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LogHistoryPayload>
        }
        findFirst: {
          args: Prisma.LogHistoryFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LogHistoryPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.LogHistoryFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LogHistoryPayload>
        }
        findMany: {
          args: Prisma.LogHistoryFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LogHistoryPayload>[]
        }
        create: {
          args: Prisma.LogHistoryCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LogHistoryPayload>
        }
        createMany: {
          args: Prisma.LogHistoryCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.LogHistoryCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LogHistoryPayload>[]
        }
        delete: {
          args: Prisma.LogHistoryDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LogHistoryPayload>
        }
        update: {
          args: Prisma.LogHistoryUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LogHistoryPayload>
        }
        deleteMany: {
          args: Prisma.LogHistoryDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.LogHistoryUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.LogHistoryUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LogHistoryPayload>[]
        }
        upsert: {
          args: Prisma.LogHistoryUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LogHistoryPayload>
        }
        aggregate: {
          args: Prisma.LogHistoryAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateLogHistory>
        }
        groupBy: {
          args: Prisma.LogHistoryGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.LogHistoryGroupByOutputType>[]
        }
        count: {
          args: Prisma.LogHistoryCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.LogHistoryCountAggregateOutputType> | number
        }
      }
    }
    Condition: {
      payload: Prisma.$ConditionPayload<ExtArgs>
      fields: Prisma.ConditionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ConditionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConditionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ConditionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConditionPayload>
        }
        findFirst: {
          args: Prisma.ConditionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConditionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ConditionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConditionPayload>
        }
        findMany: {
          args: Prisma.ConditionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConditionPayload>[]
        }
        create: {
          args: Prisma.ConditionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConditionPayload>
        }
        createMany: {
          args: Prisma.ConditionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ConditionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConditionPayload>[]
        }
        delete: {
          args: Prisma.ConditionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConditionPayload>
        }
        update: {
          args: Prisma.ConditionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConditionPayload>
        }
        deleteMany: {
          args: Prisma.ConditionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ConditionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ConditionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConditionPayload>[]
        }
        upsert: {
          args: Prisma.ConditionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConditionPayload>
        }
        aggregate: {
          args: Prisma.ConditionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateCondition>
        }
        groupBy: {
          args: Prisma.ConditionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ConditionGroupByOutputType>[]
        }
        count: {
          args: Prisma.ConditionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ConditionCountAggregateOutputType> | number
        }
      }
    }
    PowerMeter: {
      payload: Prisma.$PowerMeterPayload<ExtArgs>
      fields: Prisma.PowerMeterFieldRefs
      operations: {
        findUnique: {
          args: Prisma.PowerMeterFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PowerMeterPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.PowerMeterFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PowerMeterPayload>
        }
        findFirst: {
          args: Prisma.PowerMeterFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PowerMeterPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.PowerMeterFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PowerMeterPayload>
        }
        findMany: {
          args: Prisma.PowerMeterFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PowerMeterPayload>[]
        }
        create: {
          args: Prisma.PowerMeterCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PowerMeterPayload>
        }
        createMany: {
          args: Prisma.PowerMeterCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.PowerMeterCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PowerMeterPayload>[]
        }
        delete: {
          args: Prisma.PowerMeterDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PowerMeterPayload>
        }
        update: {
          args: Prisma.PowerMeterUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PowerMeterPayload>
        }
        deleteMany: {
          args: Prisma.PowerMeterDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.PowerMeterUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.PowerMeterUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PowerMeterPayload>[]
        }
        upsert: {
          args: Prisma.PowerMeterUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PowerMeterPayload>
        }
        aggregate: {
          args: Prisma.PowerMeterAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregatePowerMeter>
        }
        groupBy: {
          args: Prisma.PowerMeterGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PowerMeterGroupByOutputType>[]
        }
        count: {
          args: Prisma.PowerMeterCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PowerMeterCountAggregateOutputType> | number
        }
      }
    }
    Gateway: {
      payload: Prisma.$GatewayPayload<ExtArgs>
      fields: Prisma.GatewayFieldRefs
      operations: {
        findUnique: {
          args: Prisma.GatewayFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GatewayPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.GatewayFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GatewayPayload>
        }
        findFirst: {
          args: Prisma.GatewayFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GatewayPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.GatewayFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GatewayPayload>
        }
        findMany: {
          args: Prisma.GatewayFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GatewayPayload>[]
        }
        create: {
          args: Prisma.GatewayCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GatewayPayload>
        }
        createMany: {
          args: Prisma.GatewayCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.GatewayCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GatewayPayload>[]
        }
        delete: {
          args: Prisma.GatewayDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GatewayPayload>
        }
        update: {
          args: Prisma.GatewayUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GatewayPayload>
        }
        deleteMany: {
          args: Prisma.GatewayDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.GatewayUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.GatewayUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GatewayPayload>[]
        }
        upsert: {
          args: Prisma.GatewayUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GatewayPayload>
        }
        aggregate: {
          args: Prisma.GatewayAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateGateway>
        }
        groupBy: {
          args: Prisma.GatewayGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.GatewayGroupByOutputType>[]
        }
        count: {
          args: Prisma.GatewayCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.GatewayCountAggregateOutputType> | number
        }
      }
    }
    Mapping: {
      payload: Prisma.$MappingPayload<ExtArgs>
      fields: Prisma.MappingFieldRefs
      operations: {
        findUnique: {
          args: Prisma.MappingFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MappingPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.MappingFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MappingPayload>
        }
        findFirst: {
          args: Prisma.MappingFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MappingPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.MappingFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MappingPayload>
        }
        findMany: {
          args: Prisma.MappingFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MappingPayload>[]
        }
        create: {
          args: Prisma.MappingCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MappingPayload>
        }
        createMany: {
          args: Prisma.MappingCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.MappingCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MappingPayload>[]
        }
        delete: {
          args: Prisma.MappingDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MappingPayload>
        }
        update: {
          args: Prisma.MappingUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MappingPayload>
        }
        deleteMany: {
          args: Prisma.MappingDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.MappingUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.MappingUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MappingPayload>[]
        }
        upsert: {
          args: Prisma.MappingUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MappingPayload>
        }
        aggregate: {
          args: Prisma.MappingAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateMapping>
        }
        groupBy: {
          args: Prisma.MappingGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MappingGroupByOutputType>[]
        }
        count: {
          args: Prisma.MappingCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MappingCountAggregateOutputType> | number
        }
      }
    }
    TemperatureSensor: {
      payload: Prisma.$TemperatureSensorPayload<ExtArgs>
      fields: Prisma.TemperatureSensorFieldRefs
      operations: {
        findUnique: {
          args: Prisma.TemperatureSensorFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemperatureSensorPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.TemperatureSensorFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemperatureSensorPayload>
        }
        findFirst: {
          args: Prisma.TemperatureSensorFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemperatureSensorPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.TemperatureSensorFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemperatureSensorPayload>
        }
        findMany: {
          args: Prisma.TemperatureSensorFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemperatureSensorPayload>[]
        }
        create: {
          args: Prisma.TemperatureSensorCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemperatureSensorPayload>
        }
        createMany: {
          args: Prisma.TemperatureSensorCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.TemperatureSensorCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemperatureSensorPayload>[]
        }
        delete: {
          args: Prisma.TemperatureSensorDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemperatureSensorPayload>
        }
        update: {
          args: Prisma.TemperatureSensorUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemperatureSensorPayload>
        }
        deleteMany: {
          args: Prisma.TemperatureSensorDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.TemperatureSensorUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.TemperatureSensorUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemperatureSensorPayload>[]
        }
        upsert: {
          args: Prisma.TemperatureSensorUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemperatureSensorPayload>
        }
        aggregate: {
          args: Prisma.TemperatureSensorAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateTemperatureSensor>
        }
        groupBy: {
          args: Prisma.TemperatureSensorGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TemperatureSensorGroupByOutputType>[]
        }
        count: {
          args: Prisma.TemperatureSensorCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TemperatureSensorCountAggregateOutputType> | number
        }
      }
    }
    OnContactSensor: {
      payload: Prisma.$OnContactSensorPayload<ExtArgs>
      fields: Prisma.OnContactSensorFieldRefs
      operations: {
        findUnique: {
          args: Prisma.OnContactSensorFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OnContactSensorPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.OnContactSensorFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OnContactSensorPayload>
        }
        findFirst: {
          args: Prisma.OnContactSensorFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OnContactSensorPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.OnContactSensorFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OnContactSensorPayload>
        }
        findMany: {
          args: Prisma.OnContactSensorFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OnContactSensorPayload>[]
        }
        create: {
          args: Prisma.OnContactSensorCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OnContactSensorPayload>
        }
        createMany: {
          args: Prisma.OnContactSensorCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.OnContactSensorCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OnContactSensorPayload>[]
        }
        delete: {
          args: Prisma.OnContactSensorDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OnContactSensorPayload>
        }
        update: {
          args: Prisma.OnContactSensorUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OnContactSensorPayload>
        }
        deleteMany: {
          args: Prisma.OnContactSensorDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.OnContactSensorUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.OnContactSensorUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OnContactSensorPayload>[]
        }
        upsert: {
          args: Prisma.OnContactSensorUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OnContactSensorPayload>
        }
        aggregate: {
          args: Prisma.OnContactSensorAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateOnContactSensor>
        }
        groupBy: {
          args: Prisma.OnContactSensorGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.OnContactSensorGroupByOutputType>[]
        }
        count: {
          args: Prisma.OnContactSensorCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.OnContactSensorCountAggregateOutputType> | number
        }
      }
    }
    AlarmContactSensor: {
      payload: Prisma.$AlarmContactSensorPayload<ExtArgs>
      fields: Prisma.AlarmContactSensorFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AlarmContactSensorFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AlarmContactSensorPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AlarmContactSensorFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AlarmContactSensorPayload>
        }
        findFirst: {
          args: Prisma.AlarmContactSensorFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AlarmContactSensorPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AlarmContactSensorFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AlarmContactSensorPayload>
        }
        findMany: {
          args: Prisma.AlarmContactSensorFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AlarmContactSensorPayload>[]
        }
        create: {
          args: Prisma.AlarmContactSensorCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AlarmContactSensorPayload>
        }
        createMany: {
          args: Prisma.AlarmContactSensorCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AlarmContactSensorCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AlarmContactSensorPayload>[]
        }
        delete: {
          args: Prisma.AlarmContactSensorDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AlarmContactSensorPayload>
        }
        update: {
          args: Prisma.AlarmContactSensorUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AlarmContactSensorPayload>
        }
        deleteMany: {
          args: Prisma.AlarmContactSensorDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AlarmContactSensorUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AlarmContactSensorUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AlarmContactSensorPayload>[]
        }
        upsert: {
          args: Prisma.AlarmContactSensorUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AlarmContactSensorPayload>
        }
        aggregate: {
          args: Prisma.AlarmContactSensorAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAlarmContactSensor>
        }
        groupBy: {
          args: Prisma.AlarmContactSensorGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AlarmContactSensorGroupByOutputType>[]
        }
        count: {
          args: Prisma.AlarmContactSensorCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AlarmContactSensorCountAggregateOutputType> | number
        }
      }
    }
    Machine: {
      payload: Prisma.$MachinePayload<ExtArgs>
      fields: Prisma.MachineFieldRefs
      operations: {
        findUnique: {
          args: Prisma.MachineFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MachinePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.MachineFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MachinePayload>
        }
        findFirst: {
          args: Prisma.MachineFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MachinePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.MachineFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MachinePayload>
        }
        findMany: {
          args: Prisma.MachineFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MachinePayload>[]
        }
        create: {
          args: Prisma.MachineCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MachinePayload>
        }
        createMany: {
          args: Prisma.MachineCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.MachineCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MachinePayload>[]
        }
        delete: {
          args: Prisma.MachineDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MachinePayload>
        }
        update: {
          args: Prisma.MachineUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MachinePayload>
        }
        deleteMany: {
          args: Prisma.MachineDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.MachineUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.MachineUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MachinePayload>[]
        }
        upsert: {
          args: Prisma.MachineUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MachinePayload>
        }
        aggregate: {
          args: Prisma.MachineAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateMachine>
        }
        groupBy: {
          args: Prisma.MachineGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MachineGroupByOutputType>[]
        }
        count: {
          args: Prisma.MachineCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MachineCountAggregateOutputType> | number
        }
      }
    }
    McRunHour: {
      payload: Prisma.$McRunHourPayload<ExtArgs>
      fields: Prisma.McRunHourFieldRefs
      operations: {
        findUnique: {
          args: Prisma.McRunHourFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$McRunHourPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.McRunHourFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$McRunHourPayload>
        }
        findFirst: {
          args: Prisma.McRunHourFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$McRunHourPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.McRunHourFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$McRunHourPayload>
        }
        findMany: {
          args: Prisma.McRunHourFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$McRunHourPayload>[]
        }
        create: {
          args: Prisma.McRunHourCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$McRunHourPayload>
        }
        createMany: {
          args: Prisma.McRunHourCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.McRunHourCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$McRunHourPayload>[]
        }
        delete: {
          args: Prisma.McRunHourDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$McRunHourPayload>
        }
        update: {
          args: Prisma.McRunHourUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$McRunHourPayload>
        }
        deleteMany: {
          args: Prisma.McRunHourDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.McRunHourUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.McRunHourUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$McRunHourPayload>[]
        }
        upsert: {
          args: Prisma.McRunHourUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$McRunHourPayload>
        }
        aggregate: {
          args: Prisma.McRunHourAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateMcRunHour>
        }
        groupBy: {
          args: Prisma.McRunHourGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.McRunHourGroupByOutputType>[]
        }
        count: {
          args: Prisma.McRunHourCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.McRunHourCountAggregateOutputType> | number
        }
      }
    }
    General: {
      payload: Prisma.$GeneralPayload<ExtArgs>
      fields: Prisma.GeneralFieldRefs
      operations: {
        findUnique: {
          args: Prisma.GeneralFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GeneralPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.GeneralFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GeneralPayload>
        }
        findFirst: {
          args: Prisma.GeneralFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GeneralPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.GeneralFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GeneralPayload>
        }
        findMany: {
          args: Prisma.GeneralFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GeneralPayload>[]
        }
        create: {
          args: Prisma.GeneralCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GeneralPayload>
        }
        createMany: {
          args: Prisma.GeneralCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.GeneralCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GeneralPayload>[]
        }
        delete: {
          args: Prisma.GeneralDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GeneralPayload>
        }
        update: {
          args: Prisma.GeneralUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GeneralPayload>
        }
        deleteMany: {
          args: Prisma.GeneralDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.GeneralUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.GeneralUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GeneralPayload>[]
        }
        upsert: {
          args: Prisma.GeneralUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GeneralPayload>
        }
        aggregate: {
          args: Prisma.GeneralAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateGeneral>
        }
        groupBy: {
          args: Prisma.GeneralGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.GeneralGroupByOutputType>[]
        }
        count: {
          args: Prisma.GeneralCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.GeneralCountAggregateOutputType> | number
        }
      }
    }
    Conversion: {
      payload: Prisma.$ConversionPayload<ExtArgs>
      fields: Prisma.ConversionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ConversionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ConversionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversionPayload>
        }
        findFirst: {
          args: Prisma.ConversionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ConversionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversionPayload>
        }
        findMany: {
          args: Prisma.ConversionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversionPayload>[]
        }
        create: {
          args: Prisma.ConversionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversionPayload>
        }
        createMany: {
          args: Prisma.ConversionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ConversionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversionPayload>[]
        }
        delete: {
          args: Prisma.ConversionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversionPayload>
        }
        update: {
          args: Prisma.ConversionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversionPayload>
        }
        deleteMany: {
          args: Prisma.ConversionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ConversionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ConversionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversionPayload>[]
        }
        upsert: {
          args: Prisma.ConversionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversionPayload>
        }
        aggregate: {
          args: Prisma.ConversionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateConversion>
        }
        groupBy: {
          args: Prisma.ConversionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ConversionGroupByOutputType>[]
        }
        count: {
          args: Prisma.ConversionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ConversionCountAggregateOutputType> | number
        }
      }
    }
    Smtp: {
      payload: Prisma.$SmtpPayload<ExtArgs>
      fields: Prisma.SmtpFieldRefs
      operations: {
        findUnique: {
          args: Prisma.SmtpFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SmtpPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.SmtpFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SmtpPayload>
        }
        findFirst: {
          args: Prisma.SmtpFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SmtpPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.SmtpFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SmtpPayload>
        }
        findMany: {
          args: Prisma.SmtpFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SmtpPayload>[]
        }
        create: {
          args: Prisma.SmtpCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SmtpPayload>
        }
        createMany: {
          args: Prisma.SmtpCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.SmtpCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SmtpPayload>[]
        }
        delete: {
          args: Prisma.SmtpDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SmtpPayload>
        }
        update: {
          args: Prisma.SmtpUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SmtpPayload>
        }
        deleteMany: {
          args: Prisma.SmtpDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.SmtpUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.SmtpUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SmtpPayload>[]
        }
        upsert: {
          args: Prisma.SmtpUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SmtpPayload>
        }
        aggregate: {
          args: Prisma.SmtpAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateSmtp>
        }
        groupBy: {
          args: Prisma.SmtpGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SmtpGroupByOutputType>[]
        }
        count: {
          args: Prisma.SmtpCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SmtpCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  password: 'password',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const SessionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  expiresAt: 'expiresAt'
} as const

export type SessionScalarFieldEnum = (typeof SessionScalarFieldEnum)[keyof typeof SessionScalarFieldEnum]


export const LogHistoryScalarFieldEnum = {
  id: 'id',
  on_contact: 'on_contact',
  alarm_contact: 'alarm_contact',
  temperature: 'temperature',
  kwh: 'kwh',
  timestamp: 'timestamp',
  machine_id: 'machine_id'
} as const

export type LogHistoryScalarFieldEnum = (typeof LogHistoryScalarFieldEnum)[keyof typeof LogHistoryScalarFieldEnum]


export const ConditionScalarFieldEnum = {
  id: 'id',
  current_timestamp: 'current_timestamp',
  last_timstamp: 'last_timstamp',
  current_condition: 'current_condition',
  last_condition: 'last_condition',
  current_kwh: 'current_kwh',
  last_kwh: 'last_kwh',
  machine_id: 'machine_id'
} as const

export type ConditionScalarFieldEnum = (typeof ConditionScalarFieldEnum)[keyof typeof ConditionScalarFieldEnum]


export const PowerMeterScalarFieldEnum = {
  id: 'id',
  name: 'name',
  address: 'address',
  gateway_id: 'gateway_id',
  mapping_id: 'mapping_id'
} as const

export type PowerMeterScalarFieldEnum = (typeof PowerMeterScalarFieldEnum)[keyof typeof PowerMeterScalarFieldEnum]


export const GatewayScalarFieldEnum = {
  id: 'id',
  name: 'name',
  protocol: 'protocol',
  config: 'config'
} as const

export type GatewayScalarFieldEnum = (typeof GatewayScalarFieldEnum)[keyof typeof GatewayScalarFieldEnum]


export const MappingScalarFieldEnum = {
  id: 'id',
  type: 'type',
  params: 'params'
} as const

export type MappingScalarFieldEnum = (typeof MappingScalarFieldEnum)[keyof typeof MappingScalarFieldEnum]


export const TemperatureSensorScalarFieldEnum = {
  id: 'id',
  name: 'name',
  address: 'address',
  gateway_id: 'gateway_id',
  mapping_id: 'mapping_id'
} as const

export type TemperatureSensorScalarFieldEnum = (typeof TemperatureSensorScalarFieldEnum)[keyof typeof TemperatureSensorScalarFieldEnum]


export const OnContactSensorScalarFieldEnum = {
  id: 'id',
  name: 'name',
  address: 'address',
  gateway_id: 'gateway_id',
  mapping_id: 'mapping_id'
} as const

export type OnContactSensorScalarFieldEnum = (typeof OnContactSensorScalarFieldEnum)[keyof typeof OnContactSensorScalarFieldEnum]


export const AlarmContactSensorScalarFieldEnum = {
  id: 'id',
  name: 'name',
  address: 'address',
  gateway_id: 'gateway_id',
  mapping_id: 'mapping_id'
} as const

export type AlarmContactSensorScalarFieldEnum = (typeof AlarmContactSensorScalarFieldEnum)[keyof typeof AlarmContactSensorScalarFieldEnum]


export const MachineScalarFieldEnum = {
  id: 'id',
  name: 'name',
  power_meter_id: 'power_meter_id',
  temperature_sensor_id: 'temperature_sensor_id',
  on_contact_sensor_id: 'on_contact_sensor_id',
  alarm_contact_sensor_id: 'alarm_contact_sensor_id'
} as const

export type MachineScalarFieldEnum = (typeof MachineScalarFieldEnum)[keyof typeof MachineScalarFieldEnum]


export const McRunHourScalarFieldEnum = {
  id: 'id',
  date: 'date',
  machine_id: 'machine_id',
  mc_run_h: 'mc_run_h',
  mc_run_kwh: 'mc_run_kwh',
  heat_up_h: 'heat_up_h',
  heat_up_kwh: 'heat_up_kwh',
  iddle_h: 'iddle_h',
  iddle_kwh: 'iddle_kwh',
  mc_production_h: 'mc_production_h',
  mc_production_kwh: 'mc_production_kwh',
  is_one_block: 'is_one_block'
} as const

export type McRunHourScalarFieldEnum = (typeof McRunHourScalarFieldEnum)[keyof typeof McRunHourScalarFieldEnum]


export const GeneralScalarFieldEnum = {
  key: 'key',
  c_name: 'c_name',
  c_logo: 'c_logo',
  license_key: 'license_key',
  log_freq: 'log_freq'
} as const

export type GeneralScalarFieldEnum = (typeof GeneralScalarFieldEnum)[keyof typeof GeneralScalarFieldEnum]


export const ConversionScalarFieldEnum = {
  key: 'key',
  co2_value: 'co2_value',
  cost_value: 'cost_value'
} as const

export type ConversionScalarFieldEnum = (typeof ConversionScalarFieldEnum)[keyof typeof ConversionScalarFieldEnum]


export const SmtpScalarFieldEnum = {
  key: 'key',
  host: 'host',
  port: 'port',
  email: 'email',
  password: 'password'
} as const

export type SmtpScalarFieldEnum = (typeof SmtpScalarFieldEnum)[keyof typeof SmtpScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]



/**
 * Field references
 */


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'RoleUser'
 */
export type EnumRoleUserFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'RoleUser'>
    


/**
 * Reference to a field of type 'RoleUser[]'
 */
export type ListEnumRoleUserFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'RoleUser[]'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime[]'>
    


/**
 * Reference to a field of type 'Json'
 */
export type JsonFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Json'>
    


/**
 * Reference to a field of type 'QueryMode'
 */
export type EnumQueryModeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'QueryMode'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
}
export type GlobalOmitConfig = {
  user?: Prisma.UserOmit
  session?: Prisma.SessionOmit
  logHistory?: Prisma.LogHistoryOmit
  condition?: Prisma.ConditionOmit
  powerMeter?: Prisma.PowerMeterOmit
  gateway?: Prisma.GatewayOmit
  mapping?: Prisma.MappingOmit
  temperatureSensor?: Prisma.TemperatureSensorOmit
  onContactSensor?: Prisma.OnContactSensorOmit
  alarmContactSensor?: Prisma.AlarmContactSensorOmit
  machine?: Prisma.MachineOmit
  mcRunHour?: Prisma.McRunHourOmit
  general?: Prisma.GeneralOmit
  conversion?: Prisma.ConversionOmit
  smtp?: Prisma.SmtpOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

