
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.ts'
export type * from './prismaNamespace.ts'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Session: 'Session',
  LogHistory: 'LogHistory',
  Condition: 'Condition',
  PowerMeter: 'PowerMeter',
  Gateway: 'Gateway',
  Mapping: 'Mapping',
  TemperatureSensor: 'TemperatureSensor',
  OnContactSensor: 'OnContactSensor',
  AlarmContactSensor: 'AlarmContactSensor',
  Machine: 'Machine',
  McRunHour: 'McRunHour',
  General: 'General',
  Conversion: 'Conversion',
  Smtp: 'Smtp'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  password: 'password',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const SessionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  expiresAt: 'expiresAt'
} as const

export type SessionScalarFieldEnum = (typeof SessionScalarFieldEnum)[keyof typeof SessionScalarFieldEnum]


export const LogHistoryScalarFieldEnum = {
  id: 'id',
  on_contact: 'on_contact',
  alarm_contact: 'alarm_contact',
  temperature: 'temperature',
  kwh: 'kwh',
  timestamp: 'timestamp',
  machine_id: 'machine_id'
} as const

export type LogHistoryScalarFieldEnum = (typeof LogHistoryScalarFieldEnum)[keyof typeof LogHistoryScalarFieldEnum]


export const ConditionScalarFieldEnum = {
  id: 'id',
  current_timestamp: 'current_timestamp',
  last_timstamp: 'last_timstamp',
  current_condition: 'current_condition',
  last_condition: 'last_condition',
  current_kwh: 'current_kwh',
  last_kwh: 'last_kwh',
  machine_id: 'machine_id'
} as const

export type ConditionScalarFieldEnum = (typeof ConditionScalarFieldEnum)[keyof typeof ConditionScalarFieldEnum]


export const PowerMeterScalarFieldEnum = {
  id: 'id',
  name: 'name',
  address: 'address',
  gateway_id: 'gateway_id',
  mapping_id: 'mapping_id'
} as const

export type PowerMeterScalarFieldEnum = (typeof PowerMeterScalarFieldEnum)[keyof typeof PowerMeterScalarFieldEnum]


export const GatewayScalarFieldEnum = {
  id: 'id',
  name: 'name',
  protocol: 'protocol',
  config: 'config'
} as const

export type GatewayScalarFieldEnum = (typeof GatewayScalarFieldEnum)[keyof typeof GatewayScalarFieldEnum]


export const MappingScalarFieldEnum = {
  id: 'id',
  type: 'type',
  params: 'params'
} as const

export type MappingScalarFieldEnum = (typeof MappingScalarFieldEnum)[keyof typeof MappingScalarFieldEnum]


export const TemperatureSensorScalarFieldEnum = {
  id: 'id',
  name: 'name',
  address: 'address',
  gateway_id: 'gateway_id',
  mapping_id: 'mapping_id'
} as const

export type TemperatureSensorScalarFieldEnum = (typeof TemperatureSensorScalarFieldEnum)[keyof typeof TemperatureSensorScalarFieldEnum]


export const OnContactSensorScalarFieldEnum = {
  id: 'id',
  name: 'name',
  address: 'address',
  gateway_id: 'gateway_id',
  mapping_id: 'mapping_id'
} as const

export type OnContactSensorScalarFieldEnum = (typeof OnContactSensorScalarFieldEnum)[keyof typeof OnContactSensorScalarFieldEnum]


export const AlarmContactSensorScalarFieldEnum = {
  id: 'id',
  name: 'name',
  address: 'address',
  gateway_id: 'gateway_id',
  mapping_id: 'mapping_id'
} as const

export type AlarmContactSensorScalarFieldEnum = (typeof AlarmContactSensorScalarFieldEnum)[keyof typeof AlarmContactSensorScalarFieldEnum]


export const MachineScalarFieldEnum = {
  id: 'id',
  name: 'name',
  power_meter_id: 'power_meter_id',
  temperature_sensor_id: 'temperature_sensor_id',
  on_contact_sensor_id: 'on_contact_sensor_id',
  alarm_contact_sensor_id: 'alarm_contact_sensor_id'
} as const

export type MachineScalarFieldEnum = (typeof MachineScalarFieldEnum)[keyof typeof MachineScalarFieldEnum]


export const McRunHourScalarFieldEnum = {
  id: 'id',
  date: 'date',
  machine_id: 'machine_id',
  mc_run_h: 'mc_run_h',
  mc_run_kwh: 'mc_run_kwh',
  heat_up_h: 'heat_up_h',
  heat_up_kwh: 'heat_up_kwh',
  iddle_h: 'iddle_h',
  iddle_kwh: 'iddle_kwh',
  mc_production_h: 'mc_production_h',
  mc_production_kwh: 'mc_production_kwh',
  is_one_block: 'is_one_block'
} as const

export type McRunHourScalarFieldEnum = (typeof McRunHourScalarFieldEnum)[keyof typeof McRunHourScalarFieldEnum]


export const GeneralScalarFieldEnum = {
  key: 'key',
  c_name: 'c_name',
  c_logo: 'c_logo',
  license_key: 'license_key',
  log_freq: 'log_freq'
} as const

export type GeneralScalarFieldEnum = (typeof GeneralScalarFieldEnum)[keyof typeof GeneralScalarFieldEnum]


export const ConversionScalarFieldEnum = {
  key: 'key',
  co2_value: 'co2_value',
  cost_value: 'cost_value'
} as const

export type ConversionScalarFieldEnum = (typeof ConversionScalarFieldEnum)[keyof typeof ConversionScalarFieldEnum]


export const SmtpScalarFieldEnum = {
  key: 'key',
  host: 'host',
  port: 'port',
  email: 'email',
  password: 'password'
} as const

export type SmtpScalarFieldEnum = (typeof SmtpScalarFieldEnum)[keyof typeof SmtpScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: 'JsonNull'
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: 'DbNull',
  JsonNull: 'JsonNull',
  AnyNull: 'AnyNull'
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

